"""Real Estate National batch 14 — questions 651-700."""
import json, pathlib

Q = pathlib.Path("src/data/real-estate-national-questions.json")
data = json.loads(Q.read_text(encoding="utf-8"))

new_qs = [
  # ── Contracts (9) ───────────────────────────────────────────────────────
  {"id":"re-nat-651","domain":"Contracts","type":"single-choice",
   "question":"An escrow holder (closing agent) holding earnest money owes duties to:",
   "choices":["BOTH parties as a NEUTRAL STAKEHOLDER — the escrow holder must follow the escrow instructions exactly, not favor either party, account for the funds, disburse only per the agreement or a court order, and exercise reasonable care; the escrow holder is NOT an advocate for either party","Only the buyer","Only the seller","Only the lender"],
   "correctAnswer":0,
   "explanation":"The escrow holder (closing/settlement agent) is a NEUTRAL STAKEHOLDER owing duties to BOTH parties: (1) FOLLOW ESCROW INSTRUCTIONS EXACTLY — disburse funds and documents only as the joint instructions or the contract specify; (2) NEUTRALITY — not favor either party; cannot take sides in disputes; (3) ACCOUNT for all funds — maintain accurate records, segregated trust accounts; (4) DISBURSE only per the agreement OR a court order — when parties dispute, the escrow holder typically must hold funds until resolution (or interplead); (5) REASONABLE CARE — verify proper documentation, identify, and execution. The escrow holder is NOT an advocate for either party — distinct from the real estate licensee who represents one client. Escrow holder breaches (improper disbursement, negligence, fraud) expose them to liability — which is why CLOSING PROTECTION LETTERS exist to protect lenders/buyers."},

  {"id":"re-nat-652","domain":"Contracts","type":"single-choice",
   "question":"A buyer's purchase contract has a 10-day inspection contingency. To PROCEED with the purchase after a satisfactory inspection, the buyer typically:",
   "choices":["Must do nothing","DELIVERS WRITTEN NOTICE removing/waiving the contingency (or, under some contracts, the contingency is deemed automatically removed if the buyer takes no action within the period — a 'passive' removal); the specific mechanism depends on whether the contract uses ACTIVE removal (buyer must affirmatively waive) or PASSIVE removal (silence = waiver) — buyers must understand which their contract uses","Must terminate","Must extend"],
   "correctAnswer":1,
   "explanation":"INSPECTION CONTINGENCY REMOVAL mechanics — critical to understand: (1) ACTIVE REMOVAL contracts (common in some states like California) — the contingency remains in effect UNTIL the buyer AFFIRMATIVELY DELIVERS WRITTEN NOTICE removing/waiving it; if the buyer does nothing, the contingency REMAINS and the buyer can still terminate even past the stated period (until the seller delivers a notice to perform); (2) PASSIVE REMOVAL contracts (common in other states) — the contingency is DEEMED AUTOMATICALLY REMOVED if the buyer takes no action within the period (SILENCE = WAIVER); if the buyer wants to terminate based on inspection, they must AFFIRMATIVELY deliver notice within the period; (3) DANGER — buyers and agents MUST KNOW which model their contract uses. Misunderstanding the mechanism is a frequent source of disputes and missed deadlines. Best practice: deliver clear written notice (of either intent to proceed or to terminate) within the period regardless of the model."},

  {"id":"re-nat-653","domain":"Contracts","type":"single-choice",
   "question":"A property is sold 'AS IS' but the contract still grants the buyer a RIGHT TO INSPECT. The combined effect is:",
   "choices":["No inspection allowed","Seller must repair everything","The buyer CAN INSPECT and, depending on the contract, may TERMINATE based on inspection findings — but the SELLER is NOT OBLIGATED TO MAKE REPAIRS; 'as is' means the buyer accepts the property's condition (no repair obligation on seller), while the inspection right lets the buyer investigate and decide whether to proceed or (if the contract allows) terminate; 'as is' does NOT waive the seller's disclosure obligations","No effect"],
   "correctAnswer":2,
   "explanation":"'AS IS' WITH RIGHT TO INSPECT — a common and important combination: (1) 'AS IS' means: the SELLER WILL NOT MAKE REPAIRS; the buyer accepts the property's PHYSICAL CONDITION as it exists; (2) RIGHT TO INSPECT means: the buyer CAN STILL INVESTIGATE the property's condition (hire inspectors, conduct due diligence); (3) COMBINED EFFECT: the buyer inspects and DECIDES whether to (a) PROCEED with the purchase accepting the condition, or (b) TERMINATE (if the contract's inspection contingency allows termination based on findings); the seller is not obligated to negotiate repairs or credits (though parties may still negotiate); (4) DISCLOSURE NOT WAIVED — 'as is' does NOT excuse the seller from disclosing KNOWN MATERIAL DEFECTS or from liability for fraud/active concealment; (5) PRACTICAL — 'as is' shifts repair responsibility and negotiation leverage but doesn't eliminate the buyer's investigation right or the seller's honesty obligations. Common in: estate sales, foreclosures, distressed properties, investor purchases."},

  {"id":"re-nat-654","domain":"Contracts","type":"single-choice",
   "question":"A backup contract automatically becomes the primary contract when the first contract terminates. At that moment, the backup buyer typically:",
   "choices":["Must renegotiate","Loses their deposit","Has no rights","STEPS INTO THE PRIMARY POSITION on the previously-agreed backup terms — contingency periods and deadlines typically begin running from the activation date (or per the backup contract's specific terms); the backup buyer should be PROMPTLY NOTIFIED of activation and the new timeline; the backup contract should clearly specify how activation works to avoid disputes"],
   "correctAnswer":3,
   "explanation":"BACKUP CONTRACT ACTIVATION mechanics: (1) AUTOMATIC ELEVATION — when the first contract terminates, the backup AUTOMATICALLY becomes the primary contract on the previously-agreed terms (no renegotiation needed, unless the backup contract requires it); (2) TIMELINE RESET — contingency periods (inspection, financing, appraisal) typically begin running from the ACTIVATION DATE (or per the backup contract's specific terms — some specify deadlines based on the original timeline); (3) PROMPT NOTIFICATION — the backup buyer should be PROMPTLY NOTIFIED of activation and the new timeline (the seller/agent has a duty to notify); (4) EARNEST MONEY — the backup buyer's earnest money becomes the active deposit (procedures should be specified); (5) WELL-DRAFTED BACKUP CONTRACTS specify: how activation occurs, when timelines start, notification requirements, and any conditions to activation. AMBIGUOUS backup contracts are a source of disputes — best practice is detailed activation provisions and prompt written notification at activation."},

  {"id":"re-nat-655","domain":"Contracts","type":"single-choice",
   "question":"A buyer assigns their purchase contract to a third party for a $10,000 'assignment fee.' This practice:",
   "choices":["IS GENERALLY LEGAL IF the contract permits assignment (or doesn't prohibit it) AND the assignment fee and arrangement are properly disclosed to all parties as required by applicable state law; some states have specific disclosure requirements for 'wholesaling' real estate; failure to comply (undisclosed assignments, acting as an unlicensed broker, or violating anti-flipping rules) can result in liability, license issues, or unenforceable contracts","Is always illegal","Requires no disclosure","Eliminates seller rights"],
   "correctAnswer":0,
   "explanation":"CONTRACT ASSIGNMENT FOR A FEE (often called 'wholesaling' in real estate investing): (1) GENERALLY LEGAL IF: (a) the contract PERMITS assignment (or doesn't prohibit it — many contracts have anti-assignment clauses); (b) the assignment and fee are PROPERLY DISCLOSED to all parties as required by applicable state law; (2) STATE-SPECIFIC RULES — several states have enacted SPECIFIC WHOLESALING DISCLOSURE REQUIREMENTS — requiring the wholesaler to disclose their assignment intent, the fee, and their non-ownership; some states require wholesalers to hold a real estate license; (3) RISKS OF NON-COMPLIANCE: (a) UNLICENSED BROKERAGE — if the wholesaler is acting as an unlicensed broker (marketing others' property for compensation), they can face penalties; (b) UNDISCLOSED ASSIGNMENTS — fraud or misrepresentation claims; (c) ANTI-FLIPPING RULES — FHA and some lenders have rules about rapid resale; (4) BEST PRACTICE — proper disclosure, understanding state-specific wholesaling rules, and considering whether a license is required. The legal landscape for wholesaling is evolving with several states tightening rules."},

  {"id":"re-nat-656","domain":"Contracts","type":"single-choice",
   "question":"To satisfy the STATUTE OF FRAUDS for a real estate contract, the writing must generally contain:",
   "choices":["Notarization always","Witness signatures always","THE ESSENTIAL TERMS — identification of the parties, description of the property, the price (or a method to determine it), and the SIGNATURE OF THE PARTY TO BE CHARGED (the party against whom enforcement is sought); the writing need not be a single formal document — multiple writings can be combined if they reference the same transaction; need not be notarized to be enforceable between the parties","Federal registration"],
   "correctAnswer":2,
   "explanation":"STATUTE OF FRAUDS WRITING REQUIREMENTS for real estate contracts: (1) ESSENTIAL TERMS that must appear: (a) IDENTIFICATION OF THE PARTIES; (b) DESCRIPTION OF THE PROPERTY (adequate to identify it — formal legal description is best but adequate description may suffice); (c) PRICE (or a method to determine it); (d) SIGNATURE OF THE PARTY TO BE CHARGED — the party against whom enforcement is sought must have signed (the other party need not have signed for enforcement against the signer); (2) MULTIPLE WRITINGS — the writing need NOT be a single formal document; multiple writings (e.g., letters, emails, memos) can be combined if they reference the same transaction and at least one is signed; (3) NOTARIZATION NOT REQUIRED for enforceability between the parties (notarization IS typically required for the DEED to be RECORDABLE — a separate issue); (4) ELECTRONIC SIGNATURES — generally satisfy the signature requirement under ESIGN/UETA; (5) EXCEPTIONS — part performance, promissory estoppel, and admission can sometimes enforce oral contracts despite the SoF."},

  {"id":"re-nat-657","domain":"Contracts","type":"single-choice",
   "question":"The key distinction between MISREPRESENTATION and FRAUD in real estate is:",
   "choices":["No difference","Misrepresentation is criminal","Both require intent","INTENT and KNOWLEDGE — MISREPRESENTATION (including innocent and negligent forms) is a false statement of material fact; FRAUD requires the additional element of SCIENTER — the speaker KNEW the statement was false (or made it with reckless disregard for truth) AND intended the other party to rely on it. Fraud carries broader remedies (including punitive damages) and potential criminal liability; innocent misrepresentation typically allows only rescission"],
   "correctAnswer":3,
   "explanation":"MISREPRESENTATION vs. FRAUD — a critical distinction: (1) MISREPRESENTATION — a FALSE STATEMENT OF MATERIAL FACT that induces reliance. Forms: (a) INNOCENT misrepresentation — speaker honestly believed it true; typically allows RESCISSION only; (b) NEGLIGENT misrepresentation — speaker failed to exercise reasonable care in ascertaining truth; allows rescission and sometimes damages; (2) FRAUD — requires ALL elements of misrepresentation PLUS: (a) SCIENTER — the speaker KNEW the statement was false OR made it with RECKLESS DISREGARD for the truth; (b) INTENT TO INDUCE reliance; (c) JUSTIFIABLE RELIANCE by the victim; (d) DAMAGES; (3) REMEDIES COMPARISON: (a) FRAUD — rescission, compensatory damages, PUNITIVE DAMAGES (in egregious cases), and potential CRIMINAL LIABILITY; (b) INNOCENT MISREPRESENTATION — typically rescission only; (4) PRACTICAL IMPACT — the SCIENTER (knowledge/intent) element is the dividing line; proving fraud requires showing the speaker KNEW or recklessly disregarded falsity. In real estate, active concealment of known defects is typically treated as fraud."},

  {"id":"re-nat-658","domain":"Contracts","type":"single-choice",
   "question":"A Letter of Intent (LOI) for a commercial real estate deal states 'this LOI is non-binding except for Sections 7 (Confidentiality), 8 (Exclusivity), and 9 (Expense Allocation), which are binding.' The legal effect:",
   "choices":["Entire LOI is binding","Entire LOI is non-binding","LOI is void","THE SPECIFIED SECTIONS (Confidentiality, Exclusivity, Expense Allocation) ARE LEGALLY BINDING and enforceable; the rest of the LOI is a non-binding expression of intent to negotiate a definitive agreement. This 'partial binding' structure is common and enforceable — courts generally honor clearly-expressed intent about which provisions bind. Ambiguous LOIs (without clear binding/non-binding language) have led to litigation where courts found the entire LOI binding"],
   "correctAnswer":3,
   "explanation":"LOI BINDING PROVISIONS — a 'partial binding' structure: (1) THE SPECIFIED BINDING SECTIONS — Confidentiality, Exclusivity (no-shop), Expense Allocation — ARE LEGALLY ENFORCEABLE; (2) THE REST of the LOI — economic terms, conditions — is a NON-BINDING expression of intent to negotiate a definitive agreement; (3) ENFORCEABILITY — courts generally HONOR clearly-expressed party intent about which provisions are binding; (4) WHY THIS STRUCTURE IS COMMON: (a) parties want to protect CONFIDENTIAL information shared during negotiation; (b) the buyer wants EXCLUSIVITY (the seller agrees not to shop the deal during negotiation — a 'no-shop' clause); (c) parties want to allocate due-diligence EXPENSES; (5) RISK OF AMBIGUITY — LOIs WITHOUT CLEAR binding/non-binding language have led to LITIGATION where courts found the ENTIRE LOI binding (e.g., the Texaco v. Pennzoil case — a famous example of an LOI being found enforceable). BEST PRACTICE: explicitly state which sections bind and which don't, in clear language."},

  {"id":"re-nat-659","domain":"Contracts","type":"single-choice",
   "question":"A seller fails to convey a small portion of the contracted land (a boundary issue reduces the conveyable acreage). The buyer still wants the property. A possible remedy is:",
   "choices":["SPECIFIC PERFORMANCE WITH ABATEMENT — the court orders the seller to convey what they CAN convey, with an ABATEMENT (reduction) in the purchase price proportional to the deficiency; this allows the buyer to obtain the available property while being compensated for the shortfall; available when the deficiency is not so material as to defeat the contract's purpose","No remedy","Full price required","Contract automatically void"],
   "correctAnswer":0,
   "explanation":"SPECIFIC PERFORMANCE WITH ABATEMENT is an important equitable remedy when a seller cannot convey EXACTLY what was contracted: (1) THE COURT ORDERS the seller to convey what they CAN convey (the available property); (2) WITH AN ABATEMENT (reduction) in the purchase price PROPORTIONAL to the deficiency (e.g., if 5% of the acreage cannot be conveyed, the price is reduced proportionally, or by the value of the missing portion); (3) WHEN AVAILABLE: when the deficiency is NOT SO MATERIAL as to defeat the contract's fundamental purpose (a minor boundary discrepancy, a small acreage shortfall, a curable encumbrance); (4) WHEN NOT AVAILABLE: when the deficiency is so substantial that it fundamentally changes the bargain (then the buyer may rescind instead); (5) BUYER'S CHOICE — the buyer typically can elect between: (a) specific performance with abatement (take what's available at a reduced price), or (b) rescission (cancel the contract and recover earnest money), or (c) damages. This remedy balances the buyer's desire for the property against the seller's inability to fully perform."},

  # ── General Principles of Agency (7) ────────────────────────────────────
  {"id":"re-nat-660","domain":"General Principles of Agency","type":"single-choice",
   "question":"A commission dispute arises between two REALTOR® brokers over which is the 'procuring cause' of a sale. Under NAR rules, the dispute is typically resolved through:",
   "choices":["Litigation only","MANDATORY ARBITRATION through the local REALTOR® association's professional standards process — NAR Code of Ethics Article 17 requires REALTORS® to arbitrate (rather than litigate) contractual and specific non-contractual disputes with other REALTORS®; a panel applies procuring-cause analysis considering the entire course of events, not just first or last contact","Coin flip","State commission only"],
   "correctAnswer":1,
   "explanation":"PROCURING CAUSE DISPUTES between REALTOR® brokers: (1) MANDATORY ARBITRATION — NAR Code of Ethics ARTICLE 17 requires REALTORS® to ARBITRATE (rather than litigate) contractual disputes and specific non-contractual disputes with other REALTORS® who are members of the same or different associations; (2) PROCESS — the dispute goes to the local REALTOR® association's PROFESSIONAL STANDARDS process; a hearing panel hears evidence and renders a decision; (3) PROCURING CAUSE ANALYSIS — the panel evaluates which broker's efforts were the ORIGINATING, CONTINUING, AND PROXIMATE CAUSE of the eventual sale; considers the ENTIRE COURSE OF EVENTS (not just who showed the property first or last); factors include: who first introduced the buyer to the property, continuity of effort, abandonment/estrangement, the buyer's perception of who they were working with; (4) BINDING — arbitration awards are generally binding with very limited appeal; (5) NON-REALTORS — disputes involving non-REALTOR brokers may be litigated in court (no mandatory arbitration without contractual agreement). Procuring cause is one of the most litigated/arbitrated issues in real estate commission disputes."},

  {"id":"re-nat-661","domain":"General Principles of Agency","type":"single-choice",
   "question":"A listing agent advises their seller client to accept an offer from a buyer who is, unbeknownst to the seller, the agent's own spouse. This is:",
   "choices":["Acceptable","Required","SELF-DEALING / UNDISCLOSED CONFLICT OF INTEREST — a serious breach of fiduciary duty (loyalty and disclosure); the agent must FULLY DISCLOSE the personal relationship and interest to the seller in writing and obtain informed consent; failure to disclose can result in: license revocation, civil liability for damages, contract rescission, and disgorgement of any commission. Fiduciaries cannot profit from undisclosed conflicts","Standard practice"],
   "correctAnswer":2,
   "explanation":"SELF-DEALING is a serious fiduciary breach. THE SCENARIO: the agent steers their client toward a transaction that benefits the agent personally (here, the agent's spouse buying the property) WITHOUT DISCLOSURE. VIOLATIONS: (1) BREACH OF LOYALTY — the agent must act in the CLIENT'S best interest, not the agent's; (2) BREACH OF DISCLOSURE DUTY — the agent must disclose ALL material facts, especially personal interests; (3) UNDISCLOSED CONFLICT OF INTEREST. PROPER PRACTICE: (a) FULLY DISCLOSE the personal/family relationship and interest to the client IN WRITING; (b) OBTAIN INFORMED WRITTEN CONSENT; (c) consider WITHDRAWING if the conflict can't be cured by disclosure; (d) ensure the client has independent information about the offer's fairness. CONSEQUENCES OF NON-DISCLOSURE: license revocation, civil liability for damages, contract rescission, DISGORGEMENT of commission (forced return of compensation earned through the breach), NAR ethics violations. The fiduciary principle is absolute: agents cannot secretly profit from their position of trust."},

  {"id":"re-nat-662","domain":"General Principles of Agency","type":"single-choice",
   "question":"After an agency relationship ends, the agent's duty of CONFIDENTIALITY regarding the former client's non-public information:",
   "choices":["Ends immediately","Ends after 30 days","Ends at closing","GENERALLY CONTINUES INDEFINITELY — the agent must continue to protect the former client's confidential information (financial condition, motivations, personal circumstances learned during the relationship) even after the relationship ends; the agent cannot use or disclose this information to the former client's detriment in subsequent transactions"],
   "correctAnswer":3,
   "explanation":"POST-TERMINATION CONFIDENTIALITY is a critical (and frequently misunderstood) principle: (1) CONFIDENTIALITY GENERALLY CONTINUES INDEFINITELY after the agency relationship ends; (2) WHAT'S PROTECTED: the former client's NON-PUBLIC INFORMATION learned during the relationship — financial condition, motivations to sell/buy, personal circumstances, bottom-line price, willingness to negotiate, family situation, business plans; (3) WHAT THE AGENT CANNOT DO after the relationship ends: (a) USE the confidential information to the former client's detriment; (b) DISCLOSE it to others (including new clients with adverse interests); (c) PROFIT from the former client's confidential information; (4) WHAT DUTIES END: most other fiduciary duties (loyalty in NEW transactions, obedience, ongoing care) END with the relationship — the agent can represent new clients, even with interests adverse to the former client, AS LONG AS confidential information is protected; (5) PRACTICAL IMPLICATION: an agent who represented a seller cannot later, when representing a buyer interested in that same property (re-listed), use the prior seller's confidential bottom-line price. Confidentiality is the duty that OUTLIVES the relationship."},

  {"id":"re-nat-663","domain":"General Principles of Agency","type":"single-choice",
   "question":"When two brokerages dispute who is owed a cooperating commission, and they are NOT both REALTOR® members (so NAR arbitration doesn't apply), the dispute is typically resolved by:",
   "choices":["LITIGATION in civil court (or arbitration if the parties have a contractual arbitration agreement) — applying procuring-cause principles and the specific terms of any cooperation or compensation agreement between the brokerages; the court examines the entire transaction history to determine which broker's efforts were the proximate cause of the sale","NAR mandatory arbitration regardless","No resolution","State commission decree only"],
   "correctAnswer":0,
   "explanation":"COMMISSION DISPUTES between NON-REALTOR brokerages: (1) NAR ARBITRATION DOESN'T APPLY — NAR Code of Ethics arbitration (Article 17) only binds REALTOR® members; if either brokerage is not a REALTOR® member (or both aren't), NAR's mandatory arbitration doesn't govern; (2) RESOLUTION OPTIONS: (a) LITIGATION in civil court — the most common path for non-REALTOR disputes; (b) ARBITRATION — if the parties have a CONTRACTUAL arbitration agreement (e.g., in an MLS cooperation agreement or a written referral/cooperation contract); (c) MEDIATION — voluntary; (3) APPLICABLE LAW — courts apply: PROCURING-CAUSE principles; the specific terms of any COOPERATION OR COMPENSATION AGREEMENT between the brokerages; relevant MLS rules (if both are MLS participants); state law on broker compensation; (4) ANALYSIS — the court examines the ENTIRE TRANSACTION HISTORY to determine which broker's efforts were the originating, continuing, and proximate cause of the sale; (5) POST-2024 ENVIRONMENT — buyer-broker compensation is now negotiated through buyer-representation agreements, changing how these disputes arise. Documentation of cooperation agreements is critical."},

  {"id":"re-nat-664","domain":"General Principles of Agency","type":"single-choice",
   "question":"A listing agent enters incorrect square footage in the MLS (relying on old county records that turn out to be wrong). A buyer relies on the figure and overpays. The agent's potential liability:",
   "choices":["No liability","SIGNIFICANT — agents have a duty to exercise reasonable care in the information they provide; while agents typically may rely on reputable sources (county records, prior listings), they should verify or DISCLAIM material data (e.g., 'square footage from county records, buyer to verify'); failure to verify or disclaim material errors can result in negligence claims, license discipline, and liability for the buyer's damages","Buyer's fault only","Federal preemption"],
   "correctAnswer":1,
   "explanation":"MLS DATA ACCURACY and agent liability: (1) DUTY OF REASONABLE CARE — agents must exercise reasonable care in the information they provide to the public and to clients; (2) RELIANCE ON SOURCES — agents typically MAY rely on reputable sources (county records, tax assessor data, prior listings, seller representations) BUT must use reasonable judgment; (3) BEST PRACTICE FOR MATERIAL DATA: (a) VERIFY material figures (square footage, lot size, bedrooms) when feasible; (b) DISCLAIM data the agent cannot verify ('Square footage from county records; buyer to verify' or 'Information deemed reliable but not guaranteed'); (c) NOTE the SOURCE of key figures; (4) LIABILITY for material errors: (a) NEGLIGENT MISREPRESENTATION claims if the agent should have caught or disclaimed the error; (b) LICENSE DISCIPLINE for failing to exercise reasonable care; (c) CIVIL DAMAGES — the buyer's losses from overpaying based on inaccurate square footage; (5) MITIGATION — proper disclaimers, source attribution, and recommending independent verification reduce liability. Square footage errors are among the most common sources of post-closing real estate litigation."},

  {"id":"re-nat-665","domain":"General Principles of Agency","type":"single-choice",
   "question":"A BROKER PRICE OPINION (BPO) prepared by a licensee for a lender (e.g., for a short sale or REO valuation):",
   "choices":["Is a formal appraisal","Eliminates appraisals","IS AN ESTIMATE OF VALUE prepared by a real estate licensee — typically used by lenders for loss-mitigation, short sales, REO disposition, and portfolio management; BPOs are NOT formal appraisals (not USPAP-governed in the same way); MANY STATES REGULATE who can prepare BPOs and for what purposes; some prohibit BPOs for loan-origination purposes (where an appraisal is required); compensation and licensing rules vary","Federal mandate"],
   "correctAnswer":2,
   "explanation":"BROKER PRICE OPINIONS (BPOs): (1) DEFINITION — an estimate of a property's probable selling price prepared by a real estate licensee (not a licensed appraiser); (2) COMMON USES: (a) LENDER LOSS-MITIGATION (evaluating short sales, deeds in lieu); (b) REO (bank-owned) property disposition pricing; (c) PORTFOLIO MANAGEMENT and risk assessment; (d) RELOCATION companies; (3) NOT A FORMAL APPRAISAL — BPOs are less rigorous than USPAP appraisals; typically based on a drive-by or interior inspection plus comparable analysis; (4) STATE REGULATION VARIES: (a) MANY STATES REGULATE who can prepare BPOs and for what purposes; (b) SOME STATES PROHIBIT BPOs for LOAN-ORIGINATION purposes (where federal law requires a licensed appraisal); (c) some states require specific BPO licensing or certification; (d) compensation limits and disclosure requirements vary; (5) FEDERAL CONTEXT — Dodd-Frank and federal lending rules require LICENSED APPRAISALS for most mortgage origination — BPOs cannot substitute. The licensee must understand their state's specific BPO rules to avoid unauthorized practice."},

  {"id":"re-nat-666","domain":"General Principles of Agency","type":"single-choice",
   "question":"State trust account rules typically require brokers to RETAIN trust account RECORDS for:",
   "choices":["No retention","One week","One month","A SPECIFIED PERIOD (commonly 3-7 years, varying by state) — including: all deposit and disbursement records, monthly reconciliations, bank statements, copies of checks, ledgers for each transaction, and supporting documentation; records must be available for STATE REAL ESTATE COMMISSION AUDIT; failure to maintain proper records is itself a violation, separate from any actual mishandling of funds"],
   "correctAnswer":3,
   "explanation":"TRUST ACCOUNT RECORD RETENTION: (1) RETENTION PERIOD — varies by state but commonly 3-7 YEARS (some states require longer for certain records); (2) RECORDS THAT MUST BE RETAINED: (a) all DEPOSIT records (who, when, how much, which transaction); (b) all DISBURSEMENT records (to whom, when, authorization); (c) MONTHLY RECONCILIATIONS (matching bank statements to internal ledgers); (d) BANK STATEMENTS; (e) COPIES OF CHECKS and deposit slips; (f) LEDGER for each transaction; (g) SUPPORTING DOCUMENTATION (contracts, instructions, authorizations); (3) AVAILABILITY — records must be available for STATE REAL ESTATE COMMISSION AUDIT (often on demand or short notice); (4) FAILURE TO MAINTAIN RECORDS — is ITSELF A VIOLATION, separate from any actual mishandling; brokers who cannot produce required records during an audit face discipline even if no funds were actually mishandled; (5) FORMAT — most states allow electronic recordkeeping if records are secure, accessible, and complete; (6) THE QUALIFYING/DESIGNATED BROKER is typically personally responsible for compliance. Proper trust accounting is one of the most heavily scrutinized aspects of real estate practice."},

  # ── Practice of Real Estate (7) ─────────────────────────────────────────
  {"id":"re-nat-667","domain":"Practice of Real Estate","type":"single-choice",
   "question":"Under ADA TITLE III, a commercial property owner leasing space to retail businesses:",
   "choices":["HAS OBLIGATIONS to ensure 'places of public accommodation' are ACCESSIBLE — including readily-achievable barrier removal in existing facilities, accessible new construction and alterations meeting ADA Standards, and reasonable modifications to policies; LEASE AGREEMENTS often allocate ADA compliance responsibility between landlord and tenant, but BOTH can be liable to the public regardless of how they allocate it between themselves","Has no obligations","Only tenants are liable","Federal preemption eliminates liability"],
   "correctAnswer":0,
   "explanation":"ADA TITLE III (public accommodations and commercial facilities): (1) WHO'S COVERED — owners, operators, lessors, and lessees of 'places of public accommodation' (retail stores, restaurants, hotels, offices serving the public, etc.) and commercial facilities; (2) OBLIGATIONS: (a) BARRIER REMOVAL — remove architectural barriers in EXISTING facilities where 'readily achievable' (easily accomplishable without much difficulty/expense); (b) NEW CONSTRUCTION AND ALTERATIONS — must meet ADA Standards for Accessible Design; (c) REASONABLE MODIFICATIONS to policies, practices, procedures; (d) AUXILIARY AIDS and SERVICES (for effective communication); (3) LANDLORD-TENANT ALLOCATION — lease agreements often ALLOCATE ADA compliance responsibility between landlord and tenant — BUT both can be LIABLE TO THE PUBLIC regardless of how they allocate it between themselves (the allocation is enforceable between landlord and tenant via indemnity, but doesn't limit third-party/government claims); (4) ENFORCEMENT — DOJ enforcement, private lawsuits (injunctive relief, attorneys' fees; no damages in federal ADA Title III, but state laws may add damages); (5) REAL ESTATE PRACTICE — agents involved in commercial leasing/sales should advise clients to consult ADA-knowledgeable counsel; ADA compliance is a significant commercial real estate consideration."},

  {"id":"re-nat-668","domain":"Practice of Real Estate","type":"single-choice",
   "question":"In real estate advertising, which phrasing would MOST LIKELY violate the Fair Housing Act?",
   "choices":["'Spacious 3-bedroom home'","'Perfect for a CHRISTIAN FAMILY in a QUIET ADULT community, no children' — language indicating preferences based on RELIGION and FAMILIAL STATUS violates the FHA; advertising cannot express preferences, limitations, or discrimination based on protected classes (race, color, religion, sex, national origin, familial status, disability)","'Recently renovated kitchen'","'Close to public transportation'"],
   "correctAnswer":1,
   "explanation":"FAIR HOUSING ADVERTISING — the FHA prohibits advertising that 'indicates any preference, limitation, or discrimination' based on protected classes (race, color, religion, sex, national origin, familial status, disability), OR an INTENTION to make such a preference. PROBLEMATIC LANGUAGE: (1) RELIGION — 'Christian family,' 'churchgoing community,' references to specific faiths; (2) FAMILIAL STATUS — 'no children,' 'adults only,' 'mature persons,' 'empty-nesters' (except in HOPA-qualified senior housing); (3) RACE/ETHNICITY/NATIONAL ORIGIN — references to ethnic composition, 'exclusive neighborhood' (sometimes a code), language preferences; (4) DISABILITY — 'no wheelchairs,' 'must be able to climb stairs'; (5) SEX — 'perfect for a single man'; (6) CODE WORDS — phrases courts/HUD have found problematic in context. ACCEPTABLE: descriptions of the PROPERTY itself (size, features, condition, location, amenities) — NOT the desired occupants. Selective use of human models can also violate the FHA. The 'ordinary reader' test: would a reasonable person interpret the ad as indicating a discriminatory preference?"},

  {"id":"re-nat-669","domain":"Practice of Real Estate","type":"single-choice",
   "question":"PREDATORY LENDING practices commonly include:",
   "choices":["Disclosed APRs","Standard loans","EXCESSIVE FEES AND POINTS, LOAN FLIPPING (repeated unnecessary refinancing to generate fees), EQUITY STRIPPING, STEERING borrowers to higher-cost loans than they qualify for, BALLOON PAYMENTS designed to force refinancing, LOAN TERMS NOT IN THE BORROWER'S INTEREST, FAILURE TO CONSIDER ABILITY TO REPAY, and DECEPTIVE MARKETING — targeting vulnerable borrowers (elderly, low-income, minority communities); regulated by HOEPA, Dodd-Frank, state laws","Required disclosures"],
   "correctAnswer":2,
   "explanation":"PREDATORY LENDING — abusive lending practices that harm borrowers: (1) EXCESSIVE FEES AND POINTS — fees far above market norms; (2) LOAN FLIPPING — repeatedly refinancing a borrower's loan unnecessarily to generate fees, stripping equity each time; (3) EQUITY STRIPPING — making loans based on home equity rather than the borrower's ability to repay, leading to foreclosure and equity loss; (4) STEERING — directing borrowers to higher-cost loans than they qualify for (often correlated with race — a fair-lending violation); (5) ABUSIVE LOAN TERMS — balloon payments designed to force refinancing, negative amortization, prepayment penalties trapping borrowers; (6) FAILURE TO CONSIDER ABILITY TO REPAY — making loans the borrower can't sustain; (7) DECEPTIVE MARKETING and high-pressure sales; (8) TARGETING — vulnerable borrowers (elderly, low-income, minority communities, financially unsophisticated); (9) REGULATION — HOEPA (high-cost loan protections), Dodd-Frank ability-to-repay rules, state predatory lending laws, fair-lending enforcement. Predatory lending was a major contributor to the 2008 financial crisis, prompting substantial reform."},

  {"id":"re-nat-670","domain":"Practice of Real Estate","type":"single-choice",
   "question":"APPRAISAL INDEPENDENCE requirements (strengthened by Dodd-Frank and HVCC predecessor rules):",
   "choices":["Allow lenders to pressure appraisers","No requirements","Eliminate appraisals","PROHIBIT lenders, mortgage brokers, real estate agents, and other interested parties from IMPROPERLY INFLUENCING or COERCING appraisers — including pressuring for a target value, withholding payment based on value, or selecting appraisers based on a history of high valuations; appraisers must be selected and compensated independently; violations carry significant penalties; AMCs were widely adopted partly to create separation"],
   "correctAnswer":3,
   "explanation":"APPRAISAL INDEPENDENCE requirements (Dodd-Frank Section 1472, prior Home Valuation Code of Conduct/HVCC, and TILA appraisal independence rules): (1) PROHIBITED CONDUCT — lenders, mortgage brokers, real estate agents, and other interested parties CANNOT: (a) PRESSURE OR COERCE an appraiser to reach a specific value; (b) WITHHOLD or threaten to withhold payment based on the appraised value; (c) SELECT appraisers based on a history of providing high valuations; (d) provide the appraiser with a TARGET VALUE; (e) condition future business on reaching certain values; (2) REQUIREMENTS: (a) appraisers must be selected and engaged INDEPENDENTLY of the loan production function; (b) appraisers must be COMPENSATED FAIRLY (customary and reasonable fees); (c) APPRAISER must exercise INDEPENDENT JUDGMENT; (3) APPRAISAL MANAGEMENT COMPANIES (AMCs) — were widely adopted partly to create SEPARATION between lenders and appraisers; AMCs assign appraisers, handle communications, and provide a buffer; (4) PENALTIES — significant civil penalties for violations; (5) PURPOSE — to prevent the appraisal inflation that contributed to the 2008 financial crisis. Real estate agents must NOT pressure appraisers, though they CAN provide relevant comparable sales data."},

  {"id":"re-nat-671","domain":"Practice of Real Estate","type":"single-choice",
   "question":"APPRAISAL MANAGEMENT COMPANIES (AMCs):",
   "choices":["ARE THIRD-PARTY INTERMEDIARIES that manage the appraisal process for lenders — selecting and assigning appraisers from a panel, handling communications, performing quality control, and providing a buffer between the lender's loan-production staff and the appraiser to maintain appraisal independence; AMCs are regulated in most states (registration, surety bonds, compliance requirements) and subject to federal oversight","Are unregulated","Are appraisers themselves","Are federal agencies"],
   "correctAnswer":0,
   "explanation":"APPRAISAL MANAGEMENT COMPANIES (AMCs): (1) ROLE — THIRD-PARTY INTERMEDIARIES that manage the appraisal process for lenders: (a) SELECT and ASSIGN appraisers from a panel of independent appraisers; (b) HANDLE COMMUNICATIONS between the lender and appraiser (maintaining independence); (c) PERFORM QUALITY CONTROL on completed appraisals; (d) MANAGE the appraisal workflow and turnaround; (2) PURPOSE — provide a BUFFER between the lender's loan-production staff and the appraiser, supporting APPRAISAL INDEPENDENCE requirements; (3) GROWTH — AMCs proliferated after the 2008 crisis and HVCC/Dodd-Frank reforms requiring lender-appraiser separation; (4) REGULATION — AMCs are regulated in MOST STATES: (a) state REGISTRATION/LICENSING; (b) SURETY BONDS; (c) COMPLIANCE requirements (appraiser fee disclosure, panel management standards, turnaround standards); (d) FEDERAL oversight via the Appraisal Subcommittee and ASC AMC National Registry; (5) CRITICISMS — concerns about: appraiser fee compression (AMCs take a cut), turnaround pressure, geographic competency issues. Real estate agents typically work with appraisers ASSIGNED through AMCs and should provide relevant comparable data without applying pressure."},

  {"id":"re-nat-672","domain":"Practice of Real Estate","type":"single-choice",
   "question":"The SAFE Act (Secure and Fair Enforcement for Mortgage Licensing Act of 2008) requires:",
   "choices":["No licensing","Only banks to register","MORTGAGE LOAN ORIGINATORS (MLOs) to be LICENSED (if working for a non-depository) or REGISTERED (if working for a depository institution) through the NATIONWIDE MULTISTATE LICENSING SYSTEM (NMLS) — including pre-licensing education, passing a national exam, background checks, continuing education, and unique NMLS identifier; designed to set minimum standards and provide accountability for mortgage originators after the 2008 crisis","Federal preemption of all state rules"],
   "correctAnswer":2,
   "explanation":"THE SAFE ACT (Secure and Fair Enforcement for Mortgage Licensing Act of 2008): (1) PURPOSE — set minimum standards and accountability for MORTGAGE LOAN ORIGINATORS (MLOs) after the 2008 financial crisis; (2) WHO IT COVERS — individuals who take residential mortgage loan applications and offer/negotiate loan terms for compensation; (3) REQUIREMENTS: (a) LICENSING — MLOs at NON-DEPOSITORY institutions (mortgage companies, brokers) must be STATE-LICENSED; (b) REGISTRATION — MLOs at DEPOSITORY institutions (banks, credit unions) must be FEDERALLY REGISTERED; (c) NMLS — all register through the NATIONWIDE MULTISTATE LICENSING SYSTEM (NMLS) and get a UNIQUE NMLS IDENTIFIER (must appear on loan documents and advertising); (d) PRE-LICENSING EDUCATION — typically 20+ hours; (e) NATIONAL EXAM — SAFE MLO test; (f) BACKGROUND CHECKS — criminal and credit; (g) CONTINUING EDUCATION — annual requirements; (4) ENFORCEMENT — state regulators and the CFPB; (5) REAL ESTATE OVERLAP — real estate licensees who also originate mortgages must comply with BOTH real estate licensing AND SAFE Act/NMLS requirements; some states have specific rules about dual roles."},

  {"id":"re-nat-673","domain":"Practice of Real Estate","type":"single-choice",
   "question":"The NMLS (Nationwide Multistate Licensing System):",
   "choices":["Is a private MLS","Replaces all state licensing","IS THE SYSTEM OF RECORD for mortgage loan originator (and certain other financial services) licensing across all states — providing a unified registration, license management, criminal/credit background checks, education tracking, and a PUBLIC CONSUMER ACCESS portal where consumers can verify an MLO's licensing status and disciplinary history; managed by state regulators through the Conference of State Bank Supervisors","Is a federal agency"],
   "correctAnswer":2,
   "explanation":"NMLS (Nationwide Multistate Licensing System & Registry): (1) WHAT IT IS — the SYSTEM OF RECORD for mortgage loan originator licensing (and increasingly other financial services licensing — money transmitters, consumer finance, debt collection) across ALL STATES; (2) FUNCTIONS: (a) UNIFIED REGISTRATION — one system for MLOs to apply for and maintain licenses in multiple states; (b) LICENSE MANAGEMENT — renewals, amendments, transfers; (c) BACKGROUND CHECKS — criminal history and credit reports; (d) EDUCATION TRACKING — pre-licensing and continuing education completion; (e) UNIQUE IDENTIFIER — each MLO gets a permanent NMLS ID number (must appear on loan documents and advertising); (f) PUBLIC CONSUMER ACCESS — the NMLS Consumer Access portal lets consumers VERIFY an MLO's licensing status, employment history, and disciplinary actions; (3) GOVERNANCE — managed by state regulators through the Conference of State Bank Supervisors (CSBS) and the American Association of Residential Mortgage Regulators; (4) NOT a federal agency — it's a state-regulator-owned system; (5) REAL ESTATE RELEVANCE — agents who refer clients to mortgage professionals can use NMLS Consumer Access to verify the MLO's standing; agents who also originate loans must maintain NMLS registration."},

  # ── Financing (5) ───────────────────────────────────────────────────────
  {"id":"re-nat-674","domain":"Financing","type":"single-choice",
   "question":"A 'YIELD SPREAD PREMIUM' (YSP) in mortgage lending refers to:",
   "choices":["A discount","A federal subsidy","A type of insurance","COMPENSATION paid by a lender to a mortgage broker for delivering a loan with a HIGHER INTEREST RATE than the borrower might otherwise qualify for; YSPs created incentives for brokers to steer borrowers into higher-cost loans; post-Dodd-Frank rules SUBSTANTIALLY RESTRICTED loan originator compensation that varies with loan terms (other than loan amount) — largely eliminating traditional YSP abuse"],
   "correctAnswer":3,
   "explanation":"YIELD SPREAD PREMIUM (YSP): (1) DEFINITION — compensation paid by a LENDER to a MORTGAGE BROKER for delivering a loan with a HIGHER INTEREST RATE than the par rate the borrower might qualify for; (2) HOW IT WORKED — a broker who got a borrower to accept a rate above par would receive a 'back-end' payment from the lender (the present value of the extra interest stream); (3) THE PROBLEM — YSPs created PERVERSE INCENTIVES: brokers were financially rewarded for steering borrowers into HIGHER-COST loans; borrowers often didn't understand they were paying more; YSP abuse contributed to the subprime crisis; (4) POST-2008 REFORM — DODD-FRANK and Federal Reserve loan-originator compensation rules (Reg Z) SUBSTANTIALLY RESTRICTED loan originator compensation: (a) LO compensation generally CANNOT VARY based on loan TERMS (interest rate, etc.) — only based on loan AMOUNT (with caps) or fixed amounts; (b) LOs cannot be paid by BOTH the consumer AND the lender on the same transaction; (c) anti-steering provisions require presenting loan options; (5) RESULT — traditional YSP abuse has been largely ELIMINATED, though broker compensation models continue to evolve. The history illustrates how compensation structures drive behavior."},

  {"id":"re-nat-675","domain":"Financing","type":"single-choice",
   "question":"MORTGAGE SERVICING RIGHTS (MSRs):",
   "choices":["ARE A TRADABLE ASSET representing the right (and obligation) to SERVICE a mortgage — collecting payments, managing escrow, handling delinquencies — in exchange for a servicing fee (typically a small percentage of the loan balance annually). MSRs are bought and sold separately from the underlying loans; their value fluctuates with interest rates (prepayment risk) and is a significant balance-sheet asset for servicers; servicing transfers must comply with RESPA notice rules","Are loans","Are appraisals","Are federal grants"],
   "correctAnswer":0,
   "explanation":"MORTGAGE SERVICING RIGHTS (MSRs): (1) WHAT THEY ARE — a TRADABLE ASSET representing the RIGHT (and obligation) to SERVICE a mortgage: (a) collecting monthly payments; (b) managing escrow for taxes and insurance; (c) handling delinquencies, loss mitigation, and foreclosure; (d) providing customer service and statements; (e) remitting funds to investors; (2) COMPENSATION — the servicer earns a SERVICING FEE (typically 0.25%-0.50% of the outstanding loan balance annually) plus ancillary income (late fees, etc.); (3) SEPARATE FROM THE LOAN — MSRs are bought and sold SEPARATELY from the underlying loans; a loan can be owned by Fannie Mae while serviced by a third party that purchased the MSR; (4) VALUE DYNAMICS — MSR value FLUCTUATES with interest rates: (a) when rates FALL, prepayment/refinancing increases — REDUCING MSR value (the servicing income stream ends early); (b) when rates RISE, prepayments slow — INCREASING MSR value; (5) BALANCE-SHEET ASSET — MSRs are a significant (and volatile) asset for mortgage servicers; (6) BORROWER IMPACT — servicing transfers (MSR sales) must comply with RESPA notice requirements; borrowers may have their loan serviced by multiple companies over its life."},

  {"id":"re-nat-676","domain":"Financing","type":"single-choice",
   "question":"After an annual ESCROW ANALYSIS, a borrower's escrow account is found to have a SHORTAGE (insufficient to cover projected tax and insurance increases). The servicer typically:",
   "choices":["Cancels the loan","NOTIFIES the borrower and offers options: (a) the borrower pays the shortage in a LUMP SUM, OR (b) the shortage is SPREAD over the next 12 months (increasing the monthly payment); the monthly escrow portion is ALSO ADJUSTED upward to cover the higher projected costs going forward; RESPA regulates escrow analysis, allowable cushion (typically max 2 months), and shortage/surplus handling","Keeps the shortage","Reduces the loan balance"],
   "correctAnswer":1,
   "explanation":"ESCROW ANALYSIS AND SHORTAGE: (1) ANNUAL ANALYSIS — servicers must perform an ANNUAL ESCROW ACCOUNT ANALYSIS (RESPA requirement) — comparing the actual escrow balance and disbursements against projected needs for the coming year; (2) SHORTAGE OCCURS when projected tax/insurance costs increase (rising property taxes, higher insurance premiums) and the current escrow payment is insufficient; (3) SERVICER OPTIONS for the borrower: (a) PAY THE SHORTAGE IN A LUMP SUM; OR (b) SPREAD THE SHORTAGE over the next 12 months (increasing the monthly payment temporarily); (4) GOING-FORWARD ADJUSTMENT — the monthly escrow portion is ALSO ADJUSTED UPWARD to cover the higher projected tax/insurance costs going forward (this is permanent unless costs decrease); (5) RESPA REGULATION — RESPA Section 10 limits: (a) the ESCROW CUSHION the servicer can require (generally MAX 2 MONTHS of escrow payments); (b) requires the annual analysis and statement; (c) governs shortage and SURPLUS handling (surpluses over $50 must typically be refunded); (6) SURPLUS — if the analysis shows excess (e.g., taxes decreased), the borrower gets a refund or credit. Escrow shortages commonly surprise borrowers — particularly after property tax reassessments following a purchase."},

  {"id":"re-nat-677","domain":"Financing","type":"single-choice",
   "question":"Lenders typically require borrowers to maintain HAZARD (homeowners) INSURANCE because:",
   "choices":["No requirement","It's optional","THE PROPERTY IS THE LENDER'S COLLATERAL — insurance protects the lender's security interest against loss from fire, storms, and other covered perils; the lender is typically named as 'MORTGAGEE' or 'LOSS PAYEE' on the policy; the required coverage amount is typically at least the loan balance OR replacement cost; if the borrower fails to maintain insurance, the lender may purchase FORCE-PLACED insurance (typically expensive) and charge the borrower","Federal mandate only"],
   "correctAnswer":2,
   "explanation":"HAZARD INSURANCE REQUIREMENTS: (1) WHY LENDERS REQUIRE IT — the PROPERTY IS THE LENDER'S COLLATERAL; if the property is destroyed or damaged (fire, storm, etc.) and uninsured, the lender's security is impaired and the borrower may walk away from a worthless property still owing the loan; (2) LENDER PROTECTION — the lender is named as 'MORTGAGEE' or 'LOSS PAYEE' on the policy, ensuring insurance proceeds go (at least partly) to protecting the loan; (3) COVERAGE AMOUNT — typically at least the LOAN BALANCE or, more commonly, the REPLACEMENT COST of the structure (lenders increasingly require replacement-cost coverage); (4) ESCROW — insurance premiums are often escrowed (part of PITI) so the lender can ensure premiums are paid; (5) FORCE-PLACED (LENDER-PLACED) INSURANCE — if the borrower fails to maintain required insurance, the lender may PURCHASE insurance on the borrower's behalf and charge the borrower; force-placed insurance is typically: (a) MUCH MORE EXPENSIVE than the borrower could obtain; (b) protects only the LENDER'S interest (not the borrower's contents or liability); (c) regulated by RESPA and CFPB rules requiring notice before force-placing; (6) FLOOD INSURANCE — separately required for properties in Special Flood Hazard Areas."},

  {"id":"re-nat-678","domain":"Financing","type":"single-choice",
   "question":"FORCE-PLACED (or 'lender-placed') hazard insurance:",
   "choices":["Is cheap","Protects the borrower fully","Is illegal","IS INSURANCE THE LENDER PURCHASES when the borrower fails to maintain required coverage; it is TYPICALLY EXPENSIVE (often 2-10x the cost of a standard policy), PROTECTS ONLY THE LENDER'S INTEREST (not the borrower's personal property or liability), and the COST IS CHARGED TO THE BORROWER; RESPA/CFPB rules require the servicer to provide ADVANCE NOTICE (typically two notices) before force-placing and to refund/cancel if the borrower provides proof of their own coverage"],
   "correctAnswer":3,
   "explanation":"FORCE-PLACED (LENDER-PLACED) INSURANCE: (1) WHAT IT IS — insurance the lender/servicer PURCHASES on the property when the borrower fails to maintain the required hazard insurance (lapsed policy, non-payment, etc.); (2) COST — TYPICALLY EXPENSIVE: often 2-10X the cost of a standard homeowner's policy because: (a) no underwriting (risk is unknown); (b) the lender's insurer takes on adverse-selection risk; (c) historically, kickback arrangements inflated costs (now regulated); (3) LIMITED COVERAGE — protects ONLY THE LENDER'S INTEREST (the structure up to the loan balance); does NOT cover the borrower's PERSONAL PROPERTY, LIABILITY, or additional living expenses; (4) COST CHARGED TO BORROWER — added to the loan balance or escrow; (5) CONSUMER PROTECTIONS (RESPA/CFPB rules): (a) servicer must send TWO ADVANCE NOTICES before force-placing (at least 45 and 15 days before); (b) must accept evidence of the borrower's own coverage; (c) must CANCEL force-placed insurance and REFUND premiums within 15 days if the borrower provides proof of acceptable coverage; (d) force-placed premiums must be 'bona fide and reasonable'; (6) BEST PRACTICE — borrowers should maintain continuous coverage and promptly respond to insurance notices to avoid the high cost of force-placed insurance."},

  # ── Real Estate Calculations (5) ────────────────────────────────────────
  {"id":"re-nat-679","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A homeowner's property is worth $450,000. They owe $280,000 on the first mortgage and $40,000 on a home equity line. What is their EQUITY?",
   "choices":["$130,000 — Equity = Market Value − Total Liens = $450,000 − ($280,000 + $40,000) = $450,000 − $320,000 = $130,000","$170,000","$450,000","$320,000"],
   "correctAnswer":0,
   "explanation":"Step 1 — Equity = Market Value − Total Outstanding Liens/Debt secured by the property.\nStep 2 — Total liens: $280,000 (first mortgage) + $40,000 (HELOC) = $320,000.\nStep 3 — Equity: $450,000 − $320,000 = $130,000.\nEQUITY is the owner's actual ownership value — what they would net (before transaction costs) if they sold at market value and paid off all property-secured debt. Equity grows through: (1) PRINCIPAL PAYDOWN (loan amortization); (2) APPRECIATION (rising market value); (3) IMPROVEMENTS (value-adding renovations). Equity is the basis for: cash-out refinance limits, HELOC availability, net proceeds at sale, and the homeowner's wealth position. (Note: actual net sale proceeds would also subtract closing costs, commissions, and transfer taxes.)"},

  {"id":"re-nat-680","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A property purchased for $300,000 five years ago is now worth $390,000. What is the TOTAL appreciation percentage and approximate ANNUAL appreciation rate (simple)?",
   "choices":["10% total, 2% annual","30% total, 6% annual (simple) — Total appreciation = ($390,000 − $300,000) / $300,000 = $90,000 / $300,000 = 30%. Simple annual = 30% / 5 years = 6% per year (compound annual growth rate would be slightly lower, ~5.4%)","90% total, 18% annual","3% total, 0.6% annual"],
   "correctAnswer":1,
   "explanation":"Step 1 — Total appreciation in dollars: $390,000 − $300,000 = $90,000.\nStep 2 — Total appreciation percentage: $90,000 ÷ $300,000 = 0.30 = 30%.\nStep 3 — Simple annual appreciation rate: 30% ÷ 5 years = 6% per year.\nNOTE on COMPOUND vs. SIMPLE: the SIMPLE method (total % ÷ years) gives 6%. The COMPOUND ANNUAL GROWTH RATE (CAGR) would be slightly lower: CAGR = ($390,000/$300,000)^(1/5) − 1 ≈ 1.30^0.2 − 1 ≈ 5.39%. The difference matters in financial analysis — CAGR is more accurate for multi-year growth because it accounts for compounding. Exam questions usually accept the simple method unless they specify CAGR. Appreciation is a key wealth-building component of real estate ownership."},

  {"id":"re-nat-681","domain":"Real Estate Calculations","type":"single-choice",
   "question":"An apartment building has fixed annual operating expenses and debt service totaling $180,000. Each unit rents for $1,500/month and there are 15 units. What is the BREAK-EVEN OCCUPANCY (the occupancy rate at which income exactly covers expenses + debt)?",
   "choices":["50%","75%","66.7% — Required annual income = $180,000. Potential annual income at 100% = 15 units × $1,500 × 12 = $270,000. Break-even occupancy = $180,000 / $270,000 = 0.667 = 66.7%","100%"],
   "correctAnswer":2,
   "explanation":"Step 1 — Required annual income to break even = total operating expenses + debt service = $180,000.\nStep 2 — Potential gross annual income at 100% occupancy: 15 units × $1,500/month × 12 months = $270,000.\nStep 3 — Break-even occupancy rate = Required Income ÷ Potential Income = $180,000 ÷ $270,000 = 0.667 = 66.7%.\nINTERPRETATION: the building must maintain at least 66.7% occupancy (about 10 of 15 units occupied) to cover all expenses and debt. Below that, the owner must fund the shortfall out of pocket. BREAK-EVEN OCCUPANCY is a critical risk metric for income property: (1) LOWER break-even = more cushion = lower risk; (2) HIGHER break-even = thinner margin = higher risk; (3) lenders examine break-even occupancy in underwriting; (4) compare to MARKET VACANCY RATES — if market vacancy is 8% (92% occupancy) and break-even is 66.7%, there's reasonable cushion."},

  {"id":"re-nat-682","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A loan has annual debt service (12 monthly P&I payments) of $24,000 on an original loan amount of $300,000. What is the MORTGAGE CONSTANT (annual debt service as a percentage of the loan amount)?",
   "choices":["12%","6%","4%","8% — Mortgage Constant = Annual Debt Service ÷ Loan Amount = $24,000 ÷ $300,000 = 0.08 = 8%"],
   "correctAnswer":3,
   "explanation":"Step 1 — Mortgage Constant (also called 'loan constant' or 'mortgage capitalization rate') = Annual Debt Service ÷ Original Loan Amount.\nStep 2 — Apply: $24,000 ÷ $300,000 = 0.08 = 8%.\nUSES OF THE MORTGAGE CONSTANT: (1) BAND-OF-INVESTMENT cap rate derivation — the mortgage constant is the debt component (weighted by LTV) in deriving an overall cap rate; (2) QUICK COMPARISON — comparing financing costs across loans; (3) POSITIVE/NEGATIVE LEVERAGE ANALYSIS — if the property's CAP RATE EXCEEDS the mortgage constant, the investor has POSITIVE LEVERAGE (debt enhances returns); if the cap rate is BELOW the mortgage constant, NEGATIVE LEVERAGE (debt drags returns); (4) The mortgage constant is ALWAYS HIGHER than the interest rate for an amortizing loan (because it includes principal repayment) and EQUALS the interest rate for an interest-only loan. The mortgage constant is a fundamental concept in income property finance analysis."},

  {"id":"re-nat-683","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A 20-unit apartment building: each unit rents for $1,200/month. Vacancy/collection loss is 6%. Other income (laundry, parking) is $12,000/year. What is the EFFECTIVE GROSS INCOME (EGI)?",
   "choices":["$288,000","$282,720 — Potential gross rent = 20 × $1,200 × 12 = $288,000. Less 6% vacancy/collection = $288,000 × 0.06 = $17,280 loss. = $270,720. Plus other income $12,000 = $282,720.","$270,720","$300,000"],
   "correctAnswer":1,
   "explanation":"Step 1 — Potential Gross Rental Income (PGI): 20 units × $1,200/month × 12 months = $288,000.\nStep 2 — Vacancy and collection loss: $288,000 × 6% = $17,280.\nStep 3 — Effective rental income: $288,000 − $17,280 = $270,720.\nStep 4 — Add other income (laundry, parking, fees): $270,720 + $12,000 = $282,720 EGI.\nTHE INCOME APPROACH PROGRESSION: (1) POTENTIAL GROSS INCOME (PGI) — all rent at 100% occupancy; (2) less VACANCY AND COLLECTION LOSS; (3) plus OTHER INCOME — laundry, parking, vending, fees, etc.; (4) = EFFECTIVE GROSS INCOME (EGI); (5) less OPERATING EXPENSES; (6) = NET OPERATING INCOME (NOI); (7) NOI ÷ CAP RATE = VALUE. Note that OTHER INCOME is typically added AFTER the vacancy adjustment (other income is often less affected by unit vacancy). Mastering the EGI/NOI build-up is essential for income property analysis and the income approach to value."},

  # ── Property Ownership (4) ──────────────────────────────────────────────
  {"id":"re-nat-684","domain":"Property Ownership","type":"single-choice",
   "question":"A tenant farmer plants and cultivates a crop. Before harvest, the farm is sold. The tenant's right to RE-ENTER and HARVEST the crop they planted is protected by the doctrine of:",
   "choices":["Trade fixtures","Severance","EMBLEMENTS (or 'fructus industriales') — the doctrine that a tenant who plants annual crops has the right to RE-ENTER after the tenancy ends to HARVEST the crops they cultivated (the fruits of their labor); applies to annual crops requiring cultivation, not to perennial/natural growth; protects the tenant's investment of labor and resources","Eminent domain"],
   "correctAnswer":2,
   "explanation":"EMBLEMENTS (also called 'fructus industriales' — 'fruits of industry'): (1) THE DOCTRINE — a tenant who PLANTS AND CULTIVATES ANNUAL CROPS has the right to RE-ENTER the property AFTER the tenancy ends to HARVEST the crops they planted; (2) RATIONALE — protects the tenant's INVESTMENT OF LABOR, SEED, AND RESOURCES in cultivating the crop; it would be inequitable for the landowner to reap what the tenant sowed; (3) WHAT QUALIFIES — ANNUAL CROPS requiring cultivation (corn, wheat, vegetables — 'fructus industriales'); does NOT apply to PERENNIAL/NATURAL growth (trees, perennial grasses, wild plants — 'fructus naturales' which pass with the land); (4) WHEN IT APPLIES — typically when the tenancy ends through NO FAULT of the tenant (e.g., a life tenant dies, a tenancy at will is terminated, the property is sold) before harvest; (5) CONTRAST WITH FIXTURES — emblements are PERSONAL PROPERTY belonging to the cultivating tenant; (6) MODERN STATUTES — many states have codified emblements rules; agricultural leases often specifically address crop rights. The doctrine is most relevant in agricultural real estate."},

  {"id":"re-nat-685","domain":"Property Ownership","type":"single-choice",
   "question":"Courts determine whether an item is a FIXTURE (real property) or PERSONAL PROPERTY using factors that include:",
   "choices":["Only the item's cost","Only who installed it","Random factors","METHOD OF ATTACHMENT (how permanently affixed), ADAPTATION (whether the item is specifically adapted to the property's use), RELATIONSHIP OF THE PARTIES (landlord-tenant favors removal; buyer-seller favors inclusion), INTENTION (objectively manifested intent at the time of installation), and any AGREEMENT between the parties — no single factor controls; INTENTION (as objectively manifested) is often considered the most important"],
   "correctAnswer":3,
   "explanation":"FIXTURE DETERMINATION TESTS (sometimes remembered by acronyms like MARIA or the 'IRMA' tests): (1) METHOD OF ATTACHMENT — how permanently is the item affixed? (bolted, plumbed, hardwired = more likely fixture; freestanding = more likely personal property); (2) ADAPTATION — is the item specifically ADAPTED or CUSTOM-FITTED to the property? (custom-cut blinds, built-in appliances = more likely fixture); (3) RELATIONSHIP OF THE PARTIES — context matters: (a) LANDLORD-TENANT relationship → favors the TENANT's right to remove (especially trade fixtures); (b) BUYER-SELLER → favors inclusion with the real estate; (c) LENDER-BORROWER → favors fixture (part of collateral); (4) INTENTION — the OBJECTIVELY MANIFESTED intent at the time of installation (often considered the MOST IMPORTANT factor — what would a reasonable person conclude the installer intended?); (5) AGREEMENT — any contract provision specifically addressing the item CONTROLS (the parties can agree an item is or isn't a fixture). NO SINGLE FACTOR is dispositive — courts weigh all factors. Disputes commonly arise over: chandeliers, appliances, window treatments, mounted TVs, custom shelving, sheds."},

  {"id":"re-nat-686","domain":"Property Ownership","type":"single-choice",
   "question":"A seller wants to take mature fruit trees and a built-in greenhouse with them when they sell. To convert these from real property to personal property:",
   "choices":["The seller can SEVER them — physically removing or contractually reserving them BEFORE the sale (or excluding them in the purchase contract); growing trees and built-in structures are normally REAL PROPERTY (fructus naturales / fixtures) that pass with the land unless the seller takes affirmative steps to SEVER or RESERVE them in writing; failure to clearly exclude them in the contract means they convey with the property","Cannot be done","Federal court order","Automatic exclusion"],
   "correctAnswer":0,
   "explanation":"SEVERANCE — converting real property to personal property: (1) THE PROBLEM — growing trees ('fructus naturales' — natural growth), built-in structures, and other fixtures are normally REAL PROPERTY that AUTOMATICALLY PASSES WITH THE LAND on sale; (2) TO TAKE THEM, the seller must SEVER them: (a) PHYSICALLY REMOVE them BEFORE closing (e.g., dig up the trees, dismantle the greenhouse) — physical severance converts them to personal property; OR (b) CONTRACTUALLY RESERVE/EXCLUDE them in the PURCHASE CONTRACT in clear written language (e.g., 'Sale excludes the three mature apple trees in the rear yard and the detached greenhouse, which Seller will remove prior to closing'); (3) THE DEFAULT RULE — WITHOUT clear severance or exclusion, these items CONVEY WITH THE PROPERTY (the buyer gets them); (4) DISPUTES — failure to clearly address items the seller wants to keep is a COMMON SOURCE OF CLOSING DISPUTES; (5) BEST PRACTICE — sellers should: (a) identify items they want to keep EARLY (before listing); (b) either sever them before showing the property or clearly EXCLUDE them in the listing and contract; (c) NOT rely on verbal understandings. The doctrine of severance is the legal opposite of annexation (personal → real)."},

  {"id":"re-nat-687","domain":"Property Ownership","type":"single-choice",
   "question":"A custom-built bookcase is screwed into wall studs and specifically sized to fit a particular alcove. Under the fixture tests, this item is most likely:",
   "choices":["Personal property the seller can always remove","A FIXTURE (real property) — it is PERMANENTLY ATTACHED (screwed into studs), specifically ADAPTED to the property (custom-sized for the alcove), and a reasonable person would conclude it was INTENDED to be a permanent part of the home; it would typically CONVEY with the property unless specifically excluded in the contract","A trade fixture","Always excluded from sale"],
   "correctAnswer":1,
   "explanation":"APPLYING THE FIXTURE TESTS to a custom built-in bookcase: (1) METHOD OF ATTACHMENT — SCREWED INTO WALL STUDS = significant permanent attachment (removing it would require tools and would leave damage); strongly suggests FIXTURE; (2) ADAPTATION — CUSTOM-SIZED to fit a particular alcove = specifically adapted to this property; cannot easily be used elsewhere; strongly suggests FIXTURE; (3) INTENTION — a reasonable person would conclude the installer INTENDED a permanent installation (custom work, structural attachment); suggests FIXTURE; (4) RELATIONSHIP — in a BUYER-SELLER context, the analysis favors INCLUSION with the real estate; (5) CONCLUSION — this is most likely a FIXTURE (real property) that CONVEYS WITH THE PROPERTY; (6) EXCEPTION — if the purchase contract SPECIFICALLY EXCLUDES it, the parties' agreement controls (the seller could reserve it by clear written exclusion). CONTRAST: a freestanding bookcase merely resting against the wall would be PERSONAL PROPERTY. Built-in/custom items are the most common fixture disputes — sellers wanting to keep custom built-ins MUST exclude them explicitly in the contract."},

  # ── Transfer of Title (4) ───────────────────────────────────────────────
  {"id":"re-nat-688","domain":"Transfer of Title","type":"single-choice",
   "question":"A BONA FIDE PURCHASER (BFP) for value without notice:",
   "choices":["Has no special protection","IS PROTECTED by recording statutes — a BFP who (1) PAYS VALUABLE CONSIDERATION, (2) acts in GOOD FAITH, and (3) takes WITHOUT NOTICE (actual, constructive, or inquiry) of prior unrecorded claims, generally takes FREE of those prior unrecorded interests; this protection is the foundation of the recording system and provides certainty for purchasers who properly search title and record","Loses to all prior claims","Only protected for cash purchases"],
   "correctAnswer":1,
   "explanation":"BONA FIDE PURCHASER (BFP) doctrine — foundational to the recording system: (1) DEFINITION — a purchaser who: (a) PAYS VALUABLE CONSIDERATION (not a gift; not a nominal sum); (b) acts in GOOD FAITH; AND (c) takes WITHOUT NOTICE (actual, constructive, or inquiry) of prior unrecorded claims; (2) PROTECTION — a BFP generally takes title FREE OF prior UNRECORDED interests that they had no notice of; (3) RATIONALE — provides CERTAINTY for purchasers who properly search the public records and record their interest; rewards diligence and the recording system; penalizes those who fail to record (their unrecorded interest can be defeated by a later BFP); (4) THE THREE TYPES OF NOTICE that defeat BFP status: (a) ACTUAL NOTICE — actual knowledge of the prior claim; (b) CONSTRUCTIVE NOTICE — recorded documents (the purchaser is charged with knowledge of what a proper title search would reveal); (c) INQUIRY NOTICE — facts that would put a reasonable person on inquiry (e.g., someone else in possession of the property); (5) RECORDING STATUTES — implement BFP protection differently (race, notice, race-notice — covered earlier); (6) NOT a BFP — donees (gift recipients), purchasers with notice, and bad-faith purchasers don't get BFP protection."},

  {"id":"re-nat-689","domain":"Transfer of Title","type":"single-choice",
   "question":"A buyer purchasing a property notices that someone OTHER than the seller is living in the house. The buyer doesn't investigate. This unexplained possession typically gives the buyer:",
   "choices":["No notice","Actual notice","Constructive notice","INQUIRY NOTICE — when facts exist that would cause a REASONABLE PERSON to investigate further (here, an unexplained occupant), the law CHARGES the buyer with knowledge of whatever a reasonable investigation WOULD HAVE REVEALED — even if the buyer didn't actually investigate; the buyer cannot claim BFP status by deliberately ignoring such red flags"],
   "correctAnswer":3,
   "explanation":"INQUIRY NOTICE: (1) DEFINITION — when FACTS EXIST that would cause a REASONABLE PERSON to make further inquiry, the law charges the person with knowledge of WHATEVER A REASONABLE INVESTIGATION WOULD HAVE REVEALED — even if they didn't actually investigate; (2) THE CLASSIC TRIGGER — SOMEONE OTHER THAN THE SELLER IN POSSESSION of the property: an unexplained occupant should prompt a reasonable buyer to ASK who they are and what rights they claim (they might be: a tenant with a lease, a buyer under an unrecorded contract, an adverse possessor, an heir, a person with a life estate); (3) CONSEQUENCE — a buyer who IGNORES such red flags is charged with inquiry notice and CANNOT claim BONA FIDE PURCHASER status as to the occupant's rights; the buyer takes subject to whatever interest the occupant actually has; (4) OTHER INQUIRY-NOTICE TRIGGERS: references in recorded documents to unrecorded instruments; physical conditions suggesting easements or encroachments; gaps or irregularities in the chain of title; (5) THE THREE TYPES OF NOTICE: ACTUAL (real knowledge), CONSTRUCTIVE (recorded documents), INQUIRY (facts requiring investigation); (6) PRACTICAL LESSON — buyers should ALWAYS investigate who is in possession and obtain estoppel certificates or written confirmation of any occupant's rights before closing."},

  {"id":"re-nat-690","domain":"Transfer of Title","type":"single-choice",
   "question":"CONSTRUCTIVE NOTICE in real estate is established by:",
   "choices":["PROPERLY RECORDING a document in the public land records — once recorded in the correct place, the document provides notice TO THE WORLD of its contents, regardless of whether anyone actually reads it; this is the foundation of the recording system: purchasers are CHARGED WITH KNOWLEDGE of all properly-recorded documents in the chain of title, whether or not they actually searched","Verbal statements","Personal knowledge only","Physical possession only"],
   "correctAnswer":0,
   "explanation":"CONSTRUCTIVE NOTICE — a cornerstone of the recording system: (1) DEFINITION — notice that the law IMPUTES to a person regardless of whether they have actual knowledge; (2) HOW ESTABLISHED — by PROPERLY RECORDING a document in the public land records (county recorder/registrar of deeds); (3) EFFECT — once a document is properly recorded in the correct place (correct county, correct index, chain of title), it provides NOTICE TO THE WORLD of its contents — REGARDLESS of whether any particular person actually reads it; (4) THE CHARGE — purchasers, lenders, and others are CHARGED WITH KNOWLEDGE of all properly-recorded documents in the chain of title — whether or not they actually conducted a search; failure to search doesn't excuse them; (5) PRACTICAL IMPLICATION — this is WHY recording is essential: a recorded deed, mortgage, easement, or lien binds subsequent purchasers even if they never saw it; conversely, an UNRECORDED interest typically does NOT provide constructive notice and can be defeated by a later BFP; (6) THE THREE NOTICE TYPES: ACTUAL (real knowledge), CONSTRUCTIVE (proper recording), INQUIRY (facts requiring investigation); (7) IMPROPER RECORDING — documents recorded in the WRONG place or OUTSIDE the chain of title (wild deeds) may NOT provide constructive notice."},

  {"id":"re-nat-691","domain":"Transfer of Title","type":"single-choice",
   "question":"ACTUAL NOTICE of a prior claim or interest is established by:",
   "choices":["Recording only","Possession only","DIRECT, PERSONAL KNOWLEDGE of the claim or interest — express information actually communicated to or known by the person (e.g., the buyer was specifically TOLD about an unrecorded easement, saw the prior contract, or otherwise had real knowledge); a person with actual notice cannot claim bona fide purchaser status as to that known interest, even if it was never recorded","Constructive notice only"],
   "correctAnswer":2,
   "explanation":"ACTUAL NOTICE: (1) DEFINITION — DIRECT, PERSONAL KNOWLEDGE of a claim, interest, or fact; express information actually communicated to or known by the person; (2) HOW ESTABLISHED — the person ACTUALLY KNOWS: e.g., they were specifically TOLD about an unrecorded easement; they SAW the prior purchase contract; the seller DISCLOSED a prior unrecorded conveyance; they received a letter about a competing claim; (3) EFFECT — a person with ACTUAL NOTICE of a prior interest CANNOT claim bona fide purchaser (BFP) status as to that known interest — even if the interest was never recorded; they take subject to it; (4) RATIONALE — it would be inequitable to let someone who KNOWS about a prior claim defeat it merely because it wasn't recorded; the recording system protects the diligent and good-faith, not those who knowingly try to exploit a recording gap; (5) THE THREE TYPES OF NOTICE: (a) ACTUAL — real, personal knowledge; (b) CONSTRUCTIVE — imputed by proper recording; (c) INQUIRY — imputed by facts requiring investigation; (6) PRACTICAL — all three types of notice defeat BFP status; a purchaser must be WITHOUT ANY of the three types of notice to qualify as a bona fide purchaser. Disclosure of known facts during a transaction can create actual notice."},

  # ── Valuation and Market Analysis (3) ───────────────────────────────────
  {"id":"re-nat-692","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"HIGHEST AND BEST USE analysis requires that the use be:",
   "choices":["Only physically possible","Only profitable","Random","FOUR TESTS — the use must be: (1) LEGALLY PERMISSIBLE (allowed by zoning, deed restrictions, and other legal constraints); (2) PHYSICALLY POSSIBLE (the site can physically support it — size, soil, topography, access); (3) FINANCIALLY FEASIBLE (it generates adequate return given the cost); and (4) MAXIMALLY PRODUCTIVE (of all feasible uses, the one producing the highest value/return); all four must be satisfied"],
   "correctAnswer":3,
   "explanation":"HIGHEST AND BEST USE — the FOUR TESTS, applied IN ORDER: (1) LEGALLY PERMISSIBLE — the use must be allowed under: zoning, deed restrictions, building codes, environmental regulations, historic district rules, etc. (illegal uses are excluded; legally nonconforming uses and reasonably probable rezoning may be considered); (2) PHYSICALLY POSSIBLE — the SITE must physically support the use: lot size and shape, soil/geology, topography, drainage, access, utility availability; (3) FINANCIALLY FEASIBLE — among legally permissible AND physically possible uses, the use must generate ADEQUATE RETURN to justify development costs (revenue exceeds total cost including a market return); (4) MAXIMALLY PRODUCTIVE — among all financially feasible uses, the one producing the HIGHEST VALUE/RESIDUAL LAND VALUE is the highest and best use. IMPORTANCE: (a) appraisals BEGIN with a highest-and-best-use analysis — value depends on the property's POTENTIAL, not just current use; (b) analyzed both AS VACANT and AS IMPROVED; (c) a property's current use may NOT be its highest and best use (e.g., a tear-down house on land worth more vacant). The four tests are applied sequentially — failing any test eliminates that use."},

  {"id":"re-nat-693","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"PLOTTAGE (or 'assemblage value') refers to:",
   "choices":["Subdividing land","A type of zoning","Random valuation","THE INCREMENT IN VALUE created when two or more adjacent parcels are COMBINED under single ownership to create a larger parcel that is MORE VALUABLE than the sum of the individual parcels — because the larger assembled site enables a higher and better use (e.g., a development that wasn't possible on the smaller individual lots); the value added by assemblage is 'plottage value'"],
   "correctAnswer":3,
   "explanation":"PLOTTAGE (ASSEMBLAGE VALUE): (1) DEFINITION — the INCREMENT IN VALUE created when two or more ADJACENT parcels are COMBINED under single ownership to form a larger parcel; (2) THE KEY PRINCIPLE — the combined parcel is worth MORE than the SUM of the individual parcels' separate values because: (a) the larger assembled site enables a HIGHER AND BETTER USE (a development, building, or use not possible on the smaller individual lots); (b) economies of scale, design flexibility, and development feasibility increase; (3) PLOTTAGE VALUE — the EXTRA VALUE created by the assemblage (Combined Value − Sum of Individual Values = Plottage Value); (4) EXAMPLE: three small adjacent lots each worth $200,000 ($600,000 total) might be worth $900,000 combined if the assembled parcel can support a profitable apartment building that none of the individual lots could — the $300,000 difference is plottage value; (5) ASSEMBLAGE — the PROCESS of combining the parcels (often through option agreements to lock prices while assembling); PLOTTAGE — the resulting VALUE INCREMENT; (6) RISK — assemblage often fails if one owner refuses to sell ('holdout'), so partial assembly may not realize plottage value. Developers and appraisers analyze plottage potential in land valuation."},

  {"id":"re-nat-694","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"In land valuation, the distinction between EXCESS LAND and SURPLUS LAND is:",
   "choices":["EXCESS LAND can be SEPARATED and SOLD or developed independently (it has its own highest and best use, separate from the existing improvement) — and is valued SEPARATELY; SURPLUS LAND cannot be separated/sold independently (it supports the existing use but no additional separate use) — it adds limited or no separate value beyond supporting the existing improvement; the distinction affects how the land is valued in the appraisal","No distinction","Both mean the same","Random terms"],
   "correctAnswer":0,
   "explanation":"EXCESS LAND vs. SURPLUS LAND — an important valuation distinction: (1) EXCESS LAND — land that is NOT NEEDED to support the existing improvement and CAN BE SEPARATED and SOLD OR DEVELOPED INDEPENDENTLY: (a) it has its OWN highest and best use, separate from the existing improvement; (b) it is VALUED SEPARATELY (added to the value of the improved portion); (c) example: a house on a 5-acre parcel where 4 acres could be subdivided and sold separately — those 4 acres are excess land valued on their own merits; (2) SURPLUS LAND — land that is MORE than typically needed but CANNOT be separated/sold independently: (a) it does NOT have a separate highest and best use; (b) it supports the existing improvement (extra yard, buffer) but no additional SEPARATE use; (c) it adds LIMITED OR NO SEPARATE VALUE beyond supporting the existing improvement (often valued at a discount or simply as part of the site); (3) WHY IT MATTERS — the appraiser must determine whether 'extra' land is EXCESS (separately valuable) or SURPLUS (limited added value) — this significantly affects the total valuation; (4) FACTORS — zoning (can it be subdivided?), access (does the extra land have road frontage?), market demand, physical characteristics. The classification drives the valuation methodology for large or irregularly-sized parcels."},

  # ── Property Disclosures (3) ────────────────────────────────────────────
  {"id":"re-nat-695","domain":"Property Disclosures","type":"single-choice",
   "question":"In California (and increasingly other states), a NATURAL HAZARD DISCLOSURE (NHD) statement is required, disclosing whether the property is in:",
   "choices":["No hazards","DESIGNATED HAZARD ZONES — including special flood hazard areas, dam inundation areas, very high fire hazard severity zones, wildland fire areas, earthquake fault zones (Alquist-Priolo), seismic hazard zones, and similar mapped hazard areas; sellers typically obtain the NHD report from a specialized company; the disclosure helps buyers understand natural-hazard risks and insurance/building implications","Only flood zones","Federal preemption"],
   "correctAnswer":1,
   "explanation":"NATURAL HAZARD DISCLOSURE (NHD) — required in California and increasingly common elsewhere: (1) WHAT IT DISCLOSES — whether the property is located within DESIGNATED MAPPED HAZARD ZONES: (a) SPECIAL FLOOD HAZARD AREA (FEMA); (b) AREA OF POTENTIAL FLOODING from dam failure (dam inundation); (c) VERY HIGH FIRE HAZARD SEVERITY ZONE; (d) WILDLAND AREA that may contain substantial forest fire risks (state responsibility area); (e) EARTHQUAKE FAULT ZONE (in CA, the Alquist-Priolo Earthquake Fault Zone); (f) SEISMIC HAZARD ZONE (liquefaction, landslide); (2) HOW PROVIDED — sellers typically obtain the NHD REPORT from a SPECIALIZED COMPANY (NHD report providers research the mapped zones); the disclosure form is delivered to the buyer; (3) PURPOSE — helps buyers understand: (a) NATURAL-HAZARD RISKS; (b) INSURANCE IMPLICATIONS (flood insurance requirements, fire insurance availability/cost — increasingly critical in wildfire-prone areas); (c) BUILDING/RETROFIT requirements (seismic, fire-hardening); (4) GROWING IMPORTANCE — wildfire and flood disclosures have become critical as climate-related risks increase and insurers withdraw from high-risk areas; (5) LIABILITY — failure to provide required NHD can result in rescission rights, damages, and license discipline."},

  {"id":"re-nat-696","domain":"Property Disclosures","type":"single-choice",
   "question":"A property is in a FEMA-designated SPECIAL FLOOD HAZARD AREA (SFHA). For a buyer obtaining a federally-related mortgage:",
   "choices":["No insurance required","Optional insurance","FLOOD INSURANCE IS GENERALLY MANDATORY — federal law requires lenders to ensure flood insurance is in place for properties in SFHAs securing federally-related mortgages; the lender will require it before closing; sellers and agents should disclose SFHA status; flood insurance is typically obtained through the National Flood Insurance Program (NFIP) or private carriers; premiums can be substantial and significantly affect affordability","Federal preemption"],
   "correctAnswer":2,
   "explanation":"SPECIAL FLOOD HAZARD AREA (SFHA) and flood insurance: (1) MANDATORY FLOOD INSURANCE — under the National Flood Insurance Act and federal lending rules, LENDERS MUST ensure flood insurance is in place for properties in SFHAs securing FEDERALLY-RELATED MORTGAGES (which includes virtually all conventional, FHA, VA, USDA loans); (2) THE LENDER WILL REQUIRE proof of flood insurance BEFORE CLOSING and will typically escrow premiums; (3) DISCLOSURE — sellers and agents should disclose known SFHA status; many states require flood disclosure; (4) FLOOD INSURANCE SOURCES: (a) NATIONAL FLOOD INSURANCE PROGRAM (NFIP) — the federal program (administered by FEMA); (b) PRIVATE FLOOD INSURANCE — a growing market, sometimes more competitive; (5) COST IMPACT — flood insurance premiums can be SUBSTANTIAL (especially after FEMA's Risk Rating 2.0 reforms, which price more by actual risk) and significantly affect affordability and the buyer's ability to qualify; (6) DISCLOSURE BEST PRACTICE — buyers should be advised to: obtain a flood determination early; get a flood insurance QUOTE during the inspection/contingency period (not at closing); understand that SFHA status materially affects ownership cost; (7) ELEVATION CERTIFICATES — may reduce premiums by documenting the structure's elevation relative to base flood elevation; (8) Standard homeowner's insurance does NOT cover flood — separate flood insurance is essential."},

  {"id":"re-nat-697","domain":"Property Disclosures","type":"single-choice",
   "question":"In wildfire-prone states (CA, CO, OR, and increasingly others), disclosure and risk considerations include:",
   "choices":["No considerations","Irrelevant","Federal preemption","WHETHER THE PROPERTY IS IN A HIGH OR VERY HIGH FIRE HAZARD ZONE, defensible-space and fire-hardening requirements (vegetation clearance, ember-resistant construction), insurance AVAILABILITY and COST (insurers have withdrawn from many high-risk areas; some markets rely on state FAIR Plan insurers of last resort), and any history of fire damage; these factors substantially affect insurability, value, and ownership cost"],
   "correctAnswer":3,
   "explanation":"WILDFIRE RISK — a rapidly growing real estate concern: (1) HAZARD ZONE STATUS — whether the property is in a HIGH or VERY HIGH FIRE HAZARD SEVERITY ZONE (mapped by state agencies like CAL FIRE); often part of the Natural Hazard Disclosure; (2) DEFENSIBLE SPACE and FIRE HARDENING — many jurisdictions require/encourage: (a) DEFENSIBLE SPACE (vegetation clearance zones — typically 100+ feet); (b) FIRE-HARDENING — ember-resistant vents, Class A roofing, non-combustible siding, dual-pane windows; (c) some states require disclosure of compliance and may require remediation before sale; (3) INSURANCE CRISIS — the BIGGEST current issue: (a) insurers have NON-RENEWED or WITHDRAWN from many high-risk areas; (b) homeowners increasingly rely on STATE 'FAIR PLAN' insurers of last resort (limited coverage, high cost); (c) lack of affordable insurance can make properties UNFINANCEABLE and UNSELLABLE; (4) DISCLOSURE — many states now require specific wildfire disclosures, defensible-space compliance disclosures, and hazard-zone notices; (5) VALUE IMPACT — high wildfire risk and insurance challenges substantially reduce value and marketability in affected areas; (6) BEST PRACTICE — buyers in fire-prone areas should obtain INSURANCE QUOTES EARLY (during the contingency period) — confirming insurability before removing contingencies. Climate-related disclosure requirements are expanding rapidly."},

  # ── Land Use Controls and Regulations (2) ───────────────────────────────
  {"id":"re-nat-698","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"INVERSE CONDEMNATION occurs when:",
   "choices":["A PROPERTY OWNER SUES THE GOVERNMENT, claiming a government action has effectively TAKEN or substantially damaged their property (or deprived them of beneficial use) WITHOUT formal eminent domain proceedings or just compensation — e.g., severe regulatory restrictions amounting to a 'regulatory taking,' or physical damage from a public project; the owner seeks compensation the government should have paid","The government sues the owner","No legal action","Random government action"],
   "correctAnswer":0,
   "explanation":"INVERSE CONDEMNATION: (1) DEFINITION — a legal action in which a PROPERTY OWNER SUES THE GOVERNMENT, claiming a government action has effectively TAKEN, substantially damaged, or deprived them of the beneficial use of their property — WITHOUT the government having initiated formal eminent domain proceedings or paid just compensation; (2) IT'S THE REVERSE of eminent domain — in EMINENT DOMAIN, the government initiates the taking and pays compensation; in INVERSE CONDEMNATION, the OWNER initiates the lawsuit seeking compensation the government should have paid but didn't; (3) COMMON SCENARIOS: (a) REGULATORY TAKINGS — government regulation so restrictive it deprives the owner of all (or substantially all) economically beneficial use (per Lucas v. South Carolina Coastal Council) or goes 'too far' (Penn Central balancing test); (b) PHYSICAL INVASION/DAMAGE — a public project (flooding from a dam, aircraft noise from a public airport, soil subsidence from public works) that physically damages or invades the property; (c) ACCESS DEPRIVATION — government action eliminating reasonable access to the property; (4) REMEDY — just compensation (and sometimes attorneys' fees); (5) CONSTITUTIONAL BASIS — the Fifth Amendment Takings Clause; (6) the doctrine ensures the government cannot accomplish a taking 'by the back door' through regulation or public projects without paying compensation. Regulatory takings law is complex and heavily litigated."},

  {"id":"re-nat-699","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"The distinction between a valid exercise of POLICE POWER and a regulatory TAKING is:",
   "choices":["No distinction","POLICE POWER allows the government to REGULATE property use for public health, safety, morals, and general welfare WITHOUT compensation (zoning, building codes, environmental rules); but if regulation goes 'TOO FAR' — depriving the owner of all (or substantially all) economically beneficial use, or unfairly burdening the owner — it becomes a regulatory TAKING requiring just compensation; courts apply tests (Lucas total-taking rule; Penn Central multi-factor balancing) to determine where regulation crosses the line","All regulation is a taking","Federal preemption"],
   "correctAnswer":1,
   "explanation":"POLICE POWER vs. REGULATORY TAKING — a fundamental and heavily litigated distinction: (1) POLICE POWER — the government's inherent authority to REGULATE private property use to protect PUBLIC HEALTH, SAFETY, MORALS, AND GENERAL WELFARE — WITHOUT paying compensation. Examples: zoning, building codes, environmental regulations, health/safety codes, nuisance abatement; (2) REGULATORY TAKING — when regulation goes 'TOO FAR' (Justice Holmes's phrase in Pennsylvania Coal v. Mahon), it becomes a TAKING requiring JUST COMPENSATION under the Fifth Amendment; (3) THE TESTS courts apply: (a) LUCAS RULE (per se / categorical taking) — if regulation deprives the owner of ALL economically beneficial or productive use, it's a taking (unless background nuisance/property law principles already prohibited the use); (b) PENN CENTRAL BALANCING TEST (the general test) — courts weigh: (i) the ECONOMIC IMPACT of the regulation on the owner; (ii) the extent of interference with INVESTMENT-BACKED EXPECTATIONS; (iii) the CHARACTER of the government action (physical invasion vs. mere regulation); (c) NOLLAN/DOLAN — exactions (conditions on permits) must have an 'essential nexus' and 'rough proportionality' to the project's impacts; (4) PHYSICAL INVASION — even a small PERMANENT PHYSICAL OCCUPATION authorized by government is a per se taking (Loretto); (5) the line between valid regulation and a compensable taking is one of the most complex areas of property law."},

  # ── Leasing and Property Management (1) ─────────────────────────────────
  {"id":"re-nat-700","domain":"Leasing and Property Management","type":"single-choice",
   "question":"The COVENANT OF QUIET ENJOYMENT in a lease guarantees the tenant:",
   "choices":["A noise-free environment","No neighbors","THE RIGHT TO POSSESS AND USE the leased premises WITHOUT SUBSTANTIAL INTERFERENCE from the landlord or anyone claiming superior title — it protects against actual or constructive eviction, the landlord's wrongful entry, and disturbance of the tenant's lawful possession; breach (e.g., failing to provide essential services rendering the premises uninhabitable) can support a constructive eviction claim and rent abatement","Free rent"],
   "correctAnswer":2,
   "explanation":"COVENANT OF QUIET ENJOYMENT — a fundamental lease protection (implied in virtually all leases, often also express): (1) WHAT IT GUARANTEES — the tenant's right to POSSESS AND USE the leased premises WITHOUT SUBSTANTIAL INTERFERENCE from: (a) the LANDLORD (wrongful entry, harassment, failure to provide essential services, disturbing the tenant's use); (b) ANYONE CLAIMING SUPERIOR TITLE (e.g., a lender foreclosing, a true owner if the landlord lacked title); (2) WHAT IT IS NOT — it does NOT guarantee a literally 'quiet' (noise-free) environment or freedom from ordinary neighbor annoyances; the 'quiet' refers to PEACEFUL POSSESSION, not the absence of noise; (3) BREACH — occurs through ACTUAL EVICTION (physically ousting the tenant) or CONSTRUCTIVE EVICTION (the landlord's actions/inactions so substantially interfere with the tenant's use that the premises become uninhabitable — e.g., failing to provide heat/water, persistent flooding, refusing essential repairs); (4) TENANT REMEDIES for breach: (a) CONSTRUCTIVE EVICTION claim — tenant vacates within a reasonable time, stops paying rent, may sue for damages; (b) RENT ABATEMENT; (c) DAMAGES; (d) INJUNCTIVE RELIEF; (5) the covenant is closely related to the IMPLIED WARRANTY OF HABITABILITY (in residential leases) — both protect the tenant's beneficial use of the premises; (6) the covenant runs to anyone with rightful possession and is a cornerstone of landlord-tenant law."},
]

data.extend(new_qs)
Q.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"Written: {len(data)} questions")
