"""Real Estate National batch 11 — questions 501-550."""
import json, pathlib

Q = pathlib.Path("src/data/real-estate-national-questions.json")
data = json.loads(Q.read_text(encoding="utf-8"))

new_qs = [
  # ── Contracts (9) ───────────────────────────────────────────────────────
  {"id":"re-nat-501","domain":"Contracts","type":"single-choice",
   "question":"A buyer receives a general warranty deed. Two years after closing, the buyer is sued by a third party claiming superior title based on a pre-existing recorded deed. The buyer may:",
   "choices":["Sue the seller for BREACH OF WARRANTY — general warranty deeds carry covenants (seisin, against encumbrances, of quiet enjoyment, of warranty, of further assurance) that protect the grantee against title defects, including those predating the grantor's ownership","Have no recourse","Sue federal regulators","Wait until the third party prevails"],
   "correctAnswer":0,
   "explanation":"General warranty deeds carry the broadest title-warranty protections: (1) COVENANT OF SEISIN — the grantor warrants they have the title they purport to convey; (2) COVENANT AGAINST ENCUMBRANCES — no undisclosed liens or encumbrances; (3) COVENANT OF QUIET ENJOYMENT — the grantee will not be lawfully disturbed in possession; (4) COVENANT OF WARRANTY — the grantor will defend the title against all claims; (5) COVENANT OF FURTHER ASSURANCE — the grantor will execute additional documents needed to perfect title. A buyer facing a title challenge can sue the grantor for breach of one or more covenants — including for claims predating the grantor's ownership."},

  {"id":"re-nat-502","domain":"Contracts","type":"single-choice",
   "question":"A purchase contract conditions performance on the buyer obtaining a building permit for a planned renovation. If the permit is denied, the buyer:",
   "choices":["Must perform anyway","HAS NO OBLIGATION TO PERFORM — the condition has failed; the contract typically terminates and the buyer is entitled to return of earnest money; however, the buyer must typically make good-faith effort to obtain the permit (cannot deliberately fail) and timely notify the seller","Loses earnest money","Owes damages"],
   "correctAnswer":1,
   "explanation":"A condition precedent that fails — through no bad faith of the requesting party — typically terminates the contract. The buyer in this scenario: (1) is excused from performance; (2) is entitled to return of earnest money; (3) may have a duty to make GOOD-FAITH EFFORT to satisfy the condition (cannot deliberately fail to apply for the permit, etc.); (4) must typically deliver TIMELY NOTICE to the seller of the failed condition per the contract. Conditions in real estate contracts (financing, inspection, permit, appraisal) are commonly conditional precedent — their failure excuses the buyer from the otherwise binding contract."},

  {"id":"re-nat-503","domain":"Contracts","type":"single-choice",
   "question":"A property is conveyed twice in succession: First, Seller S sells to Buyer A (but A does not record). Second, Seller S sells again to Buyer B (who has no notice of A's deed) and B promptly records. Under a typical 'race-notice' recording statute, the title:",
   "choices":["Goes to A","Goes to both equally","GOES TO BUYER B — a good-faith purchaser without notice who recorded first; A loses out for failing to record promptly. (Under a pure 'race' statute, B wins by recording first regardless of notice. Under a 'notice' statute, B wins by being without notice, regardless of recording first.) State recording statutes determine the outcome","Reverts to Seller S"],
   "correctAnswer":2,
   "explanation":"This scenario illustrates the importance of recording. Under a race-notice statute (the most common type in the US): the LATER buyer (B) prevails if: (1) WITHOUT NOTICE of the prior unrecorded conveyance, AND (2) RECORDS FIRST. Buyer A loses for failing to record promptly. Under a PURE RACE STATUTE: B wins by recording first regardless of notice. Under a PURE NOTICE STATUTE: B wins by being without notice, regardless of whether recording occurs first. Each state's specific recording statute determines the outcome. The lesson: RECORD PROMPTLY after closing to protect against subsequent transfers."},

  {"id":"re-nat-504","domain":"Contracts","type":"single-choice",
   "question":"A buyer seeking specific performance against a seller may face the following defenses:",
   "choices":["Only laches","Only money damages","Only Statute of Frauds","Multiple defenses: STATUTE OF FRAUDS (no written contract); buyer's INABILITY TO PERFORM (no funds, no financing); UNCLEAN HANDS (buyer's own misconduct); LACHES (unreasonable delay in seeking the remedy); IMPOSSIBILITY (property destroyed or already sold to a good-faith purchaser); AND fundamental contract defenses (fraud, duress, capacity)"],
   "correctAnswer":3,
   "explanation":"Specific performance is an EQUITABLE remedy with multiple potential defenses: (1) STATUTE OF FRAUDS — no enforceable written contract; (2) BUYER'S INABILITY TO PERFORM — no funds, no financing, etc.; (3) UNCLEAN HANDS — the buyer's own misconduct (fraud, breach, bad faith); (4) LACHES — unreasonable delay in seeking the remedy that prejudices the seller; (5) IMPOSSIBILITY — property destroyed or already sold to a bona fide purchaser; (6) BASIC CONTRACT DEFENSES — fraud, duress, undue influence, mutual mistake, capacity; (7) UNDUE HARDSHIP — if SP would cause disproportionate harm to the seller. Specific performance is far from automatic — buyers must demonstrate eligibility and overcome any defenses."},

  {"id":"re-nat-505","domain":"Contracts","type":"single-choice",
   "question":"A deed contains an error in the legal description (e.g., wrong lot number). The remedy is typically:",
   "choices":["REFORMATION — court order CORRECTING the deed to reflect what the parties actually intended; or, with party cooperation, a CORRECTIVE DEED (a new deed executed and recorded to correct the original); these tools fix errors WITHOUT canceling the original transaction","Ignoring the error","Voiding the deed entirely","Federal court referral"],
   "correctAnswer":0,
   "explanation":"For errors in deeds, two common remedies: (1) REFORMATION — a court orders CORRECTION of the deed to reflect what the parties actually intended. The party seeking reformation must prove the original intent and the error by 'clear and convincing evidence' in most states. (2) CORRECTIVE DEED — if parties agree on the error, a new deed (often labeled 'Corrective Deed') can be executed and recorded to fix the original. Both tools FIX errors without canceling the underlying transaction. Common errors corrected: lot numbers, addresses, marital status, grantor/grantee names, recording references. Reformation requires more substantial proof; corrective deeds require party cooperation."},

  {"id":"re-nat-506","domain":"Contracts","type":"single-choice",
   "question":"A real estate contract's description of the property is precise enough on its face but a latent ambiguity exists (e.g., the address refers to a property with two distinct parts and it's unclear which part is being conveyed). Under the PAROL EVIDENCE rule:",
   "choices":["Cannot be clarified","LATENT AMBIGUITIES — those not apparent on the face of the contract but emerging when applying the contract to facts — CAN be clarified through extrinsic evidence (the parties' conduct, course of dealing, prior communications, etc.) without violating the parol evidence rule's ban on contradicting written terms","Are always void","Are excused by federal law"],
   "correctAnswer":1,
   "explanation":"Latent ambiguities — those not apparent on the face of the contract but emerging when applying the contract to facts — present a special interpretive problem. The PAROL EVIDENCE RULE generally prohibits extrinsic evidence that contradicts written contract terms. However, courts allow extrinsic evidence to RESOLVE LATENT AMBIGUITIES — the evidence does NOT contradict the written terms; rather, it determines which of multiple possible interpretations is the intended one. Examples: an address that could refer to two distinct properties, a description referring to 'my property at X' when the grantor owns multiple. Without extrinsic evidence, latent ambiguities would render the contract unenforceable."},

  {"id":"re-nat-507","domain":"Contracts","type":"single-choice",
   "question":"A buyer's agent performs services for a buyer who later refuses to pay any commission. Even without an enforceable written agreement, the agent may sue for:",
   "choices":["Specific performance","Punitive damages only","QUANTUM MERUIT — recovery for the REASONABLE VALUE of services performed, on a theory of unjust enrichment; available when one party has provided benefits to another in circumstances making it inequitable for the receiving party to retain them without payment; some states allow it even without an enforceable underlying contract","Treble damages"],
   "correctAnswer":2,
   "explanation":"Quantum meruit ('as much as deserved') is a quasi-contractual recovery for the REASONABLE VALUE OF SERVICES PERFORMED. It applies when: (1) one party has provided BENEFITS to another, (2) the receiving party knew or should have known the services were being provided, (3) it would be INEQUITABLE for the receiving party to retain the benefits without paying. Quantum meruit can provide recovery even when there's no enforceable written contract (Statute of Frauds, missing terms, etc.). Some states allow it for real estate licensee services; others apply restrictive interpretations. The recovery is the FAIR MARKET VALUE of services — not the contracted rate."},

  {"id":"re-nat-508","domain":"Contracts","type":"single-choice",
   "question":"A contract states: 'Closing shall occur 30 days after the buyer obtains satisfactory financing.' This is best described as:",
   "choices":["A one-time obligation","An option contract","Anticipatory breach","A CONDITION PRECEDENT — the seller's obligation to convey title at the 30-day mark is conditioned on the prior occurrence of an event (buyer obtaining satisfactory financing); failure of the condition typically excuses performance"],
   "correctAnswer":3,
   "explanation":"A CONDITION PRECEDENT is an event that must occur (or be waived) BEFORE the obligated party's performance becomes due. The seller's obligation to close at the 30-day mark is conditioned on the prior occurrence of the financing event. If the buyer cannot obtain satisfactory financing within the timeframe: (1) the condition fails, (2) the seller's obligation never matures, (3) the contract typically terminates and the buyer typically recovers earnest money (assuming no buyer bad faith). The contract's language is critical — 'satisfactory financing' is vague; what does it mean? Best practice is specific language defining the required financing parameters."},

  {"id":"re-nat-509","domain":"Contracts","type":"single-choice",
   "question":"A buyer defaults on a residential purchase contract. The seller's duty to MITIGATE damages requires:",
   "choices":["Selling at any price","Doing nothing for 6 months","TAKING REASONABLE STEPS to reduce damages — relisting the property promptly, accepting reasonable backup offers, etc. — even though the breaching buyer remains liable for resulting damages. The seller cannot let the property sit indefinitely and then sue for full lost value. Mitigation does NOT require accepting unreasonably low offers","No mitigation duty"],
   "correctAnswer":1,
   "explanation":"The DUTY TO MITIGATE requires the non-breaching party to take reasonable steps to reduce their damages. For a seller after buyer breach: (1) RELIST the property promptly; (2) ACCEPT reasonable backup offers; (3) MARKET the property using customary methods. The seller cannot 'sit on' the property and then claim full lost value — damages will be REDUCED by amounts the seller could have reasonably mitigated. Mitigation does NOT require the seller to accept unreasonable offers or take losses to mitigate. The breaching buyer remains liable for damages NET OF reasonable mitigation efforts. Documentation of mitigation efforts is important if litigation arises."},

  # ── General Principles of Agency (7) ────────────────────────────────────
  {"id":"re-nat-510","domain":"General Principles of Agency","type":"single-choice",
   "question":"A property has had multiple prior owners die in the home. The disclosure obligation regarding this 'stigmatized' property is:",
   "choices":["Mandatory federal disclosure","No disclosure ever required","HIGHLY STATE-DEPENDENT — some states require disclosure of certain stigmatizing facts (recent violent deaths, suicides, criminal activity, hauntings); others classify these as non-material facts requiring no disclosure unless asked; still others have specific notice requirements directing buyers to consult public records","Always actionable misrepresentation if not disclosed"],
   "correctAnswer":2,
   "explanation":"Stigmatized property disclosure is HIGHLY STATE-DEPENDENT. State approaches vary: (1) AFFIRMATIVE DISCLOSURE — required for certain facts (some states require disclosure of recent violent deaths, suicides, criminal activity, alleged hauntings); (2) NON-MATERIAL FACTS STATUTE — classify the facts as non-material, requiring no disclosure even on request; (3) DISCLOSURE ONLY ON REQUEST — disclose if asked, but no affirmative duty; (4) STATUTORY NOTICES — many states require contract notices directing buyers to consult public sex offender registries and other public records. Licensees must know their state's specific rules. Notably, RELIGIOUS BELIEFS about stigmatization are not generally protected from disclosure (e.g., haunting disclosures even where 'hauntings' are not legally cognizable)."},

  {"id":"re-nat-511","domain":"General Principles of Agency","type":"single-choice",
   "question":"A property manager is hired to manage a rental property for an owner. The property manager owes the owner:",
   "choices":["No duties","Only a duty to collect rent","Federal duty of loyalty","FIDUCIARY DUTIES — including loyalty, care, accounting (separate trust account for tenant funds), disclosure of material facts, and obedience to lawful instructions; the property manager is an agent of the owner, subject to the same fiduciary duty framework as a real estate broker"],
   "correctAnswer":3,
   "explanation":"Property managers are agents of the owner, subject to the full FIDUCIARY DUTY framework: (1) LOYALTY — managing the property in the owner's best interest, not for the manager's personal benefit; (2) CARE — exercising reasonable skill and diligence; (3) ACCOUNTING — maintaining separate trust account for tenant funds (security deposits, rents), providing detailed financial reporting; (4) DISCLOSURE — material facts affecting the owner's interest; (5) OBEDIENCE — following lawful instructions; (6) CONFIDENTIALITY — protecting non-public information. Most states require property managers to hold real estate licenses (broker or salesperson). Significant exposure for breaches: license discipline, civil liability, regulatory penalties."},

  {"id":"re-nat-512","domain":"General Principles of Agency","type":"single-choice",
   "question":"A seller's authorization to the listing broker typically includes:",
   "choices":["AUTHORITY TO LIST and MARKET the property at the agreed price, present offers, hold open houses, and provide standard agency services — but NOT authority to BIND THE SELLER to a contract or accept an offer without the seller's signature; the agent generally needs SPECIFIC additional authority (or a properly executed POA) to bind the seller","Authority to convey title","Authority to set commission","Authority to skip the listing"],
   "correctAnswer":0,
   "explanation":"Listing agents generally have EXPRESS AUTHORITY: (1) to list and MARKET the property at the seller's specified terms; (2) to present offers from buyers; (3) to hold open houses and showings; (4) to communicate with prospective buyers; (5) to negotiate terms (subject to the seller's review). They generally do NOT have authority to: (a) BIND the seller to a contract; (b) ACCEPT an offer on the seller's behalf without specific authority; (c) SIGN the deed for the seller. Binding actions typically require the seller's signature or a properly executed POA (power of attorney) granting specific authority. Listing agents who exceed their authority can face liability for damages, license discipline, and lost commissions."},

  {"id":"re-nat-513","domain":"General Principles of Agency","type":"single-choice",
   "question":"In a traditional cooperative MLS sale, the buyer's broker historically acted as a SUBAGENT of the seller's broker (and indirectly of the seller). After the 2024 NAR settlement:",
   "choices":["Subagency is still required","Most modern transactions involve EXPLICIT BUYER REPRESENTATION via written buyer-representation agreements signed before showing properties; the historical subagency model has largely been replaced by buyer agency, designated agency (when within one brokerage), or transactional brokerage (in states recognizing it)","Subagency is illegal","Federal law mandates a specific model"],
   "correctAnswer":1,
   "explanation":"The historical subagency model — where the buyer's broker technically owed fiduciary duties to the SELLER (since the seller paid all commissions) — has largely been replaced. Modern practice: (1) EXPLICIT BUYER REPRESENTATION via written buyer-rep agreements (now required before showing properties per 2024 NAR settlement); (2) DESIGNATED AGENCY when transactions are within one brokerage; (3) DUAL AGENCY with informed consent; (4) TRANSACTIONAL BROKERAGE in states recognizing it (no fiduciary relationship, just facilitation). The shift to explicit buyer agency has been driven by: consumer-protection concerns, antitrust litigation (settled in 2024), and recognition that the historical model created conflicts of interest."},

  {"id":"re-nat-514","domain":"General Principles of Agency","type":"single-choice",
   "question":"When a licensee prepares a CMA (Comparative Market Analysis) for a seller, professional standards require:",
   "choices":["No standards","Mandatory federal accreditation","CARE in comparable selection (recent, similar properties from comparable neighborhoods); APPROPRIATE adjustments for differences; CLEAR disclosure of the CMA's purpose and limitations; AVOIDANCE of misrepresenting the CMA as a formal appraisal; the agent should be qualified and have local market knowledge","Federal certification"],
   "correctAnswer":2,
   "explanation":"While CMAs are NOT formal appraisals (USPAP doesn't apply directly), professional standards still require: (1) CARE in comparable selection — recent, similar properties from comparable neighborhoods; (2) APPROPRIATE adjustments for material differences (square footage, lot size, features, condition); (3) CLEAR DISCLOSURE that the CMA is an agent-prepared market analysis, NOT a formal appraisal — and shouldn't be relied on for legally significant valuations; (4) AVOIDANCE of misrepresenting the CMA's nature or reliability; (5) LOCAL MARKET KNOWLEDGE on the part of the agent. Poorly-prepared CMAs that mislead sellers can result in: license discipline, civil liability for damages (overpricing leading to extended market time, underpricing leading to lost equity), and reputational harm."},

  {"id":"re-nat-515","domain":"General Principles of Agency","type":"single-choice",
   "question":"Following the 2024 NAR settlement, the practice of broker COOPERATION (sellers' brokers working with buyers' brokers from different firms) is now generally:",
   "choices":["Eliminated","CONTINUES — sellers' brokers continue to cooperate with buyers' brokers from other firms in the sale of listings; the change is that COMMISSION COMPENSATION offered to cooperating buyer-side brokers is NEGOTIATED through buyer-representation agreements and the purchase contract (not through MLS broadcast offers as previously)","Required to be free","Forbidden across state lines"],
   "correctAnswer":1,
   "explanation":"BROKER COOPERATION continues post-2024 — sellers' brokers and buyers' brokers from different firms still work together to facilitate transactions. The KEY CHANGE is HOW BUYER-BROKER COMPENSATION is HANDLED: (1) MLS NO LONGER BROADCASTS unilateral offers of compensation from listing brokers to cooperating buyer brokers; (2) BUYER-BROKER COMPENSATION must be NEGOTIATED THROUGH WRITTEN BUYER-REPRESENTATION AGREEMENTS (signed before showing properties); (3) SELLER-PAID CONCESSIONS toward buyer-broker compensation continue to be common (negotiated in the purchase contract); (4) BUYERS may also pay their broker directly. The shift increases transparency about how buyer-broker compensation works."},

  {"id":"re-nat-516","domain":"General Principles of Agency","type":"single-choice",
   "question":"A listing agreement is generally:",
   "choices":["A PRIVATE CONTRACT between the seller and the listing broker establishing the agency relationship, the property to be marketed, the listing term, the commission, and other agreed terms; not a public document until publicly listed via MLS or other marketing","A government filing","Always recorded","Available to the public"],
   "correctAnswer":0,
   "explanation":"A listing agreement is a PRIVATE CONTRACT between the seller and the listing brokerage establishing the agency relationship and the marketing engagement. Key elements: (1) IDENTIFICATION of the parties; (2) DESCRIPTION of the property; (3) LISTING PRICE and TERMS; (4) LISTING TERM (definite expiration date, required in most states); (5) COMMISSION rate or amount; (6) AGENT'S DUTIES; (7) MARKETING METHODS authorized; (8) ANY EXCLUSIONS (e.g., specific buyers the seller wants excluded from the agreement); (9) BROKER PROTECTION PERIOD (post-listing protection if a buyer who saw the property during the listing later purchases). The agreement is not publicly recorded — it's a private contract. Once the property is listed via MLS, certain summary information becomes available to brokers."},

  # ── Practice of Real Estate (7) ─────────────────────────────────────────
  {"id":"re-nat-517","domain":"Practice of Real Estate","type":"single-choice",
   "question":"MEDIATION in real estate disputes is:",
   "choices":["A criminal proceeding","An informal, non-binding process in which a neutral mediator helps the parties reach voluntary settlement; the mediator does NOT decide the dispute (unlike an arbitrator); if mediation fails, the parties can still litigate or arbitrate; widely used and increasingly required by contract clauses or court orders","Always binding","Identical to arbitration"],
   "correctAnswer":1,
   "explanation":"Mediation is a STRUCTURED but INFORMAL process: (1) The mediator is a NEUTRAL FACILITATOR — they do NOT decide the dispute; (2) The process is typically CONFIDENTIAL — communications are protected; (3) Mediators help the parties understand each other's positions, identify common ground, and reach VOLUNTARY SETTLEMENT; (4) The mediator's role is FACILITATIVE, not decisional; (5) If mediation fails to produce settlement, the parties retain all other dispute-resolution rights (litigation, arbitration). Advantages: faster, cheaper, confidential, preserves relationships, parties control outcome. Required by many real estate contract clauses and increasingly by court orders before allowing litigation."},

  {"id":"re-nat-518","domain":"Practice of Real Estate","type":"single-choice",
   "question":"ARBITRATION in real estate disputes:",
   "choices":["Is non-binding","Eliminates the right to courts entirely in all cases","Is the same as mediation","Is a BINDING decision-making process — an arbitrator (or panel) hears evidence and ISSUES A FINAL DECISION ('award'); the arbitrator's award is GENERALLY BINDING on the parties, with very limited grounds for court appeal (under the Federal Arbitration Act and state versions); designed to be faster, cheaper, and more flexible than litigation"],
   "correctAnswer":3,
   "explanation":"Arbitration is BINDING decision-making — an arbitrator (or panel) hears evidence and ISSUES A FINAL DECISION called an AWARD. Key features: (1) BINDING — the award typically cannot be appealed to court except on very limited grounds (fraud, arbitrator misconduct, corruption, exceeding authority); (2) PRIVATE — confidential, no jury, no public record; (3) FASTER than litigation; (4) GENERALLY CHEAPER than litigation; (5) RULES vary widely — the parties typically choose AAA, JAMS, NAR-administered, or other rules. Arbitration clauses are common in real estate contracts. The Federal Arbitration Act and state versions strongly favor enforcement of arbitration agreements. NAR Code of Ethics requires REALTORS® to use arbitration for member-to-member commission disputes."},

  {"id":"re-nat-519","domain":"Practice of Real Estate","type":"single-choice",
   "question":"Trade associations like NAR provide ANTITRUST SAFE HARBORS for member activities such as:",
   "choices":["Setting industry-wide commission rates","Coordinating commission rates among members","Industry-wide territory allocation","INDUSTRY EDUCATION, BEST-PRACTICE GUIDANCE, STANDARDIZED FORMS, NEUTRAL DISPUTE RESOLUTION services — provided that each member independently makes pricing, customer-allocation, and other competitive decisions, and the association doesn't FACILITATE coordinated anti-competitive conduct"],
   "correctAnswer":3,
   "explanation":"Trade associations can provide LEGITIMATE benefits without antitrust risk when their activities focus on: (1) INDUSTRY EDUCATION — CE courses, designations, ethics training; (2) BEST-PRACTICE GUIDANCE — model contracts, professional standards; (3) STANDARDIZED FORMS — listing agreements, purchase contracts; (4) NEUTRAL DISPUTE RESOLUTION — arbitration, mediation services; (5) LEGISLATIVE/REGULATORY ADVOCACY (with first-amendment protection); (6) STATISTICAL DATA — aggregated industry data, NOT specific competitor data. NOT permitted: (a) coordinating prices or commission rates; (b) allocating customers or territories; (c) refusing to deal with non-members; (d) sharing competitively sensitive information among competitors. The 2024 NAR settlements arose precisely from concerns about anti-competitive practices."},

  {"id":"re-nat-520","domain":"Practice of Real Estate","type":"single-choice",
   "question":"HUD enforces the federal Fair Housing Act through:",
   "choices":["INVESTIGATION of complaints (typically within 100 days), efforts to conciliate, formal CHARGES if violations are found, ADMINISTRATIVE HEARINGS before HUD ALJs (or referral to DOJ for federal court litigation at complainant's election), and ongoing 'pattern or practice' enforcement; remedies include damages, injunctive relief, civil penalties","No enforcement","State court referrals only","Federal grand jury proceedings"],
   "correctAnswer":0,
   "explanation":"HUD's enforcement of the Fair Housing Act: (1) RECEIVES COMPLAINTS — must be filed within 1 year of alleged violation; (2) INVESTIGATES — typically within 100 days, examining evidence, interviewing parties; (3) CONCILIATES — attempts voluntary resolution; (4) ISSUES FORMAL CHARGES if violations are found and conciliation fails; (5) ADMINISTRATIVE HEARING before HUD ALJ OR (at complainant's election) REFERRAL TO DOJ for federal court litigation; (6) ONGOING 'PATTERN OR PRACTICE' enforcement; (7) REMEDIES include compensatory damages, injunctive relief, civil penalties (escalating for repeat violations), and required affirmative action. State and local fair-housing agencies often work in parallel with HUD."},

  {"id":"re-nat-521","domain":"Practice of Real Estate","type":"single-choice",
   "question":"MULTISTATE PRACTICE by real estate licensees:",
   "choices":["Is illegal everywhere","Requires federal license","Is regulated by international treaty","Is regulated by EACH state's licensing laws — typically requiring SEPARATE licensure in each state where the licensee actively practices; many states have RECIPROCITY agreements making it easier to obtain additional state licenses; licensees who 'practice' in another state without proper licensure can face license discipline, civil liability, and unenforceable commission claims"],
   "correctAnswer":3,
   "explanation":"Multistate practice is REGULATED BY EACH STATE — there's no federal real estate license. Generally: (1) SEPARATE LICENSURE required in each state where actively practicing; (2) RECIPROCITY agreements between many states allow streamlined licensure (often skipping the national portion of the exam, with reduced education requirements); (3) 'PRACTICE' is broadly defined — listing, showing properties, negotiating, or representing clients in another state typically requires licensure there; (4) EXCEPTIONS — limited 'cooperation' or 'referral-only' activities in some states; (5) RISKS of unlicensed practice: license discipline in home state, civil liability to consumers, INABILITY TO COLLECT COMMISSIONS, and potentially criminal charges. Licensees should consult both states' specific rules before crossing state lines for real estate activity."},

  {"id":"re-nat-522","domain":"Practice of Real Estate","type":"single-choice",
   "question":"REAL ESTATE LICENSING LAWS vary significantly state-by-state because:",
   "choices":["Federal preemption","Random differences","Real estate licensing has historically been a STATE responsibility under the U.S. federal system; each state has independently developed its licensing requirements, real estate commission structure, and substantive law. While there are many similarities (CE, prelicensing education, exam, background check), specific requirements vary widely — making INTRASTATE expertise essential","Federal mandate"],
   "correctAnswer":2,
   "explanation":"Real estate licensing has historically been a STATE responsibility under the U.S. federal system (10th Amendment reserved powers). Each state has independently developed: (1) LICENSING REQUIREMENTS — minimum age (often 18-19), pre-licensing education hours (often 60-180+), examination requirements, background check rules; (2) REAL ESTATE COMMISSION structure (commissioners, executive directors, staff); (3) SUBSTANTIVE LAW — what licensees can/cannot do, fiduciary duties, agency models, trust account rules; (4) FEE STRUCTURES; (5) CE REQUIREMENTS — variable hours and topics. Reciprocity agreements help with multistate practice but each state's specific rules ultimately govern. This decentralization means knowing your specific state's rules is essential."},

  {"id":"re-nat-523","domain":"Practice of Real Estate","type":"single-choice",
   "question":"At closing, when a closing agent discovers a SHORTAGE in the buyer's escrow account (the buyer hasn't deposited enough), the closing agent must:",
   "choices":["Cover the shortage from the agent's funds","Skip the shortage","NOT CLOSE the transaction until the shortage is resolved — closing requires all funds to be on deposit; the buyer must deliver additional funds, or the parties must agree to: (a) reduce the purchase price, (b) increase the loan, (c) accept seller financing, (d) extend the closing date; closing without resolving the shortage exposes all parties to liability","Close anyway and bill later"],
   "correctAnswer":2,
   "explanation":"When an escrow shortage is discovered at closing, the closing agent must NOT close until resolved. Closing requires all funds to be on deposit. Resolution options: (1) BUYER DELIVERS ADDITIONAL FUNDS — wire transfer, cashier's check; (2) REDUCED PURCHASE PRICE — seller agrees to a price reduction matching the shortage; (3) INCREASED LOAN — lender approves additional loan amount; (4) SELLER FINANCING — seller takes back a note for the shortage; (5) EXTENDED CLOSING — postpone until funds are available. Closing without resolving the shortage exposes: the closing agent (E&O liability, professional discipline), the buyer (default risk), the seller (incomplete payment, future title cloud), the lender (if discovered), and creates substantial title risk. Closings can be postponed or canceled, but never closed with a known shortage."},

  # ── Financing (5) ───────────────────────────────────────────────────────
  {"id":"re-nat-524","domain":"Financing","type":"single-choice",
   "question":"A NEGATIVE AMORTIZATION mortgage:",
   "choices":["Allows monthly payments LESS than the interest due — resulting in the SHORTFALL being added to the loan principal, increasing the balance over time; rare in modern QM lending but historically common in option ARMs that contributed to the 2008 financial crisis; substantially banned in Qualified Mortgages","Pays off faster","Is FHA-insured","Has no payments at all"],
   "correctAnswer":0,
   "explanation":"NEGATIVE AMORTIZATION occurs when monthly payments are LESS than the interest due — resulting in the SHORTFALL being added to the loan principal, INCREASING the balance over time. The borrower ends up owing MORE than they originally borrowed despite making payments. Historically common in: (1) PAYMENT OPTION ARMs (giving borrowers multiple payment choices, including some below interest-only); (2) GRADUATED PAYMENT MORTGAGES; (3) certain reverse mortgages. After contributing to the 2008 crisis, negative amortization features are substantially banned in QUALIFIED MORTGAGES — and remain rare in modern residential lending. Dodd-Frank and CFPB rules now require ability-to-repay underwriting based on fully-amortizing payments at the fully-indexed rate."},

  {"id":"re-nat-525","domain":"Financing","type":"single-choice",
   "question":"A 'BALLOON' mortgage:",
   "choices":["Bursts at random","Has higher rates","Is a federal grant","Has SCHEDULED MONTHLY PAYMENTS based on a LONGER amortization period (often 30 years), but the entire remaining balance becomes DUE in a single 'balloon' payment at an EARLIER stated maturity (often 5, 7, or 10 years); borrower typically must refinance or sell to make the balloon payment. Now restricted under Qualified Mortgage rules in many cases"],
   "correctAnswer":3,
   "explanation":"Balloon mortgages combine LOW MONTHLY PAYMENTS (based on a longer amortization period — typically 30 years) with a SHORTER MATURITY DATE (typically 5, 7, or 10 years). At maturity, the borrower owes the REMAINING BALANCE as a single 'balloon' payment. Borrowers typically must REFINANCE or SELL to make the balloon. Risks: (1) refinancing may not be available if credit deteriorates; (2) home value may decrease; (3) interest rates may rise. Now: (1) RESTRICTED in QM rules (limited to rural-lender exceptions for borrowers in underserved areas); (2) RARE in current residential lending; (3) MORE COMMON in commercial real estate where the borrower expects to sell or refinance before maturity."},

  {"id":"re-nat-526","domain":"Financing","type":"single-choice",
   "question":"Cash-out refinance maximum LTV ratios are typically:",
   "choices":["Unlimited","100% in all cases","LOWER than for purchase mortgages — typically 80% LTV (some programs allow 85%) for owner-occupied 1-unit properties; tighter for second homes, investment properties, and multi-unit; reflecting the higher risk of cash-out refinances vs. purchase loans","Higher than for purchase mortgages"],
   "correctAnswer":2,
   "explanation":"Cash-out refinance LTV ratios are TIGHTER than for purchase loans because they're considered HIGHER RISK: (1) The borrower is taking cash out (potentially worsening their financial position rather than improving); (2) The property's appraised value is the only collateral cushion; (3) HISTORICALLY HIGHER DEFAULT RATES than purchase loans. Typical maximums: (a) OWNER-OCCUPIED 1-UNIT: 80% LTV (some programs allow 85%); (b) SECOND HOMES: 75% LTV; (c) INVESTMENT PROPERTIES: 70-75% LTV; (d) MULTI-UNIT PROPERTIES: 70-75% LTV. Borrowers wanting more equity access may need to combine the refinance with a HELOC for the excess. Reserves and credit requirements are also typically tighter."},

  {"id":"re-nat-527","domain":"Financing","type":"single-choice",
   "question":"REVERSE MORTGAGE consumer protections include:",
   "choices":["MANDATORY HUD-APPROVED COUNSELING before loan application; AGE/RESIDENCE eligibility (typically 62+ owner-occupied); LOAN AMOUNTS capped at the appraised value (with adjustments); LATE-IN-LIFE protections for surviving non-borrower spouses; FHA insurance on HECMs to protect the borrower from negative-equity scenarios; and SUBSTANTIAL DISCLOSURE requirements","No consumer protections","Federal preemption of state laws","Mandatory federal repayment"],
   "correctAnswer":0,
   "explanation":"Reverse mortgage consumer protections are extensive due to the elderly demographic and the potential for confusion or exploitation: (1) MANDATORY HUD-APPROVED COUNSELING — before any loan application, the borrower must complete HUD-approved counseling and receive a certificate; (2) AGE/RESIDENCE ELIGIBILITY — typically 62+ owner-occupied for HECM; (3) LOAN AMOUNTS capped at appraised value with adjustments; (4) LATE-IN-LIFE PROTECTIONS — surviving non-borrower spouses have specific protections under federal rules; (5) FHA INSURANCE on HECMs — protects the borrower from negative-equity scenarios (the borrower never owes more than the property is worth); (6) SUBSTANTIAL DISCLOSURE REQUIREMENTS at multiple points; (7) ANTI-FRAUD PROVISIONS. Despite these protections, reverse mortgage scams remain a problem — particularly involving aggressive marketing and unsuitable advice."},

  {"id":"re-nat-528","domain":"Financing","type":"single-choice",
   "question":"Foreclosure timelines vary widely. Generally:",
   "choices":["NON-JUDICIAL foreclosure (using power-of-sale clauses in deeds of trust) is typically FASTER (often 3-6 months) and uses sheriff/trustee auctions outside the court system; JUDICIAL foreclosure (filed lawsuit, court judgment) is typically SLOWER (often 6-18+ months) due to court procedures, scheduling, and any contested defenses; some states allow only judicial foreclosure, others allow both","Always the same speed","Federal court only","Always under 30 days"],
   "correctAnswer":0,
   "explanation":"Foreclosure timelines vary by: (1) STATE LAW — some states require judicial foreclosure (Florida, New York, New Jersey, Illinois — slow), others allow non-judicial (Texas, California, Arizona, Nevada — faster); (2) PROCEDURE — non-judicial uses sheriff or trustee auctions outside court (3-6 months typical), judicial requires lawsuit, court judgment, and sheriff's sale (6-18+ months typical); (3) CONTESTED CASES — slower when borrower contests; (4) STATUTORY DELAYS — notice periods, redemption periods, cure periods. PRACTICAL IMPACT: shorter timelines benefit lenders but provide less time for borrowers to cure or pursue alternatives; longer timelines protect borrowers but cost lenders more in carrying costs and depreciation."},

  # ── Real Estate Calculations (5) ────────────────────────────────────────
  {"id":"re-nat-529","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A loan has a monthly P&I payment of $1,500. If the interest portion of the FIRST payment is $1,000, what is the principal portion?",
   "choices":["$1,500","$500 — Principal portion = Total Payment − Interest Portion = $1,500 − $1,000 = $500","$1,000","$2,500"],
   "correctAnswer":1,
   "explanation":"Step 1 — Basic amortization: Principal Portion = Total Payment − Interest Portion.\nStep 2 — Apply: $1,500 − $1,000 = $500 principal in the first payment.\nThis is the foundational amortization calculation. In subsequent months, the principal portion increases (as the outstanding balance decreases, less interest accrues) and the interest portion decreases — but the total monthly P&I remains constant. Over 30 years, the cumulative principal paid equals the original loan amount, and the cumulative interest paid is the lender's total return."},

  {"id":"re-nat-530","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A seller agrees to a $5,000 closing cost concession to help the buyer cover expenses. The buyer's lender will allow seller concessions up to 3% of the purchase price. On a $300,000 purchase, the seller's concession of $5,000:",
   "choices":["Exceeds the lender's limit","Is within the limit (3% of $300,000 = $9,000) — the concession is properly handled at closing as a credit reducing the buyer's net cash to close. The amount is documented on the Closing Disclosure (Section H — concession from seller to buyer)","Is invalid","Doubles to $10,000"],
   "correctAnswer":1,
   "explanation":"Step 1 — calculate the lender's concession cap: 3% × $300,000 = $9,000.\nStep 2 — the proposed $5,000 concession is WITHIN the lender's $9,000 limit.\nStep 3 — the concession is properly documented in the contract and at closing as a credit reducing the buyer's net cash to close. The amount appears on the Closing Disclosure (typically Section H — concession from seller to buyer).\nIMPORTANT: Lender concession limits vary by program (FHA, VA, conventional). Concessions ABOVE the lender's limit are sometimes treated as a 'sales price adjustment' (reducing the value the lender uses for LTV), so structuring the concession properly matters."},

  {"id":"re-nat-531","domain":"Real Estate Calculations","type":"single-choice",
   "question":"An investor purchased a rental property for $250,000 (including $50,000 land value, $200,000 building). They've taken $40,000 in depreciation deductions over the holding period. Now they sell for $325,000. Their adjusted basis is:",
   "choices":["$210,000","$290,000","$250,000","$210,000 — Adjusted Basis = Original Cost − Depreciation Taken. $250,000 − $40,000 = $210,000. (Land doesn't depreciate, so depreciation reduces only the building portion of basis, but the result is the same: total basis reduced by $40,000.)"],
   "correctAnswer":3,
   "explanation":"Step 1 — Adjusted Basis = Original Cost Basis − Depreciation Taken.\nStep 2 — Apply: $250,000 − $40,000 = $210,000.\nStep 3 — On sale, the GAIN is: Sale Price − Adjusted Basis = $325,000 − $210,000 = $115,000.\nOf this $115,000 gain, $40,000 is DEPRECIATION RECAPTURE (taxed at up to 25% federal rate) and $75,000 is long-term capital gain (taxed at up to 20%). Note: only the BUILDING depreciates, not LAND ($50,000 of original cost is land — non-depreciable). Standard depreciation period for residential rental is 27.5 years; for commercial, 39 years."},

  {"id":"re-nat-532","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A homeowner in the 24% federal tax bracket has $15,000 of mortgage interest deductible for the year. Their approximate federal tax savings from the interest deduction is:",
   "choices":["$3,600 — Tax Savings = Deduction × Marginal Tax Rate = $15,000 × 0.24 = $3,600. (Assumes they're using itemized deductions vs. the standard deduction; the actual savings depend on what other itemized deductions they have)","$1,800","$5,400","$15,000"],
   "correctAnswer":0,
   "explanation":"Step 1 — Tax Savings = Deduction × Marginal Tax Rate.\nStep 2 — Apply: $15,000 × 0.24 = $3,600.\nNote 1: This assumes the taxpayer is using ITEMIZED deductions (rather than the standard deduction); if their total itemized deductions don't exceed the standard deduction, they'd use the standard deduction and not benefit from the mortgage interest deduction at all. For 2025+ standard deductions are around $15,000 single, $30,000 married joint — high enough that many homeowners no longer itemize.\nNote 2: The 'marginal' rate is the rate on the LAST dollar earned. The actual savings depend on whether the deduction pushes income into a lower bracket overall."},

  {"id":"re-nat-533","domain":"Real Estate Calculations","type":"single-choice",
   "question":"Comparable Sales Analysis: three recent comparable properties sold at cap rates of 7.5%, 8.0%, and 8.2%. The subject property has comparable characteristics. The appraiser is likely to use a 'derived' cap rate near:",
   "choices":["5%","8% — appraisers typically use the AVERAGE or MEDIAN of recent comparable cap rates (with adjustments for property-specific risk factors); here the median is 8.0% and the average is approximately 7.9% — both pointing to a derived cap rate around 8%","12%","Cannot be determined"],
   "correctAnswer":1,
   "explanation":"Step 1 — calculate the median and average of the comparable cap rates:\n• Median (middle value): 8.0%\n• Average: (7.5% + 8.0% + 8.2%) / 3 = 23.7% / 3 = 7.9%\nStep 2 — appraiser typically uses the MEDIAN, AVERAGE, or weighted average based on comparability — adjusting for property-specific risk factors (location, age, tenant credit, lease term, etc.).\nStep 3 — derived cap rate is likely around 8% for this subject.\nThis 'derived cap rate' is then used in the income approach: Subject Value = Subject NOI ÷ Derived Cap Rate. The cap rate derivation is critical — small differences in cap rate produce large differences in derived value, so appraisers carefully analyze and document their comparable selection and adjustments."},

  # ── Property Ownership (4) ──────────────────────────────────────────────
  {"id":"re-nat-534","domain":"Property Ownership","type":"single-choice",
   "question":"A 'COMMON INTEREST COMMUNITY' (CIC) includes any planned community where owners have:",
   "choices":["No common interests","Pure fee simple only","INDIVIDUAL OWNERSHIP of their unit (or lot) PLUS MEMBERSHIP in an association that owns and manages COMMON AREAS — this category includes condominiums, planned unit developments (PUDs), cooperatives (co-ops), and similar structures; owners pay assessments to the association for common-area maintenance, insurance, and reserves","Federal land grants only"],
   "correctAnswer":2,
   "explanation":"COMMON INTEREST COMMUNITY (CIC) is the umbrella term for planned communities where owners have both individual ownership and association membership. Categories: (1) CONDOMINIUM — fee simple ownership of an individual unit + undivided fractional interest in common elements; (2) PLANNED UNIT DEVELOPMENT (PUD) — fee simple ownership of a separate lot + membership in HOA that owns common areas; (3) COOPERATIVE (CO-OP) — shares in a corporation that owns the building + proprietary lease to occupy unit; (4) TIME-SHARE — fractional or interval ownership for specified time periods; (5) HOMEOWNERS' ASSOCIATIONS (HOAs) of various types. Owners pay ASSESSMENTS for common-area maintenance, insurance, reserves, and amenities."},

  {"id":"re-nat-535","domain":"Property Ownership","type":"single-choice",
   "question":"A TIME-SHARE typically gives the owner:",
   "choices":["Year-round ownership","No ownership at all","Fee simple ownership","Either FEE-SIMPLE INTERVAL OWNERSHIP of the property for specified time periods each year, OR (in some structures) RIGHT-TO-USE membership for time at the property; documentation, taxes, transfer rights, and resale value vary significantly. Time-shares are heavily regulated and subject to specific consumer-protection rules (right of rescission, mandatory disclosures, etc.)"],
   "correctAnswer":3,
   "explanation":"Time-shares structures: (1) FEE-SIMPLE INTERVAL — actual ownership of the property for specified time periods each year (e.g., weeks 25-26); the owner has a recorded deed for their interval, can be inherited, sold, or transferred; pays property taxes prorated; (2) RIGHT-TO-USE — membership giving the right to use property for time periods, but no actual ownership; typically expires after a stated period (e.g., 30 years); often easier to transfer/cancel but less valuable. REGULATION: Time-shares are heavily regulated under state-specific consumer-protection laws — typically including: (a) MANDATORY RESCISSION PERIODS (typically 3-15 days after purchase); (b) MANDATORY PUBLIC OFFERING STATEMENT or 'public report'; (c) DISCLOSURE of restrictions, costs, and resale challenges. Time-share resale values are often poor."},

  {"id":"re-nat-536","domain":"Property Ownership","type":"single-choice",
   "question":"A condominium owner pays MONTHLY ASSESSMENTS to the condo association. These assessments typically cover:",
   "choices":["MAINTENANCE of common elements (hallways, roof, exterior, landscaping, amenities), shared utilities, master insurance on common areas and building exterior, association management, RESERVES for major capital expenses (e.g., roof replacement, elevator replacement), and operating expenses; assessments cannot cover the owner's personal expenses inside their individual unit","The buyer's individual taxes","Pure investment returns","Random expenses"],
   "correctAnswer":0,
   "explanation":"Monthly condominium assessments cover: (1) COMMON ELEMENT MAINTENANCE — hallways, roofs, exterior, landscaping, pools, gyms, lobbies; (2) SHARED UTILITIES — water, sewage, sometimes electricity for common areas; (3) MASTER INSURANCE — covers common elements and building exterior (owners need separate 'HO-6' policies for interior of their units); (4) ASSOCIATION MANAGEMENT — professional management company fees, board expenses; (5) RESERVES — funded over time for major capital expenses (roof replacement, elevator replacement, HVAC, etc.); (6) OPERATING EXPENSES — utilities, repairs, vendor contracts. Assessments DO NOT cover the owner's personal expenses inside their individual unit (those are the owner's responsibility). SPECIAL ASSESSMENTS may be imposed for unexpected major expenses beyond regular assessments."},

  {"id":"re-nat-537","domain":"Property Ownership","type":"single-choice",
   "question":"In a cooperative ('co-op') housing structure:",
   "choices":["Each resident owns their unit in fee simple","All residents own equal shares","A CORPORATION owns the entire building and underlying land; RESIDENTS OWN SHARES OF THE CORPORATION + a PROPRIETARY LEASE giving them the exclusive right to occupy a specific unit; transfers typically require BOARD APPROVAL of the new buyer (a feature unique to co-ops vs. condos); maintenance fees paid by residents cover the corporation's expenses","Residents are tenants of a public agency"],
   "correctAnswer":2,
   "explanation":"Cooperative ('co-op') housing structure: (1) The CORPORATION owns the entire building and underlying land — owning everything as a single legal entity; (2) RESIDENTS OWN SHARES in the corporation (their share allocation typically reflects the value/size of their unit); (3) RESIDENTS receive a PROPRIETARY LEASE giving them the exclusive right to occupy their specific unit; (4) TRANSFERS typically require BOARD APPROVAL of the new buyer — a unique feature giving the corporation/board control over who can become a resident (which has been controversial in fair housing contexts when boards have applied discriminatory standards); (5) MAINTENANCE FEES paid by residents cover the corporation's expenses (mortgage, taxes, maintenance, etc.). Co-ops are most common in New York City and a few other major metropolitan areas."},

  # ── Transfer of Title (4) ───────────────────────────────────────────────
  {"id":"re-nat-538","domain":"Transfer of Title","type":"single-choice",
   "question":"A grantor conveys property via WARRANTY DEED — but at the time of conveyance, the grantor has no actual title. Later, the grantor acquires title. Under the DOCTRINE OF ESTOPPEL BY DEED (after-acquired title):",
   "choices":["The title remains with the original grantor","The grantee has no rights","TITLE THAT THE GRANTOR LATER ACQUIRES PASSES AUTOMATICALLY TO THE GRANTEE — the grantor is 'ESTOPPED' from denying that title passed via the prior warranty deed; the doctrine applies to deeds containing warranties (general warranty, special warranty, grant deeds) but NOT typically to quitclaim deeds","Both parties must renegotiate"],
   "correctAnswer":2,
   "explanation":"DOCTRINE OF ESTOPPEL BY DEED (also called after-acquired title): When a grantor conveys property they don't own via a deed containing TITLE WARRANTIES, and later acquires actual title — that subsequently-acquired title PASSES AUTOMATICALLY to the prior grantee. The grantor is ESTOPPED (legally prevented) from later denying that title passed under the original deed. KEY LIMITATIONS: (1) only applies to deeds with WARRANTIES (general warranty, special warranty, grant deeds); (2) does NOT typically apply to QUITCLAIM deeds (which make no warranty of title); (3) requires the original deed to have purported to convey something the grantor didn't have. The doctrine prevents inequity and protects grantees who relied on warranty representations."},

  {"id":"re-nat-539","domain":"Transfer of Title","type":"single-choice",
   "question":"A family inherits a property from their parent who died without a will. Several heirs disagree about whether to sell the property. Their options include:",
   "choices":["Only sell to the eldest heir","No options","Federal court forced sale","One heir can file a PARTITION action seeking court-ordered division (PHYSICAL division if the property can be divided into separate parcels) or PARTITION BY SALE (forced sale and distribution of proceeds); alternatively, heirs can negotiate a BUYOUT arrangement among themselves, or all sell jointly with proceeds divided per their respective ownership shares"],
   "correctAnswer":3,
   "explanation":"When heirs to a property cannot agree on its disposition, options include: (1) PARTITION ACTION — one heir files in court seeking division. Two types: PARTITION IN KIND (physical division into separate parcels — only possible if practical); PARTITION BY SALE (forced sale with proceeds distributed per ownership shares — more common); (2) BUYOUT — one heir purchases the interests of other heirs at a negotiated price; (3) JOINT SALE — all heirs agree to sell, dividing proceeds per ownership shares; (4) RENTAL OR USE ARRANGEMENT — agree to rent the property and divide income, or share use. PARTITION is the legal mechanism that resolves disputes — but it's often the least efficient outcome (forcing a sale at market or below market, plus litigation costs). HEIR PROPERTY (where multiple co-owners hold over generations) is a major source of property loss in some communities."},

  {"id":"re-nat-540","domain":"Transfer of Title","type":"single-choice",
   "question":"PROBATE is the court-supervised process for administering a decedent's estate. NON-PROBATE transfers include:",
   "choices":["TRUSTS — property held in a trust passes per the trust's terms without probate; PAYABLE-ON-DEATH / TRANSFER-ON-DEATH accounts and deeds (in states allowing them) — pass directly to the named beneficiary; PROPERTY HELD IN JOINT TENANCY WITH RIGHT OF SURVIVORSHIP — passes automatically to the surviving joint tenant; LIFE INSURANCE — paid to named beneficiary","Only intestate succession","Only individual ownership","Federal estate alone"],
   "correctAnswer":0,
   "explanation":"NON-PROBATE TRANSFERS bypass the court probate process — assets pass according to the specific arrangement, not the will (or intestate succession). Common examples: (1) TRUSTS — property held in a properly funded living trust passes per the trust's terms; the trust avoids probate; (2) PAYABLE-ON-DEATH (POD) / TRANSFER-ON-DEATH (TOD) — bank accounts, investment accounts, vehicles, and (in states allowing them) TOD DEEDS for real estate; the named beneficiary inherits directly; (3) JOINT TENANCY WITH RIGHT OF SURVIVORSHIP — passes automatically to the surviving joint tenant; tenancy by the entirety similarly bypasses probate; (4) LIFE INSURANCE — pays to named beneficiary; (5) RETIREMENT ACCOUNTS with named beneficiaries. Estate planning typically aims to minimize probate (which can be slow, expensive, and public)."},

  {"id":"re-nat-541","domain":"Transfer of Title","type":"single-choice",
   "question":"A potential heir signs a QUITCLAIM deed releasing their interest in a property to the other heirs. The effect is to:",
   "choices":["Acquire the entire property","RELEASE the signing heir's potential interest — useful when there's uncertainty about whether the signer has any interest, when the family wants to settle ownership amicably, or to clear potential title clouds in advance. The quitclaim does not convey what the signer doesn't have; if they had no interest, the quitclaim conveys nothing","Block other heirs","Create new interests"],
   "correctAnswer":1,
   "explanation":"A quitclaim from a potential heir is a useful title-clearing tool in family situations: (1) The signer RELEASES whatever interest they may have (with no warranty that they had any interest); (2) If the signer had no actual interest, the quitclaim conveys nothing — but it cures the uncertainty and prevents later claims; (3) Commonly used when an estate is being settled and family members want clarity about ownership; or when a former spouse, ex-partner, or estranged family member's potential claim might cloud title; (4) The signer must be of legal capacity and act voluntarily — quitclaims under duress or undue influence may be challenged. The instrument is recorded in the public records to provide notice that the signer has released their interest."},

  # ── Valuation and Market Analysis (3) ───────────────────────────────────
  {"id":"re-nat-542","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"In RECONCILIATION of the three approaches to value (sales comparison, cost, income), the appraiser:",
   "choices":["Always averages all three approaches","Always uses the cost approach","Always uses the income approach","EVALUATES the relative reliability of each approach for the SUBJECT PROPERTY and weighs them accordingly to arrive at the FINAL OPINION OF VALUE — typical weighting: SALES COMPARISON for owner-occupied residential, INCOME for investment property, COST for special-purpose/new construction; the appraiser explicitly explains their reasoning in the reconciliation"],
   "correctAnswer":3,
   "explanation":"RECONCILIATION is the final stage of the appraisal process. The appraiser: (1) REVIEWS the indicators of value from each applicable approach; (2) ASSESSES the RELATIVE RELIABILITY of each approach for the specific subject property (market activity in comparables, accuracy of cost data, reliability of income projections); (3) WEIGHS the approaches accordingly — typical patterns: (a) SALES COMPARISON typically gets the most weight for OWNER-OCCUPIED RESIDENTIAL property; (b) INCOME APPROACH typically gets the most weight for INCOME-PRODUCING INVESTMENT property; (c) COST APPROACH typically gets the most weight for SPECIAL-PURPOSE PROPERTIES (schools, churches, government buildings) and NEW CONSTRUCTION; (4) ARRIVES at a FINAL OPINION of value. The appraiser explicitly EXPLAINS THEIR REASONING — not just an unexplained number."},

  {"id":"re-nat-543","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"An ADJUSTMENT GRID in the sales comparison approach:",
   "choices":["Lists property prices only","Records geographic locations","Tracks tax history","Is a SYSTEMATIC TABLE used by appraisers to compare the subject property to comparable sales — listing each property's characteristics in columns and making numeric adjustments (additions or subtractions) for differences (e.g., square footage, lot size, condition, features); the adjusted sale prices indicate value ranges for the subject property"],
   "correctAnswer":3,
   "explanation":"The ADJUSTMENT GRID is a fundamental tool in the sales comparison approach: (1) FORMAT: typically a table with the SUBJECT in one column and 3-5 COMPARABLES in adjacent columns; rows for each comparable characteristic (sale date, location, size, bedrooms, baths, condition, features); (2) ADJUSTMENTS: for each characteristic where the COMPARABLE differs from the subject, the appraiser MAKES A DOLLAR ADJUSTMENT (positive or negative) to the comparable's sale price. If a comp has a feature the subject lacks, ADJUST DOWNWARD; if the subject has something the comp lacks, ADJUST UPWARD. (Adjustments are made TO the comparables, not the subject); (3) ADJUSTED PRICE = comp's actual sale price ± adjustments; (4) RESULT: adjusted prices indicate a value range for the subject — the appraiser reconciles these to a final indicator of value."},

  {"id":"re-nat-544","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"In comparable sales analysis, TIME ADJUSTMENTS account for changes in market conditions between the comparable sale date and the subject's effective valuation date. Typically:",
   "choices":["Appraisers extract a TIME-ADJUSTMENT factor from market trends — analyzing how prices have changed in similar properties over the relevant period (e.g., 0.5% per month appreciation, 1% per month depreciation); applies a corresponding percentage adjustment to each comparable's sale price; older comparables receive larger adjustments","No time adjustments","Federal regulation sets adjustments","Time adjustments are forbidden"],
   "correctAnswer":0,
   "explanation":"TIME ADJUSTMENTS (sometimes called 'market condition adjustments') account for the changing market between comparable sale dates and the subject's effective valuation date. Method: (1) EXTRACT a time-adjustment factor from market trends — typically expressed as percentage per month or per year (e.g., 'prices have been appreciating about 0.5% per month' or 'the market has declined 6% over the past year'); (2) APPLY the corresponding percentage adjustment to each comparable's sale price (older sales get larger adjustments); (3) RESULT: each comparable's adjusted price reflects what it would have sold for IF the sale had occurred at the subject's effective valuation date. Time adjustments can be substantial in rapidly changing markets — particularly noticeable during 2020-2022 rapid appreciation and post-2022 cooling. Appraisers must clearly document and justify their adjustment factors."},

  # ── Property Disclosures (3) ────────────────────────────────────────────
  {"id":"re-nat-545","domain":"Property Disclosures","type":"single-choice",
   "question":"With respect to roof condition, sellers should disclose:",
   "choices":["Nothing about the roof","Only the color","ANY KNOWN issues — age (typical residential asphalt shingles last 15-30 years), recent leaks (current or repaired), roof replacements done during ownership, any pending or recent insurance claims, and known defects; this matters because roofs are major property components subject to costly near-term replacement, and insurance availability/pricing is significantly affected by roof age and condition","Only when asked"],
   "correctAnswer":1,
   "explanation":"ROOF DISCLOSURE typically includes: (1) ROOF AGE — most insurance carriers require disclosure of roof age and may not renew coverage on roofs near end of life; (2) RECENT LEAKS — current or repaired leaks, water damage history; (3) ROOF REPLACEMENT — partial or full replacements during ownership, who did the work, warranty status; (4) INSURANCE CLAIMS — any pending or recent claims (these become part of the property's CLUE Report — Comprehensive Loss Underwriting Exchange — affecting future insurance availability/pricing); (5) KNOWN DEFECTS — sagging, missing shingles, flashing problems, etc. ROOF MATTERS: (a) replacement costs $5,000-50,000+ depending on size and material; (b) insurance carriers increasingly refuse to cover or non-renew older roofs; (c) buyers typically prioritize roof condition in inspections."},

  {"id":"re-nat-546","domain":"Property Disclosures","type":"single-choice",
   "question":"HVAC (heating, ventilation, air conditioning) systems should be disclosed:",
   "choices":["Only after closing","Only by ZIP code","WITH information about age (typical lifespans: gas furnace 15-20 years, AC condenser 12-15 years, heat pump 10-15 years), recent service/repairs, any defects or operational issues, warranty status (if any), and refrigerant type (R-22 is phased out, R-410A is being phased out 2025+); HVAC replacement is expensive and a common buyer concern","Optional"],
   "correctAnswer":2,
   "explanation":"HVAC DISCLOSURE typically includes: (1) AGE — typical lifespans: gas furnace 15-20 years, AC condenser 12-15 years, heat pump 10-15 years; replacement cost is significant (often $5,000-20,000+ depending on system); (2) RECENT SERVICE/REPAIRS — service history, any known issues; (3) DEFECTS — including inability to maintain temperature, unusual noise, refrigerant leaks; (4) WARRANTY STATUS — original warranty (often 5-10 years on parts), service contracts; (5) REFRIGERANT TYPE — R-22 (Freon) was phased out for new equipment in 2010 and recharging it has become expensive; R-410A is being phased out 2025+; newer systems use R-454B or R-32 (more efficient and lower global warming potential). HVAC age and condition affects: insurance, comfort, energy costs, and buyer perception."},

  {"id":"re-nat-547","domain":"Property Disclosures","type":"single-choice",
   "question":"With respect to FOUNDATION ISSUES (cracks, settling, water intrusion), sellers should:",
   "choices":["Not disclose unless asked","DISCLOSE any known foundation issues — including past repairs, current cracks, settling, water intrusion, drainage problems, and any structural engineering reports; foundation problems can SIGNIFICANTLY AFFECT property value and structural integrity; failure to disclose can result in misrepresentation claims, rescission rights, and damages","Mention only minor cosmetic cracks","Federal preemption"],
   "correctAnswer":1,
   "explanation":"FOUNDATION ISSUES are typically MATERIAL FACTS requiring disclosure: (1) KNOWN CRACKS — both COSMETIC (paint hairlines, minor settling) and STRUCTURAL (active movement, large gaps, displacement); (2) PAST REPAIRS — any structural work, underpinning, drainage modifications; (3) WATER INTRUSION — basement leaks, foundation water damage; (4) DRAINAGE PROBLEMS — poor drainage contributing to foundation issues; (5) STRUCTURAL ENGINEERING REPORTS — any inspections, evaluations, or recommendations. IMPACT: foundation problems can affect (a) STRUCTURAL INTEGRITY, (b) PROPERTY VALUE (10-25% or more reduction depending on severity), (c) INSURANCE COVERAGE, (d) FUTURE REPAIR COSTS ($5,000-$100,000+ for major work). Failure to disclose known foundation issues can result in: misrepresentation claims, rescission rights, damages, license discipline."},

  # ── Land Use Controls and Regulations (2) ───────────────────────────────
  {"id":"re-nat-548","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"Common ZONING CATEGORIES in U.S. municipalities include:",
   "choices":["RESIDENTIAL (R-1, R-2, R-3 typically indicate single-family, duplex, multi-family; further subcategories common), COMMERCIAL (C-1, C-2, etc. — neighborhood, regional, etc.), INDUSTRIAL (I-1, I-2 — light vs. heavy industrial), AGRICULTURAL, MIXED-USE, and various OVERLAY DISTRICTS (historic, environmental, special purpose); each category has specific uses by right, conditional uses, prohibited uses, and dimensional standards (setbacks, height, lot coverage, FAR)","Only one category exists","Only federal categories","Random labels"],
   "correctAnswer":0,
   "explanation":"Zoning categories typically include: (1) RESIDENTIAL — R-1 (single-family, lowest density), R-2 (duplex), R-3 (multi-family), R-4 (high-density apartments); within each category, lot size minimums and dwelling unit limitations are specified; (2) COMMERCIAL — C-1 (neighborhood scale, limited intensity), C-2 (regional scale, higher intensity), C-3 (downtown/highest intensity); (3) INDUSTRIAL — I-1 (light industrial, business parks), I-2 (heavy industrial, manufacturing); (4) AGRICULTURAL — typically very low density, farming; (5) MIXED-USE — combinations of residential, commercial, and sometimes other uses; (6) OVERLAY DISTRICTS — additional regulations layered on top of base zoning for historic preservation, environmental protection, flood plains, airport approaches, etc. Each category specifies: (a) USES BY RIGHT, (b) CONDITIONAL USES (requiring permits), (c) PROHIBITED USES, (d) DIMENSIONAL STANDARDS."},

  {"id":"re-nat-549","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"In zoning, 'PERMITTED USES' (allowed by right in a zone) and 'ACCESSORY USES' (subordinate uses related to the principal use) differ in that:",
   "choices":["They are the same","ACCESSORY USES are SUBORDINATE and INCIDENTAL to the principal permitted use of the property — typically allowed without separate approval. Examples: a home office in a residential zone (accessory to residential use), a parking area for a retail store (accessory to commercial use), an equipment storage shed for a farm (accessory to agricultural use). Accessory uses must remain truly subordinate and may be regulated for size, location, hours, etc.","Federal preemption","Accessory uses are prohibited"],
   "correctAnswer":1,
   "explanation":"In zoning, ACCESSORY USES are SUBORDINATE and INCIDENTAL to the principal permitted use of the property. Characteristics: (1) MUST BE INCIDENTAL — clearly subordinate to and related to the principal use; (2) MUST BE LOCATED on the same property as the principal use; (3) MUST NOT BECOME the dominant use. EXAMPLES: home office in a residential zone (accessory to residential use); detached garage; in-law unit (depending on zoning); home-based business (limited); parking area for a retail store; loading dock for an industrial use; equipment storage shed for a farm. REGULATION: accessory uses may be SUBJECT TO SPECIFIC LIMITS — size, location (typically rear yard), hours, signage, customer traffic, employees. Some accessory uses (like ACCESSORY DWELLING UNITS or 'granny flats') have become increasingly important for affordable housing and are subject to specific state and local rules."},

  # ── Leasing and Property Management (1) ─────────────────────────────────
  {"id":"re-nat-550","domain":"Leasing and Property Management","type":"single-choice",
   "question":"When a landlord breaches the implied warranty of habitability, the tenant's remedies typically include:",
   "choices":["The tenant must move out","Only criminal complaint","REPAIR-AND-DEDUCT (tenant fixes the issue and deducts the cost from rent — typically with statutory limits and procedures), RENT WITHHOLDING (depositing rent into a separate account, escrow, or court registry while the issue is addressed), LEASE TERMINATION (tenant may move out without breach), and DAMAGES (compensatory and sometimes statutory)","No remedies available"],
   "correctAnswer":2,
   "explanation":"TENANT REMEDIES for breach of the implied warranty of habitability vary by state but typically include: (1) REPAIR-AND-DEDUCT — tenant pays for the repair and deducts from rent, typically with: (a) prior written notice to landlord, (b) statutory limit on amount (often 1 month's rent), (c) reasonable repair costs only; (2) RENT WITHHOLDING — tenant deposits rent into a separate account, escrow, or court registry while the issue is addressed; varies by state — some require court order, others allow tenant action; (3) LEASE TERMINATION — tenant may move out without being in breach of the lease, may recover security deposit; (4) DAMAGES — compensatory damages for any actual harm caused; some states allow STATUTORY DAMAGES; (5) INJUNCTIVE RELIEF — court order requiring landlord to repair. Specific procedures vary by state and must be carefully followed."},
]

data.extend(new_qs)
Q.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"Written: {len(data)} questions")
