"""Real Estate National batch 13 — questions 601-650."""
import json, pathlib

Q = pathlib.Path("src/data/real-estate-national-questions.json")
data = json.loads(Q.read_text(encoding="utf-8"))

new_qs = [
  # ── Contracts (9) ───────────────────────────────────────────────────────
  {"id":"re-nat-601","domain":"Contracts","type":"single-choice",
   "question":"After a contract default, the parties dispute who is entitled to the earnest money. The broker holding the funds may protect themselves from liability by:",
   "choices":["Disbursing to whoever asks first","FILING AN INTERPLEADER ACTION — depositing the disputed funds with the court and asking the court to decide who is entitled to them; the broker is then dismissed from the dispute and the parties litigate ownership; this avoids the broker's liability for wrongful disbursement","Keeping the funds personally","Refunding to both parties simultaneously"],
   "correctAnswer":1,
   "explanation":"INTERPLEADER is a powerful tool for brokers (and other neutral parties) holding disputed funds. PROCESS: (1) The broker FILES an interpleader action in court, naming both disputing parties as defendants; (2) DEPOSITS the disputed funds WITH THE COURT; (3) Asks the court to DETERMINE who is entitled to the funds; (4) The broker is then DISMISSED from the dispute; (5) The disputing parties LITIGATE their claims to the funds. ADVANTAGES: (a) Protects the broker from WRONGFUL DISBURSEMENT liability; (b) Eliminates risk of bad faith claims by either party; (c) Lets the court (not the broker) make the difficult determination. ALTERNATIVES: many states allow brokers to retain disputed funds until a court order or written agreement of both parties — interpleader is when neither resolves naturally."},

  {"id":"re-nat-602","domain":"Contracts","type":"single-choice",
   "question":"A buyer is in default on a purchase contract. Before the seller can declare default and terminate the contract, the contract typically requires:",
   "choices":["Immediate termination","No notice","WRITTEN NOTICE TO THE BUYER specifying the alleged default and giving the buyer an OPPORTUNITY TO CURE within a stated period (often 7-30 days); failure to cure within the period allows the seller to declare default and pursue remedies; jumping to default without proper cure notice may waive the seller's right or invalidate the termination","Federal court approval"],
   "correctAnswer":2,
   "explanation":"DEFAULT CURE PROCEDURES are common in real estate contracts. STANDARD STEPS: (1) The non-breaching party identifies the alleged default; (2) DELIVERS WRITTEN NOTICE — specifying the breach and giving the breaching party an OPPORTUNITY TO CURE; (3) STATED CURE PERIOD — often 7-30 days, varying by contract; (4) IF CURED — the contract continues; (5) IF NOT CURED — the non-breaching party may declare default and pursue remedies. IMPORTANCE: (a) Required by most modern residential contracts; (b) Protects against premature termination; (c) Preserves the non-breaching party's rights — JUMPING TO DEFAULT without proper cure notice may waive the right or invalidate the termination. NOTICE REQUIREMENTS: typically must follow contract notice provisions exactly (form, content, delivery method)."},

  {"id":"re-nat-603","domain":"Contracts","type":"single-choice",
   "question":"A purchase contract for a condominium is contingent on HOA APPROVAL of the buyer. This contingency:",
   "choices":["No effect","Universal","Federal mandate","Allows the buyer to TERMINATE the contract and recover earnest money if the HOA REJECTS the buyer's application or imposes conditions unacceptable to the buyer; the buyer should COMPLETE the HOA application promptly to avoid waiving the contingency by inaction; HOAs typically review for board approval, financial qualifications, and rule compliance"],
   "correctAnswer":3,
   "explanation":"HOA APPROVAL CONTINGENCIES are common in condominium and co-op purchases — many associations have specific buyer approval processes. KEY ELEMENTS: (1) The HOA REVIEWS the buyer's application (financial qualifications, references, sometimes interview); (2) APPROVAL CRITERIA — varies by HOA but typically includes financial qualifications, no criminal history, references, intent to occupy or rent, rule compliance; (3) BUYER OBLIGATIONS — complete and submit the application promptly; (4) PROTECTIONS for the buyer — if HOA REJECTS or imposes UNACCEPTABLE CONDITIONS, the buyer can typically terminate and recover earnest money; (5) TIME LIMITS — contingency typically expires within a stated period (often 30-45 days). FAIR HOUSING IMPLICATIONS — HOAs cannot discriminate based on protected classes; complaints about disparate application of approval criteria are common in fair-housing enforcement."},

  {"id":"re-nat-604","domain":"Contracts","type":"single-choice",
   "question":"A mortgage's ACCELERATION CLAUSE typically allows the lender to:",
   "choices":["Reduce the interest rate","Force the borrower to refinance","Increase the loan amount","DECLARE THE ENTIRE LOAN BALANCE IMMEDIATELY DUE upon specified events of default — including failure to make payments, transfer of the property (via DUE-ON-SALE clause), failure to pay property taxes or insurance, or violation of other covenants in the mortgage; designed to protect the lender from continued risk after default and to enable foreclosure"],
   "correctAnswer":3,
   "explanation":"ACCELERATION CLAUSES are standard in modern mortgages. WHAT THEY DO: allow the lender to DECLARE THE ENTIRE LOAN BALANCE IMMEDIATELY DUE upon specified events of default. COMMON TRIGGERS: (1) FAILURE TO MAKE PAYMENTS — typically after a stated grace period and notice; (2) DUE-ON-SALE — transfer of the property without lender consent; (3) FAILURE TO PAY PROPERTY TAXES or insurance; (4) VIOLATION OF OTHER COVENANTS (waste, unauthorized renovations, environmental violations, etc.). PROCESS: (1) Lender provides written notice of acceleration; (2) Stated cure period (varies by state and loan type); (3) If not cured, lender can declare the entire balance due and initiate foreclosure. PROTECTIONS: borrowers have the right to NOTICE, opportunity to CURE (in most cases), and REINSTATEMENT rights even after acceleration (in many states)."},

  {"id":"re-nat-605","domain":"Contracts","type":"single-choice",
   "question":"A landowner discovers their neighbor has been openly using a 3-foot strip of the landowner's property for 25 years. The landowner sues for trespass. The neighbor's potential defense based on LACHES:",
   "choices":["Cannot be raised","Doesn't apply to real estate","Always succeeds","The doctrine of LACHES — an equitable defense based on UNREASONABLE DELAY in bringing a claim, combined with PREJUDICE to the defendant — could potentially be raised, though it would not give the neighbor title (that would require adverse possession). Laches is most relevant for equitable claims, not legal claims; can affect remedies but not necessarily eliminate the underlying claim"],
   "correctAnswer":3,
   "explanation":"The doctrine of LACHES is an EQUITABLE defense based on UNREASONABLE DELAY in bringing a claim, combined with PREJUDICE to the defendant. APPLICATION: (1) UNREASONABLE DELAY — the plaintiff knew (or should have known) of the claim but waited unreasonably long; (2) PREJUDICE — the delay has caused harm to the defendant (lost evidence, witnesses unavailable, changes in position, etc.); (3) MOST RELEVANT FOR EQUITABLE CLAIMS — not strictly legal claims; (4) CAN AFFECT REMEDIES — even if the underlying claim survives, courts may limit equitable remedies. IN THIS SCENARIO: laches could potentially limit equitable relief but does NOT give the neighbor title — that would require ADVERSE POSSESSION (which requires meeting specific elements including hostility/lack of permission for the statutory period). LACHES is typically a more limited defense than statute of limitations."},

  {"id":"re-nat-606","domain":"Contracts","type":"single-choice",
   "question":"The STATUTE OF LIMITATIONS for breach-of-contract claims in real estate transactions:",
   "choices":["Is uniform federal law","Doesn't apply to real estate","Eliminates all claims after one year","VARIES BY STATE — typically 3-10 years from the date of breach (or, under some states' 'discovery rules,' from when the breach was reasonably discoverable); fraudulent breaches typically have LONGER limitation periods or START FROM DISCOVERY; some states have specific statutes for real estate disputes; if claims expire, the underlying claim is generally lost"],
   "correctAnswer":3,
   "explanation":"STATUTES OF LIMITATIONS for real estate contract claims VARY SIGNIFICANTLY by state: (1) TYPICAL RANGE — 3-10 years from the date of breach; (2) WRITTEN CONTRACTS typically have longer limitation periods than oral contracts (e.g., 6 years for written, 3 years for oral in many states); (3) DISCOVERY RULE — many states allow the limitation period to start when the breach was reasonably discoverable (rather than when the breach occurred), especially for hidden defects; (4) FRAUDULENT BREACHES — typically have LONGER limitation periods or specific 'date of discovery' triggers; (5) SPECIFIC STATUTES — some states have specific real estate statute of limitations provisions; (6) EXPIRATION CONSEQUENCES — if claims expire, the UNDERLYING CLAIM IS GENERALLY LOST; courts will dismiss late-filed claims. PRACTICAL: parties should consult specific state law and document claims early to preserve rights."},

  {"id":"re-nat-607","domain":"Contracts","type":"single-choice",
   "question":"A commercial real estate purchase contract is contingent on the BUYER OBTAINING LENDER APPROVAL of the proposed financing. This contingency:",
   "choices":["Eliminates the financing","Universal","Federal preemption","Allows the buyer to TERMINATE THE CONTRACT and recover earnest money if the LENDER REFUSES to approve the loan or imposes unacceptable terms (despite the buyer's good-faith application efforts); the buyer must typically APPLY FOR FINANCING within a stated period (often 5-15 days after contract); failure to apply timely may waive the contingency"],
   "correctAnswer":3,
   "explanation":"FINANCING CONTINGENCIES are common in real estate. KEY ELEMENTS: (1) BUYER MUST APPLY FOR FINANCING within a stated period (often 5-15 days after contract); (2) BUYER MUST PURSUE FINANCING in good faith — making reasonable efforts to obtain approval; (3) IF LENDER REFUSES — the buyer can typically terminate the contract and recover earnest money; (4) IF LENDER IMPOSES UNACCEPTABLE TERMS — depending on the contingency language (rate range, type, points), buyer may also terminate; (5) WAIVER — failure to deliver timely notice of contingency exercise often constitutes WAIVER, leaving the buyer obligated to perform; (6) DOCUMENTATION — the buyer should KEEP RECORDS of application efforts, lender communications, and rejection details. The contingency protects buyers from being forced to perform when financing isn't available — but requires PROACTIVE compliance with contract requirements."},

  {"id":"re-nat-608","domain":"Contracts","type":"single-choice",
   "question":"CONCURRENT CONDITIONS in a real estate contract refer to:",
   "choices":["RECIPROCAL OBLIGATIONS that must be performed AT THE SAME TIME — typically the seller's obligation to convey title and the buyer's obligation to pay; neither party must perform without the other simultaneously performing; this is fundamental to real estate closings, where the deed is delivered as the purchase funds are transferred","Random terms","Optional conditions","Federal requirements"],
   "correctAnswer":0,
   "explanation":"CONCURRENT CONDITIONS are RECIPROCAL OBLIGATIONS that must be performed AT THE SAME TIME. In real estate: (1) THE SELLER'S obligation to CONVEY TITLE (via signed and notarized deed); (2) THE BUYER'S obligation to PAY THE PURCHASE PRICE (typically in immediately-available funds — wire, cashier's check); (3) These are TRADITIONALLY VIEWED AS CONCURRENT — neither party must perform without the other simultaneously performing. PRACTICAL IMPLICATION: at closing, the parties exchange performance simultaneously — typically through an escrow process: (a) Buyer's funds are placed in escrow before closing; (b) Seller's signed deed is placed in escrow; (c) At closing, the funds are transferred to the seller AND the deed is recorded transferring title to the buyer — virtually simultaneously. This protects both parties from one performing and the other not."},

  {"id":"re-nat-609","domain":"Contracts","type":"single-choice",
   "question":"A dispute over a real estate contract has been settled by the parties. They want to document the settlement to prevent further claims:",
   "choices":["No documentation needed","SIGN A RELEASE OR SETTLEMENT AGREEMENT — clearly identifying the parties, the underlying dispute, the consideration paid (if any), the specific claims being released, and any continuing obligations or restrictions; well-drafted releases prevent future claims arising from the same facts and provide certainty for all parties","Verbal agreement is enough","Wait for federal court"],
   "correctAnswer":1,
   "explanation":"DOCUMENTING SETTLEMENT AGREEMENTS is essential to prevent future disputes. STANDARD COMPONENTS: (1) IDENTIFICATION — clearly identify all parties (legal names, addresses); (2) BACKGROUND/RECITALS — describe the underlying dispute; (3) CONSIDERATION — what each party is providing (typically: money paid, claims released, ongoing obligations); (4) RELEASE CLAUSE — specific claims being released; typically includes broad language releasing 'all claims known or unknown' arising from specific underlying facts; (5) NON-DISCLOSURE provisions (if confidentiality is desired); (6) NON-DISPARAGEMENT clauses (sometimes); (7) ATTORNEYS' FEES — typically each party bears their own; (8) SIGNATURES of all parties (and counsel if represented). WELL-DRAFTED RELEASES prevent future claims arising from the same facts and provide certainty for all parties. POORLY-DRAFTED OR ORAL settlements often lead to renewed disputes."},

  # ── General Principles of Agency (7) ────────────────────────────────────
  {"id":"re-nat-610","domain":"General Principles of Agency","type":"single-choice",
   "question":"A licensee discovers their brokerage is engaged in systematic fair-housing violations. Reporting the misconduct may be protected by:",
   "choices":["No protections","Federal court","WHISTLEBLOWER LAWS — many states have laws PROTECTING employees and licensees from RETALIATION for reporting illegal activity; the Sarbanes-Oxley Act and Dodd-Frank Wall Street Reform Act provide protections for reporting financial fraud; reporting to government agencies (HUD, state real estate commission, EEOC) may also trigger protection. The licensee should document their concerns and seek legal advice","Random protections"],
   "correctAnswer":2,
   "explanation":"WHISTLEBLOWER PROTECTIONS may apply to licensees reporting illegal activity: (1) STATE WHISTLEBLOWER LAWS — many states have laws PROTECTING employees and licensees from RETALIATION for reporting illegal activity; (2) FEDERAL PROTECTIONS — Sarbanes-Oxley Act (financial reporting fraud), Dodd-Frank (financial industry); (3) REPORTING TO GOVERNMENT AGENCIES — HUD (fair housing violations), state real estate commission (licensing law violations), EEOC (employment discrimination), DOJ (criminal antitrust); (4) PROTECTED ACTIVITIES typically include: reporting suspected illegal conduct, refusing to participate in illegal conduct, participating in investigations, testifying in proceedings; (5) DAMAGES — for retaliation: reinstatement, back pay, lost benefits, attorney's fees, compensatory and (sometimes) punitive damages. RECOMMENDED ACTIONS: document concerns in writing, retain copies, seek legal advice, consider reporting to appropriate authority."},

  {"id":"re-nat-611","domain":"General Principles of Agency","type":"single-choice",
   "question":"State CONTINUING EDUCATION (CE) requirements for real estate licensees typically include MANDATORY TOPICS in:",
   "choices":["No required topics","Random subjects","Federal preemption","ETHICS, FAIR HOUSING LAW, LEGAL UPDATES, AGENCY LAW, and other state-specific required topics — designed to keep licensees current on legal, ethical, and practical changes; specific hours per topic are typically specified; satisfying mandatory topics is required to renew the license"],
   "correctAnswer":3,
   "explanation":"State CE REQUIREMENTS typically include MANDATORY TOPICS specified by the state real estate commission: (1) ETHICS — typically 3-6 hours per renewal cycle; covers professional ethics, fiduciary duties, conflicts of interest; (2) FAIR HOUSING LAW — typically 3-6 hours; covers federal Fair Housing Act, state and local protections, recent enforcement actions; (3) LEGAL UPDATES — covering recent changes in real estate law, court decisions, regulatory updates; (4) AGENCY LAW — fiduciary duties, agency relationships, dual agency rules; (5) STATE-SPECIFIC REQUIRED TOPICS — depending on state (e.g., escrow management, trust accounts, advertising rules). STRUCTURE: typically a specified number of total CE hours per renewal cycle (often 12-30 hours over 2-4 years), with specific hours allocated to each mandatory topic. The remaining hours can be elective from approved courses."},

  {"id":"re-nat-612","domain":"General Principles of Agency","type":"single-choice",
   "question":"Some states require salespersons to complete an APPRENTICESHIP-LIKE supervised period under a licensed broker:",
   "choices":["Required by federal law in all states","Standard practice in all states","Always 5 years long","TYPICALLY for the first 1-2 years after initial licensure — the salesperson must be SPONSORED BY a supervising broker; the broker has REVIEW and CO-SIGN obligations for the salesperson's transactions; designed to provide supervision during the early career; failure to find a sponsoring broker may result in inactive license"],
   "correctAnswer":3,
   "explanation":"SUPERVISED PERIOD requirements: (1) MOST STATES require new salespersons to be SPONSORED BY a SUPERVISING BROKER during the first years of licensure; (2) DURATION typically 1-2 years, though some states have longer periods (e.g., New York requires 4 years before independent broker eligibility); (3) THE BROKER'S OBLIGATIONS include: (a) REVIEWING and signing the salesperson's listing agreements and transaction documents, (b) PROVIDING TRAINING and oversight, (c) MAINTAINING records of supervision; (4) FAILURE TO MAINTAIN A SPONSORING BROKER — typically results in inactive license; (5) AFTER THE SUPERVISED PERIOD — depending on the state, the salesperson may continue practicing under a broker, or may be eligible to take the broker exam after additional experience and education. The supervision model ensures new licensees receive guidance during their critical early years."},

  {"id":"re-nat-613","domain":"General Principles of Agency","type":"single-choice",
   "question":"Real estate licensees can pursue various PROFESSIONAL DESIGNATIONS from organizations like NAR (National Association of Realtors). Examples include:",
   "choices":["Only one designation","Federal license","CRS (CERTIFIED RESIDENTIAL SPECIALIST), ABR (ACCREDITED BUYER'S REPRESENTATIVE), GRI (GRADUATE, REALTOR INSTITUTE), CCIM (CERTIFIED COMMERCIAL INVESTMENT MEMBER), SRES (SENIORS REAL ESTATE SPECIALIST), and many others — typically requiring additional coursework, experience, and exam; designations distinguish licensees and may signal specialized expertise","No designations"],
   "correctAnswer":1,
   "explanation":"PROFESSIONAL DESIGNATIONS available through NAR and affiliated organizations: (1) CRS (Certified Residential Specialist) — for residential agents with significant transaction experience; (2) ABR (Accredited Buyer's Representative) — for licensees representing buyers; (3) GRI (Graduate, REALTOR Institute) — broad designation covering many topics; (4) CCIM (Certified Commercial Investment Member) — commercial investment real estate; (5) SRES (Seniors Real Estate Specialist) — serving older adult clients; (6) CRP (Certified Relocation Professional) — corporate relocation; (7) RSPS (Resort and Second-Home Specialist) — resort properties; (8) PMN (Performance Management Network) — leadership and management; (9) AHWD (At Home With Diversity) — diversity and inclusion. EACH REQUIRES: additional coursework (often 30-60+ hours), experience requirements, exam, and ongoing membership/dues. Designations signal specialized expertise and may help differentiate licensees in competitive markets."},

  {"id":"re-nat-614","domain":"General Principles of Agency","type":"single-choice",
   "question":"DISCLOSURE OF COMPENSATION ARRANGEMENTS between brokers and licensees:",
   "choices":["Not required","Random","Required to be DISCLOSED to clients in some states (when material to the client's decisions) — including bonuses, referral fees, or other arrangements that might affect the licensee's recommendations; some states have specific disclosure requirements; failure to disclose can result in disciplinary action and rescission rights for clients","Federal preemption"],
   "correctAnswer":2,
   "explanation":"COMPENSATION DISCLOSURE requirements vary by state but generally require: (1) DISCLOSURE TO CLIENTS of material compensation arrangements that might affect the licensee's recommendations — including: (a) BROKER-LICENSEE SPLITS — if unusual and material; (b) BONUSES (typically for specific properties or terms); (c) REFERRAL FEES received from third parties; (d) MARKETING REIMBURSEMENTS from listing brokerages; (e) BUSINESS ARRANGEMENTS with title companies, lenders, or other service providers; (2) SPECIFIC STATE REQUIREMENTS — many states have detailed disclosure rules and forms; (3) FAILURE TO DISCLOSE can result in: license discipline, contract rescission rights for clients, civil liability for damages, NAR Code of Ethics violations; (4) AFFILIATED BUSINESS DISCLOSURES under RESPA also require disclosure of relationships between the licensee and other settlement service providers; (5) MODERN POST-2024 NAR SETTLEMENT environment makes transparency about compensation increasingly important."},

  {"id":"re-nat-615","domain":"General Principles of Agency","type":"single-choice",
   "question":"A licensed broker employs UNLICENSED ASSISTANTS in their office to help with administrative tasks. The broker's liability:",
   "choices":["No liability","Eliminated","Random","SIGNIFICANT — most state real estate laws strictly limit what UNLICENSED ASSISTANTS can do; they generally CANNOT: (a) discuss properties or transactions in substantive detail; (b) host open houses without licensed supervision; (c) negotiate; (d) prepare or explain contracts; (e) provide expert opinions; if unlicensed assistants engage in licensed activities, the supervising broker (and the assistant) face license discipline, fines, and civil liability"],
   "correctAnswer":3,
   "explanation":"UNLICENSED ASSISTANTS and licensed activities — important legal limits: (1) PROHIBITED ACTIVITIES for unlicensed persons typically include: discussing properties or transactions with the public in substantive detail; hosting open houses without licensed supervision; negotiating; preparing or explaining contracts; providing expert opinions about market conditions, pricing, or terms; making representations about properties; quoting commission rates; (2) PERMITTED ADMINISTRATIVE TASKS typically include: scheduling, basic record-keeping, document organization, social media posts (general, not specific properties), basic property information dissemination; (3) STATE LAW SPECIFICS — exact limits vary; some states allow more flexibility for unlicensed assistants under specific supervision conditions; (4) LIABILITY — if unlicensed assistants engage in licensed activities, the supervising broker faces: license discipline, fines, civil liability, contract rescission rights. The unlicensed person may also face criminal penalties for practicing without a license. Best practice: clear written policies and training."},

  {"id":"re-nat-616","domain":"General Principles of Agency","type":"single-choice",
   "question":"NAR (National Association of Realtors) membership is:",
   "choices":["VOLUNTARY — licensees can choose to be REALTORS® (NAR members) or not; membership in NAR (typically through a state or local association) brings benefits (MLS access in many markets, designations, advocacy, code of ethics enforcement, networking) but also obligations (membership dues, code of ethics compliance, arbitration of member-vs-member disputes); not all real estate licensees are REALTORS®","Required by federal law","Required by state law","Eliminated"],
   "correctAnswer":0,
   "explanation":"NAR MEMBERSHIP: (1) VOLUNTARY — joining NAR is OPTIONAL; licensees who join become REALTORS® (a registered trademark); licensees who don't join are still licensed and can practice real estate. (2) STRUCTURE — most members join through a LOCAL ASSOCIATION which automatically enrolls them in state and national NAR; (3) BENEFITS — MLS access (in many markets); CE designations (CRS, ABR, etc.); advocacy through NAR's political action; access to NAR publications and resources; arbitration of member-vs-member disputes; (4) OBLIGATIONS — MEMBERSHIP DUES (typically $200-500+ annually depending on local association); COMPLIANCE WITH NAR CODE OF ETHICS (with disciplinary enforcement); arbitration of member-vs-member disputes; (5) DISTINCTION — 'REALTOR®' refers specifically to NAR members; 'real estate agent' or 'licensee' refers to anyone licensed to practice real estate. The two are not synonymous."},

  # ── Practice of Real Estate (7) ─────────────────────────────────────────
  {"id":"re-nat-617","domain":"Practice of Real Estate","type":"single-choice",
   "question":"Under TRID and RESPA, certain fees and costs on the LOAN ESTIMATE have TOLERANCE LIMITS — they cannot increase by more than specified percentages at closing without lender consequences. Examples:",
   "choices":["No tolerance limits","Random fees","Federal preemption","ZERO TOLERANCE for: lender fees, fees for services the borrower CANNOT shop for (mortgage broker fees, lender title search), and pre-paid items; 10% TOLERANCE for fees for services the borrower CAN shop for (some title-related fees, settlement agent fees) but only if the borrower chose the lender's recommended provider; NO TOLERANCE if the borrower chose their own provider; LENDERS MUST REFUND any excess at closing"],
   "correctAnswer":3,
   "explanation":"TRID/RESPA TOLERANCE LIMITS prevent lenders from dramatically increasing fees from Loan Estimate to closing. THREE TIERS: (1) ZERO TOLERANCE — fees CANNOT INCREASE: (a) lender fees (origination, processing, underwriting); (b) fees for services the borrower CANNOT shop for (mortgage broker fees, lender's title search); (c) pre-paid items (interest, taxes, insurance); (2) 10% TOLERANCE — fees CAN INCREASE BY UP TO 10% IN AGGREGATE: (a) fees for services the borrower CAN shop for but chose the lender's recommended provider; (b) some title-related fees, settlement agent fees, recording fees; (3) NO TOLERANCE — fees can change without limit if: (a) borrower chose their own provider (not lender's); (b) certain customer-driven changes; (c) unforeseen circumstances. EXCESS — lenders must REFUND any excess over tolerance at closing or within 60 days; rule violations can result in CFPB enforcement actions."},

  {"id":"re-nat-618","domain":"Practice of Real Estate","type":"single-choice",
   "question":"LOAN MODIFICATION SCAMS (also called 'mortgage assistance scams' or 'foreclosure rescue fraud'):",
   "choices":["Are legal","Are rare","Mostly target older homeowners","TARGET HOMEOWNERS IN FINANCIAL DISTRESS — scammers charge upfront fees promising to help with loan modifications, foreclosure relief, or other mortgage assistance; common patterns include: (a) UPFRONT FEES (illegal in most states); (b) FALSE PROMISES of guaranteed results; (c) IMPERSONATION of attorneys or government employees; (d) DISCOURAGING contact with lender; protected under federal Mortgage Assistance Relief Services Rule (MARS), state laws, and CFPB enforcement"],
   "correctAnswer":3,
   "explanation":"LOAN MODIFICATION SCAMS target homeowners in financial distress with fraudulent promises of help. COMMON PATTERNS: (1) UPFRONT FEES — most state laws and federal MARS Rule require services to be COMPLETED before payment; many states completely PROHIBIT upfront fees for mortgage assistance; (2) FALSE PROMISES of guaranteed results, federal programs that don't exist, or special insider connections; (3) IMPERSONATION of attorneys, government employees, or established financial institutions; (4) DISCOURAGING borrowers from contacting their own lender (preventing the homeowner from getting actual help); (5) TAKING OWNERSHIP — some scams involve transferring property ownership to the 'rescuer' with vague promises to help; (6) IDENTITY THEFT — collecting financial information for fraud. PROTECTIONS: federal Mortgage Assistance Relief Services (MARS) Rule (16 CFR 322), state laws, CFPB enforcement, attorney general actions. Victims should report to: FTC, CFPB, state AG, HUD-approved housing counselors."},

  {"id":"re-nat-619","domain":"Practice of Real Estate","type":"single-choice",
   "question":"FORECLOSURE RESCUE SCAMS often involve:",
   "choices":["No scams happen","Legitimate banking practices","Random fraud","DISTRESSED HOMEOWNERS being convinced to TRANSFER PROPERTY OWNERSHIP to a 'rescuer' (sometimes via warranty deed or quitclaim deed) with vague promises of refinancing or repurchase opportunities; the rescuer then sells, refinances, or otherwise extracts value while the homeowner loses both property AND any equity. ALSO INCLUDES: equity stripping, rent-back scams, sham transactions, and various other patterns. Federal and state consumer protection laws apply"],
   "correctAnswer":3,
   "explanation":"FORECLOSURE RESCUE SCAMS exploit distressed homeowners. COMMON PATTERNS: (1) DEED THEFT — convincing the homeowner to TRANSFER OWNERSHIP to a 'rescuer' with vague promises of refinancing, lease-back, or repurchase rights; the rescuer then sells, refinances, or otherwise extracts equity; (2) RENT-BACK SCAMS — the rescuer takes title and rents the property back to the homeowner with promises to allow repurchase; rent is often unaffordable, leading to eviction; (3) EQUITY STRIPPING — multiple loans or refinances extracting equity until the homeowner is left with no value; (4) SHAM TRANSACTIONS — fake mortgage modifications, fake loan applications, false promises of government programs; (5) IMPERSONATION of attorneys or housing counselors. PROTECTIONS: federal Mortgage Assistance Relief Services (MARS) Rule, state Foreclosure Rescue Prohibitions, HUD-approved housing counseling, fair housing laws (when targeting specific protected classes). Many states REQUIRE rescission rights for transactions made by homeowners in foreclosure."},

  {"id":"re-nat-620","domain":"Practice of Real Estate","type":"single-choice",
   "question":"AFFINITY FRAUD in real estate occurs when:",
   "choices":["FRAUDSTERS TARGET MEMBERS OF SPECIFIC COMMUNITIES (religious, ethnic, age, professional, etc.) — often presenting themselves as members of the community and exploiting trust within the group; common in investment scams, refinance fraud, foreclosure rescue fraud, and Ponzi schemes; particularly damaging because of social-network amplification","No fraud occurs","Only large investors are affected","Federal court issue only"],
   "correctAnswer":0,
   "explanation":"AFFINITY FRAUD in real estate (and other contexts) targets members of specific COMMUNITIES — religious, ethnic, age, professional, or other groups — exploiting in-group trust. PATTERNS: (1) FRAUDSTER PRESENTS as a member of the community (often genuinely is, or fakes credentials); (2) EXPLOITS TRUST built within the community; (3) USES SOCIAL NETWORKS to spread the fraud — affected community members invite others, amplifying losses; (4) COMMON SCAMS: investment Ponzi schemes (real estate or mortgage-related), refinance fraud, foreclosure rescue, fraudulent investment opportunities. EXAMPLES: schemes targeting religious congregations, ethnic communities, retirees, professional associations. PARTICULARLY DAMAGING because: (a) victims often don't report due to community embarrassment; (b) losses extend across many community members; (c) social network amplification makes early detection hard. PROTECTIONS: SEC, FBI, and state regulators have task forces; community education and skepticism are key defenses."},

  {"id":"re-nat-621","domain":"Practice of Real Estate","type":"single-choice",
   "question":"A PYRAMID SCHEME in real estate (sometimes disguised as 'investment training' or 'multilevel marketing'):",
   "choices":["Is legitimate","Has no consequences","REQUIRES PARTICIPANTS to recruit other participants to earn returns — with most income coming from new recruits' fees rather than from actual real estate transactions; PYRAMID schemes are ILLEGAL under federal and state law; legitimate multilevel marketing involves real product/service sales (not recruitment); SEC, FTC, and state regulators actively prosecute","Federal preemption"],
   "correctAnswer":2,
   "explanation":"PYRAMID SCHEMES IN REAL ESTATE — often disguised as 'investment training' or 'multilevel marketing' programs: (1) REQUIREMENTS — participants must RECRUIT new participants to earn returns; (2) ECONOMIC STRUCTURE — most income comes from RECRUIT FEES rather than from actual real estate transactions; (3) MATHEMATICAL CERTAINTY OF COLLAPSE — eventually, the pool of new recruits exhausts (geometric growth required); (4) DECEPTIVE PRACTICES — false claims about typical participant earnings, manipulated testimonials, pressure tactics; (5) ILLEGAL under federal (FTC Act, SEC Act) and state laws; (6) LEGITIMATE multilevel marketing has REAL PRODUCT/SERVICE SALES (not just recruitment); (7) REGULATORS — SEC, FTC, state attorneys general, state real estate commissions all prosecute; (8) WARNING SIGNS: high enrollment fees, focus on recruitment over sales, unsustainable promises, pressure to recruit, lack of substantive product/service. Real estate-focused pyramid schemes have caused significant losses; victims should report to FTC, SEC, state regulators."},

  {"id":"re-nat-622","domain":"Practice of Real Estate","type":"single-choice",
   "question":"The TELEPHONE CONSUMER PROTECTION ACT (TCPA) of 1991 regulates:",
   "choices":["Real estate inspections","Property values","TELEMARKETING and AUTODIALER calls — restricting calls to numbers on the Do Not Call Registry, requiring proper identification, restricting calls before 8 AM or after 9 PM, prohibiting auto-dialed calls and prerecorded calls to cellphones without prior express consent; ALSO restricts unsolicited TEXT MESSAGES and FAXES; PENALTIES up to $500-$1,500 per violation; real estate licensees who cold-call must comply","Random regulations"],
   "correctAnswer":2,
   "explanation":"TELEPHONE CONSUMER PROTECTION ACT (TCPA) of 1991: (1) RESTRICTS UNSOLICITED CALLS — to numbers on the National Do Not Call Registry; for solicitation purposes; (2) AUTODIALER and PRERECORDED CALL RESTRICTIONS — calls to CELLPHONES require prior express CONSENT (express written consent for sales calls); (3) TIME LIMITS — no telemarketing calls before 8 AM or after 9 PM (in the called party's local time); (4) IDENTIFICATION — caller must identify themselves and the entity they represent at the start of the call; (5) TEXT MESSAGES — same rules apply to unsolicited commercial text messages; (6) FAXES — UNSOLICITED COMMERCIAL FAXES are restricted; (7) PENALTIES — $500-$1,500 per violation (plus statutory damages, treble damages for willful violations); private right of action available — class action lawsuits common; (8) REAL ESTATE LICENSEES who cold-call must comply with TCPA, Do Not Call, and state telemarketing laws. Many states have additional restrictions."},

  {"id":"re-nat-623","domain":"Practice of Real Estate","type":"single-choice",
   "question":"During the COVID-19 pandemic, the federal CDC eviction moratorium:",
   "choices":["Continues today","Is permanent","Has no historical record","TEMPORARILY HALTED MANY EVICTIONS for non-payment of rent during the pandemic (issued in 2020, extended through August 2021 before being struck down by the Supreme Court); subsequent state and local eviction moratoria varied; landlords were generally required to continue eviction processes for non-rent reasons (lease violations, criminal activity, etc.); rental assistance programs (Emergency Rental Assistance Program/ERAP) helped tenants pay back rent"],
   "correctAnswer":3,
   "explanation":"The CDC EVICTION MORATORIUM was a major (and controversial) federal action during the COVID-19 pandemic: (1) ISSUED in September 2020 by the CDC, citing public health authority to prevent eviction-related disease transmission; (2) TEMPORARILY HALTED most evictions for non-payment of rent for eligible tenants; (3) EXTENDED multiple times through August 2021; (4) STRUCK DOWN by the Supreme Court in August 2021 (Alabama Association of Realtors v. HHS) — ruling that CDC lacked statutory authority for this measure; (5) SUBSEQUENT STATE AND LOCAL MORATORIA varied — many continued after the federal moratorium ended; (6) RENTAL ASSISTANCE — Emergency Rental Assistance Program (ERAP) provided $46.5 billion to help tenants pay back rent and utilities; (7) PRACTICAL IMPACT: significant disruption to rental markets, landlord-tenant relationships, eviction processing courts. The historical event illustrates federal vs. state authority over landlord-tenant matters."},

  # ── Financing (5) ───────────────────────────────────────────────────────
  {"id":"re-nat-624","domain":"Financing","type":"single-choice",
   "question":"An ENERGY-EFFICIENT MORTGAGE (EEM) is a special loan program that:",
   "choices":["ALLOWS the borrower to BORROW ADDITIONAL FUNDS to make energy-efficiency improvements to the home — beyond what standard underwriting would permit based on the property's current value. The improvements are projected to REDUCE FUTURE ENERGY COSTS, justifying the higher loan amount. Available through FHA (EEM), VA (energy improvements), and conventional lenders; can be combined with purchase or refinance loans","Standard mortgage","No energy benefits","Random tax benefit"],
   "correctAnswer":0,
   "explanation":"ENERGY-EFFICIENT MORTGAGES (EEMs) are special loan programs that allow borrowers to BORROW ADDITIONAL FUNDS for ENERGY-EFFICIENCY IMPROVEMENTS — beyond what standard underwriting would otherwise permit. PROGRAMS: (1) FHA EEM — increases the FHA loan limit by the cost of energy improvements (limited by stated caps); (2) VA EEM — energy improvements for veterans' purchases; (3) CONVENTIONAL EEMs — through Fannie Mae's HomeStyle Energy program; (4) USDA Rural Energy. RATIONALE: energy improvements REDUCE FUTURE ENERGY COSTS, increasing the borrower's ability to make payments; the additional debt is justified by the savings. ELIGIBLE IMPROVEMENTS: insulation, energy-efficient windows, HVAC upgrades, solar panels, water heaters, smart-home energy controls. REQUIREMENTS: typically a HERS (Home Energy Rating System) rating or similar energy audit; improvements must be cost-effective; integration with purchase or refinance loans. EEMs are underutilized but increasingly important as climate concerns grow."},

  {"id":"re-nat-625","domain":"Financing","type":"single-choice",
   "question":"The FHA 203(k) RENOVATION LOAN allows borrowers to:",
   "choices":["Only purchase","COMBINE the PURCHASE PRICE (or refinance balance) with PLANNED RENOVATION COSTS into a SINGLE MORTGAGE — typically for HUD-approved renovations; the loan funds for renovation are held in escrow and disbursed as work progresses; available in standard 203(k) (more complex projects, $5,000+ renovations) and limited (or 'streamline') 203(k) (simpler projects, less paperwork); useful for purchasing fixer-uppers","Only refinance","Only commercial"],
   "correctAnswer":1,
   "explanation":"FHA 203(k) RENOVATION LOAN: (1) COMBINES PURCHASE PRICE (or refinance balance) with PLANNED RENOVATION COSTS into a SINGLE MORTGAGE; (2) USEFUL for: purchasing FIXER-UPPERS, refinancing with major renovations, addressing deferred maintenance, modernizing older properties; (3) TWO VARIANTS: (a) STANDARD 203(k) — for complex projects, structural changes, additions; minimum $5,000 in renovations; requires HUD-approved consultant; (b) LIMITED (STREAMLINE) 203(k) — for simpler projects, no structural changes, less paperwork; up to $35,000 in renovations; (4) FUND DISBURSEMENT — renovation funds held in escrow and DISBURSED AS WORK PROGRESSES; typically requires HUD-approved contractor; (5) APPRAISAL — based on AS-COMPLETED VALUE (post-renovation); (6) BUYER BENEFITS: ability to purchase distressed properties with renovation budgeted from day one; (7) ALTERNATIVES: Fannie Mae HomeStyle Renovation (conventional), VA renovation loans, USDA renovation programs."},

  {"id":"re-nat-626","domain":"Financing","type":"single-choice",
   "question":"FANNIE MAE'S HOMEREADY and FREDDIE MAC'S HOME POSSIBLE loan programs target:",
   "choices":["High-income buyers","Wealthy investors","LOW- TO MODERATE-INCOME BUYERS — typically with income at or below 80% of area median income (AMI); flexible income sources (including non-occupant co-borrower income, boarder income); reduced PMI; lower down payment options (typically 3%); homebuyer education requirement; available for purchases and refinances; designed to expand homeownership opportunities","Random borrowers"],
   "correctAnswer":2,
   "explanation":"HOMEREADY (Fannie Mae) and HOME POSSIBLE (Freddie Mac) are conventional loan programs targeting LOW- TO MODERATE-INCOME BUYERS: (1) INCOME LIMITS — typically at or below 80% of AREA MEDIAN INCOME (AMI), though some areas have no limits; (2) DOWN PAYMENT — as low as 3%; (3) INCOME SOURCES — flexible: NON-OCCUPANT CO-BORROWER INCOME, BOARDER INCOME (boarder rent counted toward qualifying income), HOUSEHOLD INCOME from non-borrower contributors; (4) PMI — reduced PMI rates compared to standard conventional loans; (5) HOMEBUYER EDUCATION — required (online courses available); (6) AVAILABLE for purchases AND refinances; (7) PROPERTY TYPES — single-family, condos, manufactured homes (with restrictions), 2-4 unit properties; (8) USE — designed to expand homeownership for: first-time buyers, lower-income borrowers, borrowers with non-traditional credit profiles, multigenerational households. These programs have helped millions of borrowers access homeownership."},

  {"id":"re-nat-627","domain":"Financing","type":"single-choice",
   "question":"Financing for MANUFACTURED (MOBILE) HOMES presents specific challenges and options:",
   "choices":["Standard mortgage always","No financing available","Federal regulation only","Manufactured homes (built post-1976 to HUD code) typically can be financed via: (a) FHA TITLE I (for manufactured homes only, longer terms, lower limits); (b) FHA TITLE II (manufactured homes AS REAL PROPERTY ON OWNED LAND, similar to traditional FHA); (c) VA, USDA, conventional, Fannie/Freddie programs — but typically require the home to be on permanently owned land and meet specific criteria; (d) CHATTEL LOANS for homes on rented land (higher rates, shorter terms)"],
   "correctAnswer":3,
   "explanation":"MANUFACTURED HOME FINANCING has specific challenges and options: (1) HUD CODE COMPLIANCE — homes built AFTER JUNE 15, 1976 to HUD code are 'manufactured homes' (not 'mobile homes'); pre-1976 homes are typically uninsurable for traditional financing; (2) LAND OWNERSHIP MATTERS: (a) HOME + OWNED LAND (real property classification) — more financing options, longer terms, lower rates; (b) HOME ON RENTED LAND (chattel/personal property) — typically requires CHATTEL LOANS (shorter terms, higher rates); (3) FHA OPTIONS: (a) TITLE I — for manufactured homes only, including on rented land; (b) TITLE II — manufactured homes on owned land, similar to traditional FHA; (4) OTHER PROGRAMS: VA (eligible veterans), USDA (eligible rural areas), Fannie Mae MH Advantage, Freddie Mac CHOICEHome; (5) CHALLENGES: depreciation (unlike most real estate), fewer secondary-market options, less liquidity. Manufactured homes are an important affordable housing source — financing has been historically more difficult than traditional housing."},

  {"id":"re-nat-628","domain":"Financing","type":"single-choice",
   "question":"In a COOPERATIVE (co-op) housing structure, the buyer purchases SHARES of the corporation and obtains a PROPRIETARY LEASE rather than purchasing the underlying real estate. Financing for co-op purchases:",
   "choices":["IS A 'SHARE LOAN' — secured by the shares and proprietary lease rather than by a traditional mortgage on real property; rates may be slightly HIGHER than traditional mortgages; loan-to-value limits are typically more conservative; LENDERS may require BOARD APPROVAL for the loan; some lenders specialize in co-op financing","Identical to traditional","Federal preemption","No financing"],
   "correctAnswer":0,
   "explanation":"CO-OP SHARE LOANS are specialized: (1) SECURED BY THE SHARES AND PROPRIETARY LEASE — not a traditional mortgage on real property; (2) RATES — typically slightly HIGHER than traditional mortgages (often 0.25-0.5% higher); (3) LTV LIMITS — typically more conservative than traditional mortgages (often 75-80% LTV); (4) BOARD APPROVAL — co-op boards typically must approve the LOAN (the board can deny the loan, blocking the purchase); some lenders require co-op board approval before processing; (5) RECOGNITION AGREEMENTS — typically required between lender and co-op corporation, ensuring the lender has appropriate notice and remedies; (6) SPECIALIZED LENDERS — many lenders don't offer co-op loans; specialized lenders dominate the market (particularly in NYC where co-ops are common); (7) DOWN PAYMENT REQUIREMENTS — co-op boards often impose minimum down payment requirements (often 20-50% depending on the building); higher than typical mortgage requirements; (8) TAX TREATMENT — interest on share loans is deductible as mortgage interest under specific IRS rules."},

  # ── Real Estate Calculations (5) ────────────────────────────────────────
  {"id":"re-nat-629","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A 30-year mortgage at 6% has a monthly P&I payment of $1,799. What is the approximate ORIGINAL LOAN AMOUNT?",
   "choices":["$200,000","$300,000 — using mortgage payment formula REVERSED: solve for P given PMT, rate, term: $1,799 ≈ $300,000 × [0.06/12 × (1.005)^360] / [(1.005)^360 - 1]","$400,000","$100,000"],
   "correctAnswer":1,
   "explanation":"Step 1 — Mortgage payment formula reversed:\nPMT = P × [r(1+r)^n] / [(1+r)^n − 1]\nwhere PMT = $1,799, r = 0.06/12 = 0.005, n = 360.\nStep 2 — Solve for P:\nP = PMT × [(1+r)^n − 1] / [r(1+r)^n]\nP = $1,799 × [(1.005)^360 − 1] / [0.005 × (1.005)^360]\n(1.005)^360 ≈ 6.0226\nP ≈ $1,799 × [5.0226] / [0.005 × 6.0226]\nP ≈ $1,799 × 5.0226 / 0.030113\nP ≈ $300,000.\nStep 3 — Verify: $300,000 × 6% / 12 = $1,500 first-month interest; total monthly P&I $1,799; principal portion $299; cumulative balances trend correctly. ANSWER: approximately $300,000."},

  {"id":"re-nat-630","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A property's assessed value INCREASED from $250,000 to $300,000 mid-year. The mill rate is 30 mills. Approximate tax for the full year (assuming the increase applies for half the year):",
   "choices":["$9,000","$8,250 — Average assessed value = ($250,000 + $300,000) / 2 = $275,000. Tax = $275,000 × 30 ÷ 1,000 = $8,250. (Some jurisdictions PRORATE based on time of assessment change; others apply prior assessment for the entire year)","$7,500","$11,000"],
   "correctAnswer":1,
   "explanation":"Step 1 — Average assessed value for the year (if change applies mid-year): ($250,000 + $300,000) / 2 = $275,000.\nStep 2 — Convert mill rate: 30 mills = 30/1,000 = 0.030.\nStep 3 — Estimated annual tax: $275,000 × 0.030 = $8,250.\nNOTE: actual prorations vary by jurisdiction: (1) some jurisdictions apply the PRIOR ASSESSMENT for the entire year, with the new assessment applying NEXT YEAR ($250,000 × 0.030 = $7,500); (2) some apply the NEW ASSESSMENT retroactively for the full year ($300,000 × 0.030 = $9,000); (3) some PRORATE based on time of assessment change (the $8,250 calculation above). Check specific jurisdictional rules; assessment dates and tax-year alignment vary significantly. This calculation tests the basic concept of WEIGHTED-AVERAGE PRORATION."},

  {"id":"re-nat-631","domain":"Real Estate Calculations","type":"single-choice",
   "question":"Annual property taxes of $3,600 have been paid by the seller for the calendar year. Closing occurs on December 1. Using a 360-day year, the buyer owes the seller a credit for:",
   "choices":["No credit","$300","$3,000 of credit, calculated as 30 days remaining in year × $10/day daily rate ($3,600 ÷ 360)","$300 only because closing is so late in year — Daily tax rate = $3,600 ÷ 360 = $10/day. Days remaining in year after December 1 closing = 30 days (Dec 2-31). Credit to seller = 30 × $10 = $300."],
   "correctAnswer":3,
   "explanation":"Step 1 — Daily tax rate: $3,600 ÷ 360 = $10/day.\nStep 2 — Days remaining in year after December 1 closing = 30 days (Dec 2-31, using 360-day year).\nStep 3 — Credit to seller from buyer: 30 × $10 = $300.\nThe seller has prepaid for the entire year. The buyer will own the property for 30 days at year-end and benefit from the prepaid taxes. So the buyer compensates the seller for those 30 days at the daily rate. Note: in many real-world transactions, the seller WOULDN'T have prepaid the entire year by December 1 — taxes are typically paid in installments. The calculation tests the proration principle. This is the inverse of an early-year closing where the seller would owe the buyer for prepaid taxes covering most of the year."},

  {"id":"re-nat-632","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A property has TOTAL assessed value of $400,000, allocated as: $100,000 LAND + $300,000 IMPROVEMENTS. The mill rate is 25 mills for land, 30 mills for improvements (some jurisdictions apply different rates). What is the total annual tax?",
   "choices":["$11,500 — Land tax = $100,000 × 25 ÷ 1,000 = $2,500. Improvements tax = $300,000 × 30 ÷ 1,000 = $9,000. Total = $2,500 + $9,000 = $11,500. (Note: most jurisdictions apply the SAME rate to total value; some special districts apply different rates)","$10,000","$13,000","$8,000"],
   "correctAnswer":0,
   "explanation":"Step 1 — Land tax: $100,000 × 25/1,000 = $2,500.\nStep 2 — Improvements tax: $300,000 × 30/1,000 = $9,000.\nStep 3 — Total tax: $2,500 + $9,000 = $11,500.\nNOTE: MOST JURISDICTIONS apply the SAME mill rate to total assessed value (e.g., $400,000 × 30/1,000 = $12,000) — they don't separately rate land vs. improvements. Some jurisdictions (often special districts) do apply different rates. The 'split-rate' or 'land value tax' concept — where land is taxed at a HIGHER rate than improvements — is used in some economic theory and limited real-world applications (e.g., parts of Pennsylvania). The calculation tests the ability to apply different rates to different categories — useful for understanding split-rate concepts even where they're not typical."},

  {"id":"re-nat-633","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A single homeowner sold their primary residence (which they've lived in for 10 years) for $700,000. They originally purchased for $200,000 and have made $50,000 in capital improvements. Their TAXABLE capital gain (after Section 121 exclusion):",
   "choices":["$500,000","$200,000 — Adjusted basis = $200,000 + $50,000 = $250,000. Gross gain = $700,000 − $250,000 = $450,000. Section 121 exclusion = $250,000 for single. Taxable gain = $450,000 − $250,000 = $200,000.","$0","$450,000"],
   "correctAnswer":1,
   "explanation":"Step 1 — Adjusted basis: Original cost + capital improvements = $200,000 + $50,000 = $250,000.\nStep 2 — Gross capital gain: $700,000 − $250,000 = $450,000.\nStep 3 — Section 121 exclusion (single filer): UP TO $250,000.\nStep 4 — Taxable gain: $450,000 − $250,000 = $200,000.\nThe taxable $200,000 is taxed at LONG-TERM CAPITAL GAINS rates (currently 0%, 15%, or 20% depending on income). If the homeowner had been married filing jointly, the Section 121 exclusion would be UP TO $500,000 — making the gain fully excluded ($450,000 < $500,000). KEY LESSONS: (1) Section 121 is generous but not unlimited; (2) Tracking BASIS (purchase + improvements) is critical to maximize exclusion; (3) Married couples have substantial benefit; (4) Long-held primary residences in appreciating markets often exceed Section 121 limits."},

  # ── Property Ownership (4) ──────────────────────────────────────────────
  {"id":"re-nat-634","domain":"Property Ownership","type":"single-choice",
   "question":"A grantor wants to create a JOINT TENANCY WITH RIGHT OF SURVIVORSHIP among two of his children. To validly create joint tenancy, the deed must satisfy:",
   "choices":["Random elements","No requirements","THE FOUR UNITIES (PITT: Possession, Interest, Title, Time) — each joint tenant must take possession at the same time (TIME), with EQUAL interests (INTEREST), via the same deed (TITLE), and equal right to possess the whole (POSSESSION); failure of any unity converts the result to tenancy in common (no survivorship); some states have abolished common-law unities for joint tenancy but require similar attributes","Federal certification"],
   "correctAnswer":2,
   "explanation":"JOINT TENANCY requires the FOUR UNITIES (PITT) under common law: (1) UNITY OF POSSESSION — each joint tenant has equal right to possess the whole; (2) UNITY OF INTEREST — each joint tenant has equal share (e.g., two joint tenants each own 50%); cannot be unequal; (3) UNITY OF TITLE — all joint tenants take from the same conveyance (the SAME deed); cannot be from separate deeds at different times; (4) UNITY OF TIME — all joint tenants must take their interest at the SAME MOMENT in time. FAILURE OF ANY UNITY converts the arrangement to TENANCY IN COMMON (no right of survivorship). MODERN STATUTORY CHANGES: many states have ABOLISHED the strict common-law unities for joint tenancy, allowing creation in various circumstances (e.g., transferring to oneself and others as joint tenants). DEED LANGUAGE typically must EXPRESSLY state 'as joint tenants with right of survivorship' — courts often require explicit intent to create joint tenancy over tenancy in common."},

  {"id":"re-nat-635","domain":"Property Ownership","type":"single-choice",
   "question":"In MARITAL PROPERTY law, US states are divided into 'COMMON-LAW' (separate property) states and 'COMMUNITY PROPERTY' states. In COMMUNITY PROPERTY states (CA, TX, AZ, NV, NM, ID, WA, WI, LA + AK as opt-in):",
   "choices":["All states are the same","No marital property","Federal mandate","Property ACQUIRED DURING MARRIAGE is generally considered COMMUNITY PROPERTY (each spouse owns equal share); property OWNED BEFORE MARRIAGE or RECEIVED DURING MARRIAGE BY GIFT OR INHERITANCE remains SEPARATE PROPERTY; gives both spouses equal rights to manage community property; significant implications for ownership, transfers, debt liability, divorce, and inheritance"],
   "correctAnswer":3,
   "explanation":"COMMUNITY PROPERTY states (9 states + AK as opt-in: California, Texas, Arizona, Nevada, New Mexico, Idaho, Washington, Wisconsin, Louisiana, plus Alaska as opt-in for couples who elect): (1) COMMUNITY PROPERTY — property acquired DURING MARRIAGE is generally jointly owned by both spouses, regardless of whose name is on title; (2) SEPARATE PROPERTY — property owned BEFORE MARRIAGE, or RECEIVED DURING MARRIAGE BY GIFT OR INHERITANCE, remains separate. RIGHTS AND OBLIGATIONS: (1) EACH SPOUSE has equal rights to manage community property; (2) BOTH SPOUSES typically must sign for transfers of real estate held as community property; (3) DEBTS incurred during marriage are typically community obligations; (4) DIVISION on divorce — community property typically divided EQUALLY (with state variations); (5) DEATH — surviving spouse typically retains 1/2 of community property automatically; remaining 1/2 passes per the deceased's will or intestate succession; (6) REAL ESTATE PRACTICE — title and deed forms specifically address community property issues. COMMON-LAW (SEPARATE PROPERTY) states (most US states) have different rules — property is owned by whoever's name appears on title."},

  {"id":"re-nat-636","domain":"Property Ownership","type":"single-choice",
   "question":"TENANCY BY THE ENTIRETY (TBE) has distinct tax and creditor implications, including:",
   "choices":["No special treatment","TAX-WISE: property typically TREATED THE SAME as joint tenancy for income tax purposes (the spouses report jointly); for ESTATE TAX, only the deceased spouse's interest is potentially taxable, with the marital deduction protecting the survivor's interest. FOR CREDITORS: in many states, debts of ONE SPOUSE alone CANNOT REACH the TBE property — the property is protected from individual-spouse creditor claims (a key advantage); divorce or death severs the TBE","Federal preemption","Random treatment"],
   "correctAnswer":1,
   "explanation":"TENANCY BY THE ENTIRETY (TBE) — available only to married couples and recognized in some states (TBE-recognizing states include FL, NJ, NY, PA, VA, MA, MD, MI, NC, OH, OK, OR, TN, VT, WA, WY among others). KEY IMPLICATIONS: (1) TAX-WISE — for INCOME TAX purposes, treated similarly to joint tenancy; spouses report jointly; for ESTATE TAX, only the deceased spouse's interest is potentially taxable, and the MARITAL DEDUCTION typically protects the survivor's interest from federal estate tax; (2) CREDITOR PROTECTION — major advantage in many TBE states: DEBTS OF ONE SPOUSE ALONE CANNOT REACH the TBE property; only joint debts of both spouses can. This provides significant protection from individual creditor claims (medical bills, business debts of one spouse, professional liability); (3) RIGHT OF SURVIVORSHIP — the surviving spouse automatically takes full title on the deceased's death; (4) MUTUAL CONSENT — neither spouse can unilaterally sever or convey their interest; (5) DIVORCE SEVERS — divorce typically converts TBE to tenancy in common."},

  {"id":"re-nat-637","domain":"Property Ownership","type":"single-choice",
   "question":"When a joint tenant dies, what documentation is typically needed to update the public records to show survivorship?",
   "choices":["Original deed","An AFFIDAVIT OF SURVIVORSHIP (or 'Affidavit of Death of Joint Tenant') — sworn statement attaching the death certificate and identifying the surviving joint tenant(s); recorded in the county records to clear title for the survivor; some states use specific recording forms; typically straightforward but should be done promptly to maintain clear title","Federal court order","No documentation"],
   "correctAnswer":1,
   "explanation":"SURVIVORSHIP DOCUMENTATION typically uses an AFFIDAVIT OF SURVIVORSHIP (also called 'Affidavit of Death of Joint Tenant' or 'Survivorship Affidavit'): (1) SWORN STATEMENT — by the surviving joint tenant(s) (or executor of the deceased) confirming: (a) the deceased joint tenant has died; (b) the deceased's identity; (c) the date of death; (d) the property in question; (e) the surviving joint tenant's identity. (2) DEATH CERTIFICATE attached as evidence; (3) RECORDED in the county where the property is located; (4) AFTER RECORDING: the public records reflect the surviving joint tenant as the sole owner; the property is no longer subject to the deceased's potential creditors or probate; (5) TIMELINESS — should be done promptly; some states have specific time limits; (6) ALTERNATIVES IN COMMUNITY PROPERTY STATES: a 'Community Property Affidavit' may be used; (7) TENANCY BY THE ENTIRETY automatically passes to the survivor and typically needs similar documentation. Without this filing, the public records remain in the joint tenancy form — creating title problems for the survivor."},

  # ── Transfer of Title (4) ───────────────────────────────────────────────
  {"id":"re-nat-638","domain":"Transfer of Title","type":"single-choice",
   "question":"A grantor signs a deed but the grantee is in another country and cannot personally accept the deed. Most courts apply the doctrine of:",
   "choices":["Mandatory delivery","Federal court","ACCEPTANCE PRESUMPTION — when a deed is BENEFICIAL TO THE GRANTEE (i.e., conveying full title without onerous conditions), and there's no clear evidence of rejection, courts will PRESUME the grantee has accepted; the deed is effective upon delivery to the grantee or to a third party for the grantee's benefit; explicit acceptance is not required when the conveyance is beneficial","No transfer possible"],
   "correctAnswer":2,
   "explanation":"DEED ACCEPTANCE PRESUMPTION is well-established. PRINCIPLES: (1) DEEDS THAT ARE BENEFICIAL TO THE GRANTEE — typical residential or commercial real estate conveyances — are PRESUMED ACCEPTED unless there's clear evidence of REJECTION; (2) THE PRESUMPTION applies when the grantee is alive at the time of delivery (or, in some cases, even after death — passing through their estate); (3) RATIONALE — most people would accept a conveyance of full title; explicit acceptance isn't necessary for the deed to be effective; (4) DELIVERY TO A THIRD PARTY for the grantee's benefit (e.g., to an escrow agent or attorney) is generally treated as delivery to the grantee; (5) WHEN ACCEPTANCE BECOMES AN ISSUE: deeds with ONEROUS CONDITIONS (e.g., agreements requiring the grantee to assume large debts or undesirable obligations); deeds that would expose the grantee to liability (environmental contamination, regulatory violations); in these cases, the grantee may explicitly REJECT to avoid acceptance liability. Most residential transactions don't raise these issues."},

  {"id":"re-nat-639","domain":"Transfer of Title","type":"single-choice",
   "question":"COUNTY RECORDING FEES for deeds and other instruments:",
   "choices":["Federal fees","Free","Random","ARE STATE-LOCAL TRANSACTION COSTS — typically calculated PER PAGE (often $10-50 per page) or PER DOCUMENT (with maximum caps in some jurisdictions); collected at recording by the county recorder; paid at closing by buyer or seller per local custom; helps fund the recording office; recording is essential for providing constructive notice and establishing priority"],
   "correctAnswer":3,
   "explanation":"COUNTY RECORDING FEES are state-local transaction costs: (1) STRUCTURE — typically calculated PER PAGE (often $10-50 per page) or PER DOCUMENT (with caps); some jurisdictions have a per-document base fee plus per-page fee; (2) AMOUNTS — vary by jurisdiction; some counties have substantial fees (e.g., Nevada $40+/page; California $14/first page, $3/subsequent), others are lower; (3) WHO PAYS — typically paid at closing by buyer or seller per local custom (buyer often pays for mortgage recording, seller for deed recording — varies); (4) PURPOSE — helps fund the recording office (technology, staff, archives); (5) IMPORTANCE — recording is ESSENTIAL for: providing constructive notice, establishing priority against later claims, perfecting the buyer's title; (6) ADDITIONAL FEES that may apply: documentary transfer tax (mentioned earlier), state-specific surcharges, technology fees, indexing fees, recording verification fees. Closing agents handle these — buyers and sellers see the totals on the Closing Disclosure."},

  {"id":"re-nat-640","domain":"Transfer of Title","type":"single-choice",
   "question":"A CONSTRUCTIVE TRUST in real estate is:",
   "choices":["AN EQUITABLE REMEDY — a court-imposed legal device treating someone (the constructive trustee) as holding property in trust for the benefit of another (the equitable beneficiary). Created when the trustee acquired property through fraud, breach of fiduciary duty, mistake, or other equitable wrongdoing — to prevent unjust enrichment. The constructive trustee must convey the property to the beneficiary","A formal trust document","Federal preemption","Random arrangement"],
   "correctAnswer":0,
   "explanation":"CONSTRUCTIVE TRUSTS are an EQUITABLE REMEDY (rather than a formal trust document): (1) COURT-IMPOSED — a court treats someone (the 'constructive trustee') as holding property in trust for the benefit of another (the 'equitable beneficiary'); (2) CREATED WHEN — the trustee acquired property through: (a) FRAUD; (b) BREACH OF FIDUCIARY DUTY; (c) MISTAKE; (d) UNJUST ENRICHMENT; (e) other equitable wrongdoing; (3) PURPOSE — to PREVENT UNJUST ENRICHMENT by forcing the wrongdoer to convey the property to the rightful equitable owner; (4) DIFFERENCES FROM EXPRESS TRUSTS: (a) NOT VOLUNTARILY CREATED — imposed by court; (b) NO FORMAL TRUST DOCUMENT — exists by equity; (c) USED AS A REMEDY — not for ongoing trust administration; (5) EXAMPLES: (a) someone who acquires property through fraud must convey to the defrauded person; (b) a fiduciary who breaches duty to acquire property for themselves can be required to convey it; (c) when title is held in one name due to mistake. CONSTRUCTIVE TRUSTS are a powerful equitable remedy."},

  {"id":"re-nat-641","domain":"Transfer of Title","type":"single-choice",
   "question":"The doctrine of MERGER OF ESTATES (when one party comes to own both dominant and servient estates of an easement, or both a leasehold and a fee):",
   "choices":["Eliminates all estates","Federal court only","Random rule","CAUSES the lesser estate (or the easement) to MERGE INTO THE GREATER ESTATE — terminating the lesser interest. EXAMPLES: (a) if the owner of a dominant easement acquires title to the servient property, the easement merges into ownership and ends; (b) if a tenant acquires the landlord's fee interest, the leasehold merges into the fee. The doctrine typically operates AUTOMATICALLY by operation of law"],
   "correctAnswer":3,
   "explanation":"DOCTRINE OF MERGER OF ESTATES: (1) APPLIES when ONE PARTY comes to own multiple estates in the same property; (2) CAUSES the lesser estate (or the easement) to MERGE INTO THE GREATER ESTATE — terminating the lesser interest. EXAMPLES: (a) DOMINANT/SERVIENT MERGER — if the owner of a dominant easement acquires title to the servient property, the easement merges into ownership and TERMINATES (the easement no longer exists). The owner cannot 'use their own easement' on their own property — they just own it. (b) LEASEHOLD/FEE MERGER — if a tenant ACQUIRES the landlord's fee interest, the leasehold MERGES into the fee — the tenant now owns the property outright. (c) MORTGAGE/FEE MERGER — generally REQUIRES additional intent to merge; without intent, the mortgage can remain valid. (3) OPERATES AUTOMATICALLY by operation of law in most cases; (4) DELIBERATE NON-MERGER — sometimes parties want to avoid merger (e.g., a tenant who buys the building may want to keep the lease in force as a separate obligation for tax reasons); requires explicit documentation."},

  # ── Valuation and Market Analysis (3) ───────────────────────────────────
  {"id":"re-nat-642","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"DEMAND DRIVERS in real estate markets include:",
   "choices":["EMPLOYMENT GROWTH (jobs attracting people to an area), POPULATION GROWTH (more potential buyers/renters), INCOME LEVELS (higher incomes support higher prices), MORTGAGE RATES (lower rates increase affordability), CONSUMER CONFIDENCE, demographic trends (household formation rates), and migration patterns; demand factors typically affect prices and absorption rates; markets with strong demand drivers see appreciating prices","No drivers exist","Random factors","Federal regulation"],
   "correctAnswer":0,
   "explanation":"DEMAND DRIVERS in real estate markets — factors that increase consumer demand for housing: (1) EMPLOYMENT GROWTH — jobs attract migration and increase income; (2) POPULATION GROWTH — more potential buyers and renters; (3) INCOME LEVELS — higher incomes support higher prices; (4) MORTGAGE RATES — lower rates increase affordability (purchase power); (5) CONSUMER CONFIDENCE — affects willingness to make large purchases; (6) DEMOGRAPHIC TRENDS — household formation rates, generational patterns (millennials forming households, baby boomers downsizing); (7) MIGRATION PATTERNS — domestic relocation, international immigration; (8) GEOGRAPHIC PREFERENCES — climate, urban vs. suburban, work-from-home enabled relocations. STRONG DEMAND DRIVERS produce: (a) RISING PRICES — bidding up of limited supply; (b) DECLINING DAYS ON MARKET — quicker sales; (c) HIGHER ABSORPTION RATES — new construction selling quickly. WEAK DEMAND DRIVERS produce: (a) DECLINING OR STAGNANT PRICES; (b) INCREASING DAYS ON MARKET; (c) HIGHER VACANCY in rental markets. Real estate professionals must analyze demand drivers to advise clients and forecast trends."},

  {"id":"re-nat-643","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"SUPPLY DRIVERS in real estate markets include:",
   "choices":["Eliminate housing","Federal preemption","Only government action","NEW CONSTRUCTION (rate of new home/apartment building), AVAILABLE EXISTING INVENTORY (homes listed for sale), TENURE PATTERNS (homeowners staying longer reduces supply), LAND AVAILABILITY (developable land for new construction), REGULATORY ENVIRONMENT (zoning, permits, building codes affecting construction speed), and CONSTRUCTION COSTS (affecting new construction profitability); MARKETS WITH CONSTRAINED SUPPLY see PRICES RISE faster"],
   "correctAnswer":3,
   "explanation":"SUPPLY DRIVERS in real estate markets — factors affecting how much housing is available: (1) NEW CONSTRUCTION — the rate of new home/apartment building (controlled by builders, financing, permitting, regulation); (2) AVAILABLE EXISTING INVENTORY — homes listed for sale (controlled by individual decisions to sell); (3) TENURE PATTERNS — average length of homeownership; homeowners staying longer (e.g., due to low mortgage rates locked in earlier) reduces supply; (4) LAND AVAILABILITY — developable land for new construction; geographic constraints (oceans, mountains, lakes, protected lands); (5) REGULATORY ENVIRONMENT — zoning, permitting requirements, building codes, environmental review, subdivision regulations — affecting how quickly new supply can be added; (6) CONSTRUCTION COSTS — building materials, labor, financing — affecting whether new construction is profitable; (7) DEMOLITIONS AND CONVERSIONS — losses from supply through demolition or conversion to non-residential use. CONSTRAINED SUPPLY: when demand exceeds supply (low new construction, low existing inventory), PRICES RISE FASTER. ABUNDANT SUPPLY: PRICES MODERATE or decline."},

  {"id":"re-nat-644","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"MARKET SEGMENTATION in real estate refers to:",
   "choices":["DIVIDING THE TOTAL MARKET into smaller, more analyzable SUB-MARKETS based on relevant characteristics — typically: PROPERTY TYPE (single-family vs. condo vs. multi-family vs. commercial), PRICE TIER (starter, mid-range, luxury), GEOGRAPHIC AREA (neighborhood, school district, zip code), and BUYER DEMOGRAPHICS (first-time buyers, families, investors). Each segment has DIFFERENT demand, supply, and pricing dynamics; analysis must be SEGMENT-SPECIFIC","No segmentation","Federal categories","Random"],
   "correctAnswer":0,
   "explanation":"MARKET SEGMENTATION is essential for meaningful real estate analysis: (1) DIVIDING the total market into SMALLER, MORE ANALYZABLE SUB-MARKETS based on relevant characteristics; (2) COMMON SEGMENTATIONS: (a) PROPERTY TYPE — single-family vs. condo vs. multi-family vs. commercial; (b) PRICE TIER — starter (lower 33%), mid-range, luxury (top 10-20%); (c) GEOGRAPHIC AREA — neighborhood, school district, zip code; (d) BUYER DEMOGRAPHICS — first-time buyers, families with school-age children, empty-nesters, retirees, investors; (e) PROPERTY AGE/CONDITION — new construction, mature, fixer-uppers; (3) IMPORTANCE — EACH SEGMENT HAS DIFFERENT DEMAND, SUPPLY, AND PRICING DYNAMICS; (4) PRACTICAL APPLICATIONS: (a) APPRAISALS — comparables must be from the same market segment; (b) MARKET REPORTS — should report by segment, not just overall market; (c) CMA — comparables must match the subject's segment; (d) INVESTMENT ANALYSIS — different segments have different return profiles. AGGREGATING ACROSS SEGMENTS often produces misleading market analysis."},

  # ── Property Disclosures (3) ────────────────────────────────────────────
  {"id":"re-nat-645","domain":"Property Disclosures","type":"single-choice",
   "question":"With respect to PROPERTY TAX HISTORY of a property:",
   "choices":["Tax history is irrelevant","Most state disclosure laws require sellers to disclose the AMOUNT of current annual property tax, but RECENT TAX HISTORY (recent increases, planned reassessments, special assessments, tax-related issues) should also be disclosed; buyers should investigate independently because: (a) major tax increases may be coming; (b) special assessments may be in process; (c) tax history reveals expected ongoing costs","Always private","Federal preemption"],
   "correctAnswer":1,
   "explanation":"PROPERTY TAX HISTORY DISCLOSURE typically includes: (1) CURRENT ANNUAL TAX AMOUNT — most state disclosure laws require this; (2) ADDITIONAL DISCLOSURES (beyond statutory minimums) commonly include: (a) RECENT TAX INCREASES — significant year-over-year increases; (b) PENDING REASSESSMENT — known plans for assessment changes affecting future taxes; (c) SPECIAL ASSESSMENTS — pending or recent special assessments for infrastructure (sewer, sidewalks, neighborhood improvements); (d) HOMESTEAD EXEMPTIONS — whether currently applied, and whether new owner would qualify; (e) PROPOSED CHANGES — pending bond issues, mill rate changes, or other tax-related changes; (3) BUYER PROTECTION — beyond seller disclosure, buyers should independently INVESTIGATE: (a) PROPERTY APPRAISER'S OFFICE for recent and projected tax data; (b) RECENT SALES IN THE AREA showing tax burden; (c) PLANNED IMPROVEMENTS that might trigger special assessments. Property taxes are typically one of the LARGEST ongoing ownership costs — accurate disclosure helps buyers make informed decisions."},

  {"id":"re-nat-646","domain":"Property Disclosures","type":"single-choice",
   "question":"BOUNDARY DISPUTES involving the property:",
   "choices":["Not material","CONSTITUTE MATERIAL FACTS requiring disclosure — sellers should disclose any known boundary disputes, easement disputes, encroachment issues, or related litigation. Buyers may also investigate through: surveys, title searches, neighbor interviews, and review of property records; PENDING boundary disputes can significantly affect the property's title and value","Federal preemption","Always private"],
   "correctAnswer":1,
   "explanation":"BOUNDARY DISPUTES typically constitute MATERIAL FACTS requiring disclosure: (1) WHAT TO DISCLOSE: (a) KNOWN BOUNDARY DISPUTES with neighbors (e.g., disagreements about property lines); (b) ENCROACHMENT ISSUES (existing or potential encroachments); (c) EASEMENT DISPUTES (questions about easement rights, access, scope); (d) RELATED LITIGATION (pending or recent court cases); (e) SURVEY-RELATED ISSUES (recent surveys revealing problems); (2) BUYER INDEPENDENT INVESTIGATION: (a) ORDER A SURVEY — essential for identifying boundary issues; (b) TITLE SEARCH — may reveal recorded easements or boundary instruments; (c) NEIGHBOR INTERVIEWS — talking with adjacent property owners; (d) PROPERTY RECORDS — review deeds, plats, and historical records; (3) IMPACT — pending or unresolved boundary disputes can: (a) AFFECT TITLE INSURANCE coverage and premiums; (b) LIMIT FUTURE DEVELOPMENT (planning, building); (c) CAUSE LITIGATION COSTS for buyer; (d) REDUCE PROPERTY VALUE. Buyers should typically REQUIRE clean boundary resolution before closing."},

  {"id":"re-nat-647","domain":"Property Disclosures","type":"single-choice",
   "question":"EASEMENTS that benefit OR burden the property:",
   "choices":["Don't matter","Are unenforceable","Federal preemption","SHOULD BE DISCLOSED — sellers should disclose all known easements: (a) BENEFITS THE PROPERTY (rights to use neighbor's land for access, utilities, etc.); (b) BURDENS THE PROPERTY (other parties' rights to use this property for access, utilities, etc.); buyers should investigate via title search and survey. Easements run with the land — they transfer with the property and can substantially affect use, value, and development potential"],
   "correctAnswer":3,
   "explanation":"EASEMENT DISCLOSURE is essential: (1) WHAT TO DISCLOSE: (a) BENEFITING EASEMENTS — easements that BENEFIT this property (e.g., the right to cross neighbor's land for access; utility easements ensuring services); (b) BURDENING EASEMENTS — easements that BURDEN this property (e.g., neighbor's right to access through this property; utility easements limiting where structures can be built; conservation easements); (c) PRESCRIPTIVE EASEMENTS — easements that may have arisen from long use even without express grant; (d) IMPLIED EASEMENTS — easements that may exist by necessity or implication; (2) BUYER INDEPENDENT INVESTIGATION: (a) TITLE SEARCH — reveals RECORDED easements; (b) SURVEY — may identify physical easement uses; (c) PROPERTY INSPECTION — looking for evidence of utility easements (manholes, transformers, power lines, etc.); (3) IMPACT: easements RUN WITH THE LAND — they transfer with the property and can substantially affect: (a) USE AND ENJOYMENT of the property; (b) DEVELOPMENT POTENTIAL (where structures can be built); (c) VALUE — restrictive easements typically reduce value, beneficial easements typically increase value."},

  # ── Land Use Controls and Regulations (2) ───────────────────────────────
  {"id":"re-nat-648","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"AGGREGATING multiple smaller parcels into a single larger development site requires:",
   "choices":["TYPICAL STEPS — purchasing individual parcels (often through option agreements to lock prices while assembling); ensuring CONSISTENT TITLE without gaps; preparing CONSOLIDATED SURVEY of the assembled land; FILING a vacated-plat or replat to legally combine parcels; obtaining necessary REZONING and other approvals for the desired use; can take YEARS and significant CAPITAL — successful developers often have specialized expertise","No requirements","Federal court","Random process"],
   "correctAnswer":0,
   "explanation":"PARCEL AGGREGATION (also called 'assemblage') for development: (1) STRATEGIC TYPICAL STEPS: (a) IDENTIFY THE DEVELOPMENT VISION — what use requires aggregation; (b) ANALYZE THE TARGET ZONE — does it allow the intended use? at what density? (c) IDENTIFY OWNER UNIVERSE — who owns the relevant parcels? what's their motivation? (d) PURCHASE PARCELS — typically through OPTION AGREEMENTS to lock prices while assembling (rather than outright purchase, which would reveal the assembly and drive up later prices); (2) TITLE CONSIDERATIONS: (a) ENSURE CONSISTENT TITLE without gaps; (b) ADDRESS any title clouds, easements, restrictions; (c) PREPARE CONSOLIDATED SURVEY of the assembled land; (d) FILE A VACATED-PLAT or REPLAT to legally combine parcels into a single development site; (3) APPROVALS — obtain necessary REZONING and other approvals for the desired use; (4) FINANCING — bridge loans, joint ventures, equity partners; (5) TIME — assembly often takes YEARS; (6) RISK — partial assembly may not be useful if one owner refuses to sell; specialized developers have expertise in this area."},

  {"id":"re-nat-649","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"SUBDIVISION DESIGN — the layout of streets, lots, common areas, and infrastructure in a new development — is subject to:",
   "choices":["No regulation","SUBSTANTIAL REGULATION through subdivision ordinances enforced by planning commissions and other local authorities; typical requirements address: street widths and patterns, lot sizes and orientations, sidewalks, drainage and stormwater management, utility infrastructure, open space requirements (% of land for public/common use), buffer zones from adjoining incompatible uses, and access standards. Developers must submit detailed plans for approval before construction begins","Federal preemption","Random standards"],
   "correctAnswer":1,
   "explanation":"SUBDIVISION DESIGN is subject to extensive regulation: (1) SUBDIVISION ORDINANCES enforced by planning commissions and local authorities; (2) TYPICAL REQUIREMENTS address: (a) STREET WIDTHS and PATTERNS — minimum widths, sight distances, cul-de-sac standards, grid vs. curvilinear preferences; (b) LOT SIZES and ORIENTATIONS — minimum lot dimensions, lot frontage on streets, setback requirements; (c) SIDEWALKS — required width and material; (d) DRAINAGE and STORMWATER MANAGEMENT — preventing flooding, environmental compliance; (e) UTILITY INFRASTRUCTURE — water, sewer, electricity, natural gas, telecommunications; (f) OPEN SPACE REQUIREMENTS — % of land for public/common use, parks; (g) BUFFER ZONES from adjoining incompatible uses; (h) ACCESS STANDARDS — driveway placement, road connections; (3) APPROVAL PROCESS — DETAILED PLANS submitted for: PLANNING COMMISSION review; PUBLIC HEARINGS; FINAL APPROVAL by local governing body; (4) RECORDING — approved plats are RECORDED in the county records and become legal descriptions for the new lots; (5) DEVELOPMENT AGREEMENTS — sometimes used to address specific concerns. Subdivision design substantially shapes neighborhood character for decades."},

  # ── Leasing and Property Management (1) ─────────────────────────────────
  {"id":"re-nat-650","domain":"Leasing and Property Management","type":"single-choice",
   "question":"In residential leases, a landlord's RIGHT OF ENTRY into the leased premises:",
   "choices":["Allows entry anytime","Is unlimited","REQUIRES PROPER NOTICE (typically 24 hours minimum, often 48 hours, longer in some jurisdictions) and ENTRY MUST BE for LAWFUL PURPOSES (inspections, repairs, showings to prospective new tenants, etc.); UNANNOUNCED entry is typically a violation of the tenant's right to QUIET ENJOYMENT — exposing the landlord to liability. EXCEPTIONS for emergencies (fire, gas leak, etc.) where immediate entry is necessary","Tenant cannot deny"],
   "correctAnswer":2,
   "explanation":"LANDLORD RIGHT OF ENTRY in residential leases is heavily regulated to balance landlord access needs with tenant privacy: (1) PROPER NOTICE typically required — 24 HOURS MINIMUM (often 48 hours, longer in some jurisdictions like California's 24 hours, Massachusetts's at least 24 hours' notice in most cases); some states allow 12 hours for some entries; (2) LAWFUL PURPOSES required: (a) PROPERTY INSPECTIONS — typically with notice, reasonable frequency; (b) REPAIRS — necessary maintenance and repairs; (c) SHOWINGS to prospective new tenants (typically after lease termination notice); (d) SHOWINGS to prospective buyers (typically subject to lease terms); (e) DELIVERY of important documents or services; (3) UNANNOUNCED ENTRY — typically VIOLATES the tenant's right to QUIET ENJOYMENT and may expose the landlord to: rent abatement claims, damages, criminal trespass charges in some states, fair housing implications if discriminatory; (4) EMERGENCIES — exceptions for emergencies (fire, gas leak, water leak threatening damage) where immediate entry is necessary; (5) TIME OF DAY — typically must be during reasonable hours (9 AM - 6 PM in many states); (6) ABUSIVE ENTRY — pattern of harassment via entry can be retaliation and grounds for tenant action."},
]

data.extend(new_qs)
Q.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"Written: {len(data)} questions")
