"""Real Estate National batch 10 — questions 451-500."""
import json, pathlib

Q = pathlib.Path("src/data/real-estate-national-questions.json")
data = json.loads(Q.read_text(encoding="utf-8"))

new_qs = [
  # ── Contracts (9) ───────────────────────────────────────────────────────
  {"id":"re-nat-451","domain":"Contracts","type":"single-choice",
   "question":"A buyer sues a seller for specific performance. For the buyer to obtain specific performance, the buyer must demonstrate that they are:",
   "choices":["READY, WILLING, AND ABLE to perform their own obligations — including having the funds to close and tendering performance — because courts will not order specific performance to a party who is not prepared to fulfill their own side of the contract","Already at closing","Wealthy","Represented by an attorney"],
   "correctAnswer":0,
   "explanation":"To obtain specific performance, the requesting party must demonstrate they are READY, WILLING, AND ABLE to perform their own contract obligations — including having the funds, financing, and any other prerequisites in place. A buyer who can't actually close cannot force the seller to convey. Courts apply this principle because specific performance is an equitable remedy — the plaintiff must come with 'clean hands' and be prepared to do their part."},

  {"id":"re-nat-452","domain":"Contracts","type":"single-choice",
   "question":"A buyer breaches a purchase contract. The seller's damages are typically measured by:",
   "choices":["Punitive damages only","EXPECTATION DAMAGES — the position the seller would have been in had the contract been performed (typically the difference between the contract price and the eventual resale price plus carrying costs and lost opportunity damages)","Sentimental damages","Nominal damages only"],
   "correctAnswer":1,
   "explanation":"Expectation damages (sometimes called 'benefit of the bargain' damages) put the non-breaching party in the position they would have occupied had the contract been performed. For a seller after buyer breach: typically the difference between the contract price and the actual resale price, plus carrying costs (mortgage, taxes, utilities, etc.) during the period of seller's mitigation efforts, minus any avoided costs. Many residential contracts cap the seller's recovery via liquidated damages provisions (often the earnest money)."},

  {"id":"re-nat-453","domain":"Contracts","type":"single-choice",
   "question":"After a contract breach, the non-breaching party can sometimes choose to recover:",
   "choices":["Always punitive damages","Punitive damages by default","RELIANCE DAMAGES — the costs the non-breaching party incurred IN RELIANCE on the contract (e.g., inspection fees, appraisal fees, moving expenses prepared) when expectation damages are difficult to prove or insufficient","No damages at all"],
   "correctAnswer":2,
   "explanation":"Three main categories of contract damages: (1) EXPECTATION damages — putting the party where they would have been if the contract had been performed; (2) RELIANCE damages — reimbursing costs incurred in reliance on the contract (inspections, appraisals, financing applications, moving prep); (3) RESTITUTION damages — returning what was given to prevent unjust enrichment. The non-breaching party often elects whichever measure produces the largest recovery in their specific case. Each measure aims to achieve a different remedial goal."},

  {"id":"re-nat-454","domain":"Contracts","type":"single-choice",
   "question":"The Uniform Commercial Code (UCC) governs the sale of goods. UCC Article 2 applicability to real estate transactions is generally:",
   "choices":["UCC Article 2 applies to all real estate transactions","UCC governs only commercial real estate","UCC replaces common-law contract rules","REAL ESTATE TRANSACTIONS are GENERALLY OUTSIDE the scope of UCC Article 2 (which applies to 'goods,' not real property); real estate transactions are governed by common-law contract principles and state real-property statutes — though UCC Article 9 (secured transactions) may apply to security interests in fixtures"],
   "correctAnswer":3,
   "explanation":"UCC Article 2 (the most commonly tested UCC provisions) applies to the sale of 'goods' — movable personal property — and does NOT apply to real estate transactions. Real estate is governed by common-law contract principles, state real-property law, and the Statute of Frauds. UCC Article 9 (secured transactions) MAY apply to certain real-estate-related transactions involving fixtures or where collateral has both goods and real-property characteristics. The UCC and real estate law sometimes interact at boundaries (fixtures, growing crops, severed timber, certain commercial financing) — but UCC Article 2 doesn't directly govern real estate sales."},

  {"id":"re-nat-455","domain":"Contracts","type":"single-choice",
   "question":"A seller is sued for breach of an oral promise to convey real estate. The Statute of Frauds (SoF) is:",
   "choices":["A DEFENSE — the seller can assert the SoF as a defense, arguing that the oral promise is unenforceable because the SoF requires real estate conveyances to be in writing; exceptions include partial performance, equitable estoppel, and admission of the contract by the party against whom enforcement is sought","Always invoked by the plaintiff","Required for jury trials","Eliminated by federal law"],
   "correctAnswer":0,
   "explanation":"The Statute of Frauds is asserted as a DEFENSE by the party trying to AVOID enforcement of an oral agreement. A seller sued on an oral real estate promise can assert the SoF to defeat the lawsuit. However, EXCEPTIONS exist: (1) PARTIAL PERFORMANCE — if the buyer has paid part of the purchase price AND taken possession AND made improvements, courts may estop the SoF defense; (2) EQUITABLE ESTOPPEL — if the seller's conduct led the buyer to reasonably rely; (3) ADMISSION — if the seller admits the contract in pleadings or testimony; (4) PROMISSORY ESTOPPEL in narrow cases. The defense has significant limitations."},

  {"id":"re-nat-456","domain":"Contracts","type":"single-choice",
   "question":"An INDEMNIFICATION clause in a real estate contract typically:",
   "choices":["Eliminates all liability","REQUIRES one party (the indemnitor) to DEFEND and REIMBURSE the other party (the indemnitee) for specified claims, losses, or damages — typically claims arising from the indemnitor's actions, breaches, or status; common in commercial real estate, property management, and brokerage agreements","Is illegal","Is the same as insurance"],
   "correctAnswer":1,
   "explanation":"Indemnification clauses shift risk between parties. An indemnitor agrees to: (1) DEFEND the indemnitee against specified claims (i.e., pay legal fees), (2) HOLD the indemnitee HARMLESS (i.e., absorb the loss), and (3) INDEMNIFY (reimburse) the indemnitee for losses, damages, or expenses. The scope is defined by the clause: indemnification 'for' the indemnitor's own actions, OR 'against' all claims (including those caused by the indemnitee — controversial and often statutorily limited). Common in: commercial real estate, property management, brokerage agreements, joint ventures. Indemnification is NOT insurance — it depends on the indemnitor's ability to pay."},

  {"id":"re-nat-457","domain":"Contracts","type":"single-choice",
   "question":"A HOLD HARMLESS clause attempting to release one party from liability for their OWN gross negligence or intentional misconduct is typically:",
   "choices":["Always enforceable","Required by federal law","Either UNENFORCEABLE OR HEAVILY SCRUTINIZED — courts in most states refuse to enforce contractual provisions that release a party from liability for their own intentional misconduct, gross negligence, or violations of strong public policy. Hold-harmless clauses are common for ordinary negligence but limited at the extremes","Required for residential contracts"],
   "correctAnswer":2,
   "explanation":"Hold-harmless and exculpatory clauses (releasing one party from liability) face significant legal limits. While ORDINARY NEGLIGENCE can typically be the subject of valid hold-harmless clauses (with clear, conspicuous language), provisions attempting to release a party from: (1) GROSS NEGLIGENCE, (2) INTENTIONAL MISCONDUCT, (3) VIOLATIONS OF STRONG PUBLIC POLICY, (4) PERSONAL INJURY CAUSED BY the party's reckless conduct — are typically UNENFORCEABLE under most state laws. Even ordinary-negligence releases face scrutiny if they're hidden in fine print or in contracts of adhesion."},

  {"id":"re-nat-458","domain":"Contracts","type":"single-choice",
   "question":"After a NOVATION (substitution of a new party and release of the original), the original party is:",
   "choices":["Still liable on the original contract","Liable as a surety","Required to perform on demand","FULLY RELEASED from all obligations under the original contract; the new party assumes all duties; this differs from a simple ASSIGNMENT, where the assignor typically retains secondary liability"],
   "correctAnswer":3,
   "explanation":"Novation involves three elements: (1) a NEW CONTRACT, (2) SUBSTITUTION of a new party for the original, (3) DISCHARGE of the original party. After valid novation, the ORIGINAL PARTY IS FULLY RELEASED from all obligations under the original contract — the new party stands in their shoes. Novation requires consent of all three parties (original obligor, new obligor, and the other side of the deal). Compare to ASSIGNMENT, where the assignor typically retains SECONDARY liability if the assignee defaults. Novation is the cleaner — but rarer — substitution mechanism."},

  {"id":"re-nat-459","domain":"Contracts","type":"single-choice",
   "question":"A bank sells (ASSIGNS) a mortgage to a different lender. The assignment is documented in a separate instrument and recorded. The assignment:",
   "choices":["Eliminates the borrower's obligation","Transfers the BENEFICIAL ownership of the mortgage (the right to receive payments and to enforce the security) to the new lender; the borrower's underlying loan obligations continue unchanged; assignment must typically be in writing and (for full protection against subsequent transfers) recorded","Requires the borrower's consent","Is illegal"],
   "correctAnswer":1,
   "explanation":"Mortgage assignment transfers the beneficial ownership of the mortgage (the right to receive payments and to enforce against the property) to the new lender. The borrower's underlying loan OBLIGATIONS continue unchanged — they just pay a different lender. Assignment must typically be: (1) in writing, (2) signed by the assignor, (3) RECORDED to provide constructive notice and protect against subsequent transfers, and (4) accompanied by notice to the borrower under RESPA (servicing transfer notice). Mortgage assignments are extremely common in the secondary mortgage market — most loans are sold and reassigned multiple times over their lives."},

  # ── General Principles of Agency (7) ────────────────────────────────────
  {"id":"re-nat-460","domain":"General Principles of Agency","type":"single-choice",
   "question":"A real estate brokerage opens a second location across town. The new location is generally considered:",
   "choices":["Optional and unregulated","Separate from the main office","A BRANCH OFFICE — typically requiring separate registration with the state real estate commission, separate physical signage, a designated branch manager (often a licensed broker), separate trust accounts in some states, and compliance with applicable advertising rules","An automatic separate brokerage"],
   "correctAnswer":2,
   "explanation":"Branch offices have specific regulatory requirements that vary by state, typically including: (1) SEPARATE REGISTRATION with the state real estate commission; (2) PHYSICAL SIGNAGE distinguishing the branch and identifying it as a branch of the main brokerage; (3) DESIGNATED BRANCH MANAGER (often a licensed broker or broker-associate) responsible for supervision; (4) SEPARATE TRUST ACCOUNTS in some states; (5) compliance with all applicable advertising and licensing rules. Failure to comply with branch office rules can result in license discipline."},

  {"id":"re-nat-461","domain":"General Principles of Agency","type":"single-choice",
   "question":"In many states, each licensed brokerage must designate a 'qualifying broker' or 'broker-of-record.' This person:",
   "choices":["Is the youngest licensee","Is the broker who handles the most listings","Is the brokerage's CEO automatically","Is a specifically designated LICENSED BROKER (sometimes also called designated broker or principal broker) who is legally responsible for the brokerage's compliance with state real estate laws — including supervision of salespersons, trust account management, advertising compliance, and licensing matters; bears personal license risk for brokerage failures"],
   "correctAnswer":3,
   "explanation":"The qualifying broker (or designated broker, principal broker, broker-of-record — terminology varies by state) is the LICENSED BROKER specifically designated to be legally responsible for the brokerage's compliance with state real estate licensing law. Duties include: (1) supervising affiliated salespersons, (2) trust-account compliance and management, (3) advertising compliance, (4) licensing matters and renewals, (5) record-keeping, (6) state-required reporting. The qualifying broker bears PERSONAL license risk for brokerage failures — they can face discipline for company-wide violations even when not personally involved."},

  {"id":"re-nat-462","domain":"General Principles of Agency","type":"single-choice",
   "question":"A consumer wins a $50,000 judgment against a licensee for fraud. The licensee is insolvent and the judgment cannot be collected. In a state with a real estate recovery fund, the consumer typically:",
   "choices":["Files a claim with the state's real estate recovery fund — providing the judgment, evidence of inability to collect from the licensee, and proof of compliance with the fund's procedural requirements; if approved, the fund pays the consumer up to the statutory cap, and the LICENSEE'S LICENSE IS TYPICALLY SUSPENDED UNTIL REPAYMENT","Has no further options","Must pursue the licensee's family","Can collect from the state real estate commission directly"],
   "correctAnswer":0,
   "explanation":"State real estate recovery funds (where they exist) provide a backstop for consumers who win judgments against licensees but cannot collect. The process typically: (1) consumer obtains a JUDGMENT against the licensee in civil court for fraud, misrepresentation, breach of fiduciary duty, etc.; (2) consumer demonstrates INABILITY TO COLLECT from the licensee; (3) files a CLAIM with the recovery fund per state procedure; (4) the commission reviews and approves up to the statutory cap (often $25,000-$50,000 per claim, with aggregate caps per licensee); (5) the fund pays the consumer, and the LICENSEE'S LICENSE IS SUSPENDED until they reimburse the fund."},

  {"id":"re-nat-463","domain":"General Principles of Agency","type":"single-choice",
   "question":"State real estate commissions often conduct TRUST ACCOUNT AUDITS of broker offices. These audits typically examine:",
   "choices":["The brokerage's profit margin","Whether the trust account is properly maintained — separate from operating funds, with timely deposits, accurate records of every transaction, monthly reconciliation, and no commingling or conversion; failures can result in license discipline ranging from fines and education requirements to revocation","The broker's marketing budget","Affiliated salespersons' personal finances"],
   "correctAnswer":1,
   "explanation":"Trust account audits examine compliance with state trust-account rules: (1) SEPARATE ACCOUNT — trust funds separate from operating funds (no commingling); (2) TIMELY DEPOSITS — earnest money deposited within statutory timeframes (often 2-5 business days); (3) ACCURATE RECORDS — every deposit, withdrawal, and balance documented; (4) MONTHLY RECONCILIATION — bank statements reconciled with internal records; (5) NO COMMINGLING — no broker operating funds in the trust account; (6) NO CONVERSION — no withdrawals for non-trust purposes. Failures result in: warnings, education requirements, fines, suspension, or revocation — depending on severity and pattern."},

  {"id":"re-nat-464","domain":"General Principles of Agency","type":"single-choice",
   "question":"The state real estate licensing examination typically:",
   "choices":["Has no scoring standard","Is decided by personal interview","Consists of a NATIONAL portion (covering general real estate principles tested in nearly all states) and a STATE portion (covering state-specific laws); typically scored using a SCALED or RAW score with a published passing threshold (e.g., 70-75%); both portions usually must be passed; the test is computer-based and administered by approved vendors","Is conducted only orally"],
   "correctAnswer":2,
   "explanation":"The state licensing examination structure typically: (1) NATIONAL portion (about 80 questions) — covers general real estate principles (the topics on this exam!); (2) STATE portion (about 40 questions) — covers state-specific laws, regulations, and commission rules; (3) SCORING — varies by state, but typically requires passing BOTH portions independently (e.g., 70-75% on each); (4) FORMAT — computer-based, multiple-choice, administered by approved vendors (PSI, Pearson VUE); (5) TIME — typically 2-3 hours total. Candidates failing one portion may need only retake that portion within a stated window."},

  {"id":"re-nat-465","domain":"General Principles of Agency","type":"single-choice",
   "question":"A licensee files an Errors & Omissions (E&O) claim with their insurance carrier after a consumer threatens to sue. The carrier typically:",
   "choices":["Pays the claim immediately without inquiry","Refuses all coverage","Provides only defense","INVESTIGATES the claim, defends the licensee against the lawsuit (assigning defense counsel), and indemnifies for covered losses up to the policy limits; the carrier may also try to negotiate a settlement; the licensee should NOTIFY THE CARRIER PROMPTLY after any claim, threat, or potential claim — late notice can void coverage"],
   "correctAnswer":3,
   "explanation":"E&O carrier claim handling: (1) INVESTIGATION — carrier reviews the facts, the policy, and exclusions; (2) DEFENSE — if the claim is potentially covered, the carrier provides defense counsel and pays defense costs (subject to limits and exclusions); (3) SETTLEMENT — the carrier often pursues settlement to limit exposure; (4) INDEMNIFICATION — the carrier pays covered judgments or settlements up to policy limits. KEY OBLIGATIONS FOR THE INSURED: (a) PROMPT NOTICE of any claim, threat, or potential claim (late notice can void coverage), (b) cooperation in defense, (c) no admissions or settlements without carrier consent, (d) preservation of evidence."},

  {"id":"re-nat-466","domain":"General Principles of Agency","type":"single-choice",
   "question":"A licensee facing potential discipline VOLUNTARILY SURRENDERS their license. Compared to a contested disciplinary hearing leading to revocation, voluntary surrender:",
   "choices":["May avoid an admission of misconduct (the surrender is treated as a resignation in many states), prevent the publication of detailed disciplinary findings, allow some control over the surrender's terms, AND in some cases enable easier re-licensing in the future — though it ends the license; many practitioners use voluntary surrender as part of settlement of pending matters","Has the same effect as revocation","Eliminates all civil liability","Is impossible legally"],
   "correctAnswer":0,
   "explanation":"Voluntary surrender (or relinquishment) of a license is often used as part of settlement of pending disciplinary matters. Advantages over a contested revocation: (1) NO ADMISSION of misconduct (in many states, surrender is treated as a voluntary resignation); (2) NO PUBLISHED DETAILED FINDINGS — protecting professional reputation to some degree; (3) SOME CONTROL over the surrender's terms; (4) IN SOME CASES, EASIER RE-LICENSING in the future. Voluntary surrender does not necessarily eliminate civil liability — consumers can still sue for any underlying misconduct. The strategic decision involves weighing settlement costs against contesting on the merits."},

  # ── Practice of Real Estate (7) ─────────────────────────────────────────
  {"id":"re-nat-467","domain":"Practice of Real Estate","type":"single-choice",
   "question":"IRC Section 121 provides a tax EXCLUSION for capital gains on the sale of a PRIMARY RESIDENCE. The exclusion is generally:",
   "choices":["Unlimited","UP TO $250,000 of gain for a single filer (or $500,000 for married couples filing jointly), provided the seller owned and used the home as their primary residence for at LEAST 2 of the prior 5 years; the exclusion is once every 2 years","Always $1 million","Only for first-time sellers"],
   "correctAnswer":1,
   "explanation":"IRC Section 121 (the 'primary residence exclusion') provides one of the most valuable tax benefits in real estate. Key features: (1) EXCLUSION AMOUNT — up to $250,000 of capital gain for single filers, $500,000 for married couples filing jointly; (2) OWNERSHIP TEST — owned the home for at least 2 of the prior 5 years; (3) USE TEST — used as the seller's primary residence for at least 2 of the prior 5 years (the two periods can overlap or be different); (4) FREQUENCY — can be used once every 2 years; (5) APPLIES even if the seller no longer owns the property at the time of filing (e.g., sold during the year). Significant exclusions for unforeseen circumstances (job change, health, etc.) may apply with prorated amounts."},

  {"id":"re-nat-468","domain":"Practice of Real Estate","type":"single-choice",
   "question":"A taxpayer sells a primary residence they bought 10 years ago for $200,000 and now sells for $450,000. Assuming they meet the Section 121 ownership/use tests and they're single, their TAXABLE capital gain (before considering basis adjustments and any other factors) is approximately:",
   "choices":["$250,000","$200,000","$0 — the $250,000 gain is fully excluded under Section 121 for a single filer (under the cap)","$450,000"],
   "correctAnswer":2,
   "explanation":"Step 1 — calculate raw gain: $450,000 sale price − $200,000 cost basis = $250,000 gain.\nStep 2 — apply Section 121 exclusion: single filer gets up to $250,000 excluded.\nStep 3 — taxable gain: $250,000 gain − $250,000 exclusion = $0 taxable.\nThe seller pays NO federal income tax on this gain (assuming all Section 121 tests are met). If the gain had been $300,000, only the $250,000 exclusion would apply and $50,000 would be taxable as capital gain. Section 121 is a powerful tax benefit — homeowners should track their basis (purchase price + capital improvements) and timing to maximize the exclusion."},

  {"id":"re-nat-469","domain":"Practice of Real Estate","type":"single-choice",
   "question":"On the sale of a rental property, depreciation that the owner claimed in prior years is subject to:",
   "choices":["No special treatment","Excluded from gain","Tax-free recovery","DEPRECIATION RECAPTURE — recovered depreciation is taxed at a maximum 25% rate (currently); the remainder of the gain may be taxed at long-term capital gains rates; this is sometimes called 'unrecaptured Section 1250 gain' for real property"],
   "correctAnswer":3,
   "explanation":"On the sale of a rental property, the IRS recaptures the benefit of depreciation deductions taken in prior years. For real property: 'UNRECAPTURED SECTION 1250 GAIN' is taxed at a maximum rate of 25% (currently), regardless of the seller's regular tax bracket. The remainder of the gain (excess over depreciation taken) is taxed at LONG-TERM CAPITAL GAINS rates (currently 0%, 15%, or 20% depending on income). The net effect: depreciation is a TIMING benefit, not a permanent tax savings — but with the 25% recapture cap (vs. up to 37% on ordinary income), depreciation is still typically advantageous."},

  {"id":"re-nat-470","domain":"Practice of Real Estate","type":"single-choice",
   "question":"At residential closings, the closing agent generally must:",
   "choices":["File a FORM 1099-S with the IRS reporting the sale, including the seller's name, address, taxpayer identification number (typically Social Security Number), and the gross proceeds from the sale; one copy goes to the IRS and one to the seller","Pay the seller's taxes","File a credit report","Issue a federal tax refund"],
   "correctAnswer":0,
   "explanation":"Form 1099-S (Proceeds from Real Estate Transactions) is filed by the closing agent for most residential real estate sales. The form reports: seller's name, address, taxpayer ID (SSN or ITIN), property address, date of closing, gross proceeds, and any property tax allocations. Copy A goes to the IRS, Copy B to the seller. The form helps the IRS track real estate gains and ensures sellers properly report sales on their tax returns. EXEMPTIONS include: certain primary residence sales meeting Section 121 exclusion thresholds with proper certification, and transfers between related parties or in certain other specified circumstances."},

  {"id":"re-nat-471","domain":"Practice of Real Estate","type":"single-choice",
   "question":"A buyer's wire transfer of closing funds is intercepted and redirected to a fraudster's account using a sophisticated email-based attack. This type of fraud:",
   "choices":["Is impossible in modern banking","Is exclusively a federal crime","Is a major and growing risk in real estate — known as WIRE FRAUD or 'business email compromise' (BEC); fraudsters typically gain access to email accounts of agents, attorneys, title companies, or borrowers and send fraudulent wiring instructions; losses are often UNRECOVERABLE; mitigation: verify wiring instructions by phone with a known number, use encrypted email, deploy email-security tools","Carries no legal consequences"],
   "correctAnswer":2,
   "explanation":"Wire fraud / Business Email Compromise (BEC) in real estate is a major and growing threat. Fraudsters compromise email accounts (agent, attorney, title company, or borrower) — often through phishing — then send fraudulent wiring instructions to redirect closing funds to fraudster-controlled accounts. Losses are often UNRECOVERABLE because: (1) wire transfers are difficult to reverse, (2) fraudsters quickly move funds across borders, (3) banks have limited duty to detect anomalies. MITIGATION: (a) VERIFY wiring instructions by PHONE using a number obtained from a known source (not email), (b) use encrypted email, (c) deploy email-security tools, (d) educate all parties, (e) carry cyber insurance. The FBI and FTC track BEC and provide reporting mechanisms."},

  {"id":"re-nat-472","domain":"Practice of Real Estate","type":"single-choice",
   "question":"Real estate licensees handle substantial amounts of consumer non-public personal information (financial data, transaction details, communications). Best practices for CYBERSECURITY include:",
   "choices":["Sharing passwords with colleagues","Storing client data on personal email","Using only one device for all communications","STRONG and unique passwords (often with multi-factor authentication), encrypted email for sensitive matter, secure document-handling platforms (not free unprotected cloud services), regular software/firmware updates, employee security training, INCIDENT RESPONSE plan, and cyber liability insurance"],
   "correctAnswer":3,
   "explanation":"Cybersecurity for real estate licensees should include: (1) STRONG, UNIQUE PASSWORDS with MULTI-FACTOR AUTHENTICATION (MFA); (2) ENCRYPTED EMAIL for sensitive matters (or secure document portals); (3) SECURE DOCUMENT HANDLING — not personal Gmail/Outlook free accounts for client data; (4) REGULAR UPDATES — operating systems, browsers, security software; (5) EMPLOYEE TRAINING — phishing awareness, BEC red flags, secure habits; (6) INCIDENT RESPONSE PLAN — what to do if a breach occurs; (7) CYBER LIABILITY INSURANCE — covers breach response, notification costs, regulatory fines, business interruption. State laws (CCPA, etc.) may impose specific data security obligations."},

  {"id":"re-nat-473","domain":"Practice of Real Estate","type":"single-choice",
   "question":"A consumer informs a licensee that they may be the victim of identity theft related to a real estate transaction. The licensee's response should include:",
   "choices":["Ignore the report","Promise no further action","Refer to law enforcement only","COMPREHENSIVE response: (1) advise the consumer to file a police report and an FTC complaint, (2) place a FRAUD ALERT on credit bureaus, (3) consider a CREDIT FREEZE, (4) review and document any potentially affected transactions, (5) notify relevant parties (title company, lender), (6) report the incident to the state real estate commission or relevant authorities if regulatory issues are involved"],
   "correctAnswer":3,
   "explanation":"Identity theft response in real estate context: (1) ADVISE the consumer to file a POLICE REPORT and FTC complaint (IdentityTheft.gov); (2) place a FRAUD ALERT on credit bureaus (Equifax, Experian, TransUnion); (3) consider a CREDIT FREEZE for additional protection; (4) REVIEW and DOCUMENT any potentially affected real estate transactions; (5) NOTIFY relevant parties (title company, lender, brokerage compliance) of the suspected fraud; (6) REPORT to the state real estate commission if regulatory issues may be involved; (7) preserve all relevant documents. The licensee should NOT attempt to take action that should be handled by law enforcement or identity-theft specialists — but the licensee plays a key role in alerting the consumer to risks and preserving evidence."},

  # ── Financing (5) ───────────────────────────────────────────────────────
  {"id":"re-nat-474","domain":"Financing","type":"single-choice",
   "question":"To CANCEL Private Mortgage Insurance (PMI) on a conventional loan, the borrower typically must:",
   "choices":["REQUEST cancellation in writing to the lender when LTV reaches 80% (based on the original purchase price or the original amortization schedule); have a good payment history (typically no 30-day-late payments in past 12 months); AND in some cases provide an appraisal showing the current value supports the LTV. Automatic termination occurs at 78% LTV per HPA","Pay an extra fee","Wait until the loan is paid off","Refinance the loan"],
   "correctAnswer":0,
   "explanation":"PMI cancellation rules under the Homeowners Protection Act (HPA): (1) BORROWER-REQUESTED cancellation at 80% LTV — based on the original purchase price OR the original amortization schedule (whichever produces 80% first). Borrower must have good payment history (typically no 30-day-late payments in past 12 months). Lender may require an APPRAISAL to verify current value supports the LTV; (2) AUTOMATIC termination at 78% LTV — based on the original amortization schedule; (3) MIDPOINT termination — at the loan's amortization midpoint regardless of LTV. The PMI cancellation rules apply to most conventional loans (not FHA — FHA has separate rules)."},

  {"id":"re-nat-475","domain":"Financing","type":"single-choice",
   "question":"Under TRID rules, the LOAN ESTIMATE (LE) must be delivered to the borrower:",
   "choices":["At closing","WITHIN 3 BUSINESS DAYS of the lender receiving the borrower's complete loan application — defined as containing the borrower's name, income, Social Security Number, property address, value estimate, and loan amount sought","Within 30 days of application","On the day of application"],
   "correctAnswer":1,
   "explanation":"TRID rules require the Loan Estimate (LE) within 3 BUSINESS DAYS of receiving the complete loan application. A 'complete' application contains the six required pieces: (1) borrower's name, (2) income, (3) Social Security Number, (4) property address, (5) value estimate, (6) loan amount sought. Once these six are submitted, the 3-business-day clock starts. The LE provides the borrower with the loan terms and estimated costs — replacing the former Good Faith Estimate (GFE) and Truth-in-Lending disclosure. The lender cannot collect application fees (beyond a credit report fee) before delivering the LE."},

  {"id":"re-nat-476","domain":"Financing","type":"single-choice",
   "question":"A 'Qualified Mortgage' (QM) under federal Ability-to-Repay rules generally:",
   "choices":["Has higher rates","Is a federal grant","Provides legal protections (rebuttable presumption or safe harbor of compliance with the ability-to-repay requirements) for lenders that meet specified loan structure and underwriting standards — including maximum 43% DTI ratio, no interest-only or negative amortization, limits on points and fees, and stable loan structures (no balloon payments for non-rural lenders); the QM definition limits risky loan products that contributed to the 2008 crisis","Is unregulated"],
   "correctAnswer":2,
   "explanation":"Qualified Mortgages (QMs) are loans that meet specified ability-to-repay structure standards established by the CFPB under Dodd-Frank. Standards include: (1) no negative amortization, no interest-only periods, no balloon payments (with rural lender exceptions); (2) points and fees within statutory limits (typically 3% for loans ≥$100,000); (3) loan terms ≤30 years; (4) max DTI ratio of 43% (with some flexibility); (5) verification of borrower income, assets, employment, debt; (6) underwriting based on the fully-indexed rate. Lenders making QMs receive a 'safe harbor' or 'rebuttable presumption' against ability-to-repay claims — a significant protection. The QM definition limited risky loan products that contributed to the 2008 crisis."},

  {"id":"re-nat-477","domain":"Financing","type":"single-choice",
   "question":"A 'non-QM' mortgage:",
   "choices":["Is a small loan","Is illegal","Cannot be foreclosed","Is a mortgage that does NOT meet the Qualified Mortgage definition — typically because of higher DTI, interest-only or other non-standard features, or different underwriting (e.g., bank statement loans for self-employed borrowers, asset-based loans, foreign-borrower loans); lenders making non-QM loans bear FULL ability-to-repay liability — making rigorous underwriting essential"],
   "correctAnswer":3,
   "explanation":"Non-QM (or non-Qualified Mortgage) loans don't meet the QM definition. Common reasons: (1) HIGHER DTI than 43%; (2) INTEREST-ONLY periods or other non-standard structures; (3) DIFFERENT INCOME VERIFICATION (e.g., 'bank statement loans' for self-employed borrowers who don't have traditional W-2 income); (4) ASSET-BASED qualification (using assets rather than income); (5) FOREIGN-BORROWER loans without traditional U.S. income/credit history. Lenders making non-QM loans bear FULL ability-to-repay liability — meaning they must independently demonstrate the borrower could repay. Non-QM lending fills important gaps but requires more rigorous underwriting and typically carries higher rates."},

  {"id":"re-nat-478","domain":"Financing","type":"single-choice",
   "question":"DOWN PAYMENT ASSISTANCE PROGRAMS (DPAs) — offered by state housing finance agencies, municipalities, employers, and various other sources — typically:",
   "choices":["Provide loans, grants, or forgivable second mortgages to help eligible buyers (often first-time, income-qualified, or in specific geographic areas) afford the down payment and/or closing costs; programs vary widely in eligibility, amount, and repayment terms (some are forgivable after a stated occupancy period; others are repayable on sale or refinance)","Are illegal","Apply only to commercial property","Have no eligibility requirements"],
   "correctAnswer":0,
   "explanation":"Down Payment Assistance Programs (DPAs) provide financial assistance to help buyers afford down payments and closing costs. STRUCTURES vary: (1) GRANTS — no repayment required; (2) FORGIVABLE LOANS — loans that are forgiven after a stated period of occupancy (e.g., 5-10 years); (3) DEFERRED-PAYMENT LOANS — no payments while the property is owner-occupied; (4) STANDARD SECOND MORTGAGES — payable along with the first mortgage. ELIGIBILITY commonly includes: (a) first-time homebuyer status, (b) income limits, (c) geographic restrictions, (d) HUD-approved homebuyer education, (e) primary residence requirement. SOURCES: state housing finance agencies, city/county programs, employer assistance, nonprofit organizations, military programs. DPAs are widely underutilized — buyers should investigate before purchasing."},

  # ── Real Estate Calculations (5) ────────────────────────────────────────
  {"id":"re-nat-479","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A borrower has a $300,000 30-year mortgage at 6%. After 10 years, the approximate remaining principal balance is:",
   "choices":["$300,000","About $250,910 — early mortgage payments are mostly interest, so principal paydown is slow in early years; after 10 years (1/3 of the 30-year term), only about 16-17% of principal has been paid down (vs. linear-amortization's 33%)","$200,000","$0"],
   "correctAnswer":1,
   "explanation":"This illustrates the IMPORTANT amortization curve: early payments are mostly INTEREST, with relatively little principal paydown. After 10 years on a 30-year 6% mortgage:\n• Monthly P&I ≈ $1,799\n• Total payments over 10 years ≈ $215,857\n• Interest paid in 10 years ≈ $166,750\n• Principal paid in 10 years ≈ $49,090\n• Remaining balance ≈ $250,910 (about 84% of original)\nThis is why early mortgage payments seem to make little dent in the balance — and why making extra principal payments early in the loan has outsized impact on total interest paid and loan duration."},

  {"id":"re-nat-480","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A property has annual Net Operating Income of $96,000. The MONTHLY NOI is:",
   "choices":["$96,000","$1,920","$8,000 — Monthly NOI = Annual NOI ÷ 12 = $96,000 ÷ 12 = $8,000","$24,000"],
   "correctAnswer":2,
   "explanation":"Simple conversion: Annual NOI ÷ 12 months = Monthly NOI.\n$96,000 ÷ 12 = $8,000 per month.\nThis is a common exam-style calculation testing basic financial math. Real-world note: actual monthly NOI varies due to seasonality (heating, cooling, vacation patterns, etc.), but appraisers typically work with stabilized annual figures for valuation purposes. The cap rate calculation similarly uses annual NOI (Value = Annual NOI ÷ Cap Rate)."},

  {"id":"re-nat-481","domain":"Real Estate Calculations","type":"single-choice",
   "question":"An investor expects to receive $50,000 per year for 5 years, plus a $300,000 sale at the end of year 5. At a 10% discount rate, the approximate NET PRESENT VALUE (NPV) of these cash flows is:",
   "choices":["$550,000","$330,000","$430,000","About $375,000 — NPV calculation must discount each year's cash flow back to present value at the required rate; the sum of discounted annual cash flows ($189,539) plus the discounted sale proceeds ($186,276) ≈ $375,815"],
   "correctAnswer":3,
   "explanation":"Step 1 — discount each year's $50,000 by (1.10)^N:\n• Year 1: $50,000 ÷ 1.10 = $45,455\n• Year 2: $50,000 ÷ 1.21 = $41,322\n• Year 3: $50,000 ÷ 1.331 = $37,566\n• Year 4: $50,000 ÷ 1.4641 = $34,151\n• Year 5: $50,000 ÷ 1.61051 = $31,046\nSum: ≈ $189,540 (5-year present value of annuity).\nStep 2 — discount the $300,000 sale (year 5): $300,000 ÷ 1.61051 ≈ $186,276.\nStep 3 — total NPV: $189,540 + $186,276 ≈ $375,816.\nNPV is the foundation of investment analysis — comparing projected cash flows at a required discount rate. Positive NPV means the investment exceeds the required return; negative NPV means below."},

  {"id":"re-nat-482","domain":"Real Estate Calculations","type":"single-choice",
   "question":"At closing, a buyer's $2,400 annual hazard insurance premium has been prepaid for the year and must be prorated. Using a 360-day year, closing is on day 200 of the policy. The seller is entitled to a credit for:",
   "choices":["The DAYS REMAINING in the policy year that benefit the buyer: 360 − 200 = 160 days. Daily premium = $2,400 ÷ 360 = $6.67. Credit to seller = 160 × $6.67 ≈ $1,067","$2,400","$1,333","$200"],
   "correctAnswer":0,
   "explanation":"Step 1 — daily premium: $2,400 ÷ 360 = $6.67 per day.\nStep 2 — days the seller has prepaid that benefit the buyer: 360 − 200 = 160 days.\nStep 3 — credit to seller from buyer: 160 × $6.67 ≈ $1,067.\nThe seller has prepaid for the entire policy year but will only own the property through day 200 of that year. The remaining 160 days of coverage benefit the new buyer — so the seller is reimbursed at closing for those days. This is the typical proration approach for prepaid items (insurance, taxes paid in advance, HOA dues, rent received in advance)."},

  {"id":"re-nat-483","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A 30-year $250,000 mortgage at 6% has monthly principal and interest of approximately:",
   "choices":["$1,250","$1,499 — using standard amortization formulas, the P&I payment on a 30-year $250,000 loan at 6% is approximately $1,499; the total interest paid over 30 years is approximately $289,640 — well over 100% of the original loan amount","$833","$2,083"],
   "correctAnswer":1,
   "explanation":"Step 1 — apply the mortgage payment formula:\n PMT = P × [r(1+r)^n] / [(1+r)^n − 1]\n• P = $250,000 (principal)\n• r = 0.06 / 12 = 0.005 (monthly rate)\n• n = 30 × 12 = 360 (number of payments)\nStep 2 — compute: PMT ≈ $1,499 monthly P&I.\nStep 3 — total interest over 30 years: ($1,499 × 360) − $250,000 ≈ $289,640.\nKey insight: over 30 years at 6%, the borrower pays MORE in interest ($289,640) than the original principal ($250,000)! Total payments ≈ $539,640. This is why rate matters so much and why prepaying principal can be powerful."},

  # ── Property Ownership (4) ──────────────────────────────────────────────
  {"id":"re-nat-484","domain":"Property Ownership","type":"single-choice",
   "question":"A property's MINERAL RIGHTS have been SEVERED from the surface estate (separately owned and recorded). The surface owner:",
   "choices":["Owns all minerals","Owns no surface rights","Owns the surface for surface use, but is generally subject to the mineral-rights holder's REASONABLE SURFACE USE rights to access and extract minerals (subject to surface-use agreements and statutory protections)","Has unlimited ownership"],
   "correctAnswer":2,
   "explanation":"When mineral rights are SEVERED (separately conveyed or reserved), the surface estate and mineral estate become separate legal interests. Important consequences: (1) the SURFACE OWNER owns the surface and has full surface rights for non-mining purposes; (2) the MINERAL RIGHTS HOLDER has the right to explore and extract minerals — typically including REASONABLE SURFACE USE rights to access the mineral estate; (3) the mineral-rights holder's surface use is subject to limits (statutory and contractual): surface-use agreements, reclamation requirements, notification rules, etc. In many states, the MINERAL ESTATE is the DOMINANT estate over the surface — meaning surface owners must accommodate reasonable extraction activities."},

  {"id":"re-nat-485","domain":"Property Ownership","type":"single-choice",
   "question":"A property adjacent to a river benefits from the gradual deposit of soil along the bank as the river slowly changes course. The new land is called:",
   "choices":["A reliction","An erosion","A natural divide","ALLUVION — soil deposited gradually along the bank of a watercourse; ALLUVION belongs to the riparian owner under the doctrine of ACCRETION (the gradual process by which the land was added). Sudden changes (avulsion) typically do NOT transfer ownership"],
   "correctAnswer":3,
   "explanation":"Water-related land changes and their legal effects: (1) ACCRETION — the gradual process of soil being added to land along a watercourse; ALLUVION is the soil itself; the riparian owner gains title to the alluvion; (2) RELICTION — the gradual exposure of land formerly under water (e.g., a receding lake); also adds to the riparian owner's title; (3) EROSION — gradual loss of land to water; the riparian owner loses title to the eroded portion; (4) AVULSION — sudden, dramatic changes (e.g., a river jumping its bank to a new channel during a flood); typically does NOT transfer ownership — the original boundary is preserved. The 'gradual versus sudden' distinction is critical for these doctrines."},

  {"id":"re-nat-486","domain":"Property Ownership","type":"single-choice",
   "question":"A landlocked property owner cannot reach a public road without crossing the neighbor's property. The court may grant:",
   "choices":["An easement BY NECESSITY — when a parcel is left landlocked by a partition (or sale) of a larger tract from a common owner, courts will imply an easement of access across the retained portion(s); the easement is necessary to make the conveyance meaningful","No easement","A fee simple interest","An eminent domain proceeding"],
   "correctAnswer":0,
   "explanation":"Easement by necessity (also called 'way of necessity') is implied when a parcel is left LANDLOCKED by a partition or conveyance from a common owner. Elements: (1) UNITY OF OWNERSHIP at some point in the past (both parcels were owned by the same person); (2) SEVERANCE — the parcels were divided; (3) NECESSITY — the landlocked parcel has no other access at the time of severance. The easement is implied to make the conveyance meaningful — the law presumes the parties wouldn't have intended to leave a parcel inaccessible. The easement persists as long as necessity exists; if alternate access becomes available, the necessity may end."},

  {"id":"re-nat-487","domain":"Property Ownership","type":"single-choice",
   "question":"A surface owner enters into a written SURFACE USE AGREEMENT (SUA) with the holder of severed mineral rights. The SUA typically:",
   "choices":["Eliminates the mineral rights","Specifies the parties' rights and obligations regarding surface impacts — including locations of access roads, well pads, pipelines, equipment storage; restoration obligations; surface damages payments; insurance requirements; notice procedures; and dispute resolution. Negotiated SUAs help both parties avoid disputes and litigation","Eliminates surface ownership","Requires court approval"],
   "correctAnswer":1,
   "explanation":"Surface Use Agreements (SUAs) are written contracts between surface owners and severed mineral rights holders, specifying the parties' rights and obligations. Typical SUA provisions: (1) LOCATIONS of access roads, well pads, pipelines, equipment, and operations; (2) RESTORATION obligations after operations conclude (re-vegetation, removal of equipment, soil restoration); (3) SURFACE DAMAGES PAYMENTS (sometimes called 'surface use payments') compensating the surface owner for impacts; (4) INSURANCE requirements (liability, environmental, workers' compensation); (5) NOTICE procedures before operations begin; (6) WATER USAGE limits; (7) DISPUTE RESOLUTION (mediation, arbitration). SUAs reduce disputes that would otherwise arise from open-ended mineral rights and surface ownership."},

  # ── Transfer of Title (4) ───────────────────────────────────────────────
  {"id":"re-nat-488","domain":"Transfer of Title","type":"single-choice",
   "question":"A DOCUMENTARY TRANSFER TAX (sometimes called transfer tax, conveyance tax, or stamp tax) is:",
   "choices":["A federal tax","Optional for sellers","Eliminated by federal law","A state/local tax IMPOSED on the recording of real estate conveyance documents — typically calculated as a percentage of the sale price (or sometimes a flat fee per $1,000 of consideration); rates vary by state and locality, ranging from 0% to over 2% of the sale price; typically paid by the seller (sometimes split with buyer per local custom)"],
   "correctAnswer":3,
   "explanation":"Documentary transfer taxes (variously called transfer tax, conveyance tax, stamp tax, deed tax) are state/local taxes imposed on the recording of real estate conveyance documents. Key features: (1) TAX RATE — varies widely, from 0% (some states don't have any) to over 2% of sale price (some high-tax jurisdictions like NYC, Chicago, San Francisco); (2) BASE — typically the sale price or consideration; (3) WHO PAYS — typically the seller, but can be split with the buyer per local custom; (4) WHEN PAID — at closing, typically by the closing agent who remits the tax with the recorded deed; (5) EXEMPTIONS — common exemptions for transfers between related parties, certain government transfers, etc. Buyers and sellers should understand the transfer tax in their jurisdiction."},

  {"id":"re-nat-489","domain":"Transfer of Title","type":"single-choice",
   "question":"A 'WILD DEED' is:",
   "choices":["A general warranty deed","A deed recorded with no errors","A deed recorded BUT NOT IN THE PROPER CHAIN OF TITLE — typically because it was recorded by a grantor who had no recorded title at the time (e.g., bought after recording, or never had title); subsequent title searchers may not find the wild deed using normal search methods, so it may provide no constructive notice and may not be enforceable against good-faith purchasers without notice","A deed conveying public land"],
   "correctAnswer":2,
   "explanation":"A 'wild deed' is a deed that is recorded but is NOT IN THE PROPER CHAIN OF TITLE — usually because the grantor had no recorded interest in the property at the time of recording. Examples: (1) Grantor sells before they acquire title (then later acquires title); (2) Grantor records a deed where they never had title; (3) Grantor records after they have conveyed away their interest. Title searchers using standard tract indexes (grantor-grantee indexes) may not find wild deeds. Under most recording statutes, wild deeds provide no constructive notice — and may not be enforceable against subsequent good-faith purchasers without actual notice. Wild deeds are a recurring source of title problems."},

  {"id":"re-nat-490","domain":"Transfer of Title","type":"single-choice",
   "question":"BASIC title insurance covers known title defects discovered through standard search and the policy's specified risks. EXTENDED title insurance:",
   "choices":["Covers BASIC coverage PLUS additional risks not discovered through standard search — e.g., unrecorded mechanics' liens, unrecorded easements visible upon inspection, encroachments not apparent from records, and certain matters of survey; available to buyers (typically at additional cost) for more comprehensive protection","Eliminates the need for a closing","Increases title taxes","Is unavailable to buyers"],
   "correctAnswer":0,
   "explanation":"Title insurance comes in BASIC (or 'standard') and EXTENDED (sometimes called 'enhanced' or 'ALTA Homeowner's') coverage. BASIC: covers known recorded defects in the chain of title and certain specified risks; excludes matters not in the public records. EXTENDED: ALL OF BASIC PLUS: (1) UNRECORDED MECHANICS' LIENS, (2) UNRECORDED EASEMENTS visible upon inspection, (3) ENCROACHMENTS not in records but discoverable by survey, (4) certain ZONING violations, (5) building permit violations, (6) BOUNDARY DISPUTES with neighboring owners. Extended coverage typically costs about 10-20% more than basic and is increasingly recommended for residential buyers. Choice depends on cost vs. risk tolerance and property characteristics."},

  {"id":"re-nat-491","domain":"Transfer of Title","type":"single-choice",
   "question":"At closing, the CLOSING AGENT (or settlement agent) is responsible for:",
   "choices":["Marketing the property","Negotiating the sale price","Inspecting the property","COORDINATING the actual transfer — holding earnest money in escrow, preparing closing documents and the Closing Disclosure, collecting and disbursing funds (including paying off existing mortgages, transferring purchase funds to the seller, paying transfer taxes), recording the deed and any mortgages with the county recorder, and issuing title insurance; the closing agent serves as a neutral party between buyer and seller"],
   "correctAnswer":3,
   "explanation":"The CLOSING AGENT (also called settlement agent, escrow officer, closer) is the NEUTRAL PARTY coordinating the actual transfer. Responsibilities include: (1) HOLDING earnest money and closing funds in escrow; (2) PREPARING closing documents and the Closing Disclosure (or HUD-1 for non-TRID transactions); (3) COLLECTING funds from buyer, lender, and any other sources; (4) DISBURSING funds — paying off existing mortgages, transferring purchase funds to the seller, paying transfer taxes, paying off liens, paying commissions; (5) RECORDING the deed, mortgage, and other documents with the county recorder; (6) ISSUING title insurance policies. The closing agent serves both parties — they're not advocates for either side."},

  # ── Valuation and Market Analysis (3) ───────────────────────────────────
  {"id":"re-nat-492","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"EXTERNAL OBSOLESCENCE (or economic obsolescence) is loss in value caused by factors OUTSIDE the property. A more specific subcategory is:",
   "choices":["Physical deterioration","Functional obsolescence","LOCATIONAL OBSOLESCENCE — value loss caused by negative location characteristics (nearby industrial zones, freeway noise, flood plains, neighborhood decline, undesirable neighbors); a subset of external obsolescence with location-specific cause","Internal obsolescence"],
   "correctAnswer":2,
   "explanation":"LOCATIONAL OBSOLESCENCE is a specific subset of external obsolescence — value loss caused by NEGATIVE LOCATION characteristics. Examples: (1) Adjacent industrial zone (noise, pollution, traffic); (2) Freeway or rail noise; (3) Flood plain or other natural hazard location; (4) Neighborhood DECLINE (rising crime, falling property values, business vacancy); (5) Unattractive nearby uses (waste facilities, prisons, certain commercial uses). Locational obsolescence is typically considered INCURABLE because the cause is outside the property owner's control. Appraisers measure it through paired sales analysis comparing properties in the affected area to similar properties without the negative external factors."},

  {"id":"re-nat-493","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"In the cost approach, the appraiser computes 'COST TO CURE' for curable depreciation. This is:",
   "choices":["The current market value","Eliminated from the valuation","Always the appraised value","The amount required to FIX a curable physical or functional defect — used to compute the value loss when the property is in less than ideal condition. If the cost to cure is less than the value added by the cure, the depreciation is CURABLE; if more, INCURABLE"],
   "correctAnswer":3,
   "explanation":"COST TO CURE is the amount required to fix a curable defect — physical (e.g., replacing a worn roof) or functional (e.g., adding a needed bathroom). It's used in the cost approach to compute the value loss for curable depreciation. The CURABLE/INCURABLE test: if cost to cure ≤ value added by cure, the depreciation is CURABLE (a typical buyer would invest in the cure because it pays for itself). If cost to cure > value added, the depreciation is INCURABLE (the cure doesn't pay for itself). For curable depreciation, the value loss in the cost approach is typically equal to cost to cure. For incurable, value loss is measured by other methods (typically paired-sales analysis)."},

  {"id":"re-nat-494","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"MARKETABILITY is a critical concept in real estate valuation. A property is MARKETABLE when:",
   "choices":["It can be sold to a typical buyer in a reasonable time at a price near its market value — assuming reasonable marketing, exposure to the market, and informed buyers; marketability is affected by physical condition, title, location, market conditions, and pricing; properties may have value but lack marketability (e.g., specialty properties with no local buyer pool)","It has no defects","It was built recently","It has been listed in the past"],
   "correctAnswer":0,
   "explanation":"MARKETABILITY is distinct from VALUE — a property may have a defined value but still be hard to sell. Marketability requires: (1) PROPER PRICING — close to market value; (2) ADEQUATE EXPOSURE TIME — properties priced correctly typically sell within a reasonable time (often defined as 6-12 months in residential, varies by market and property type); (3) MARKETING EFFORT — proper listing, advertising, and showing access; (4) PHYSICAL CONDITION — the property is in saleable condition; (5) TITLE — marketable title (no clouds or major issues); (6) BUYER POOL — enough potential buyers in the market. Specialty properties (large industrial, custom luxury homes, special-purpose buildings) may have value but lack marketability — they may take much longer to sell at or near market value."},

  # ── Property Disclosures (3) ────────────────────────────────────────────
  {"id":"re-nat-495","domain":"Property Disclosures","type":"single-choice",
   "question":"A buyer discovers (during the inspection period) that an existing in-ground swimming pool was built without required permits. The seller did not disclose this. The seller's typical exposure:",
   "choices":["No liability","Sellers who knew of unpermitted work and failed to disclose may face liability for misrepresentation, fraud, or breach of statutory disclosure obligations — depending on materiality, state law, and the seller's knowledge. The buyer may have remedies including damages, rescission, or being required to permit/correct the work","Federal preemption","Buyer must accept any condition"],
   "correctAnswer":1,
   "explanation":"UNPERMITTED WORK is a material defect requiring disclosure in most jurisdictions. Sellers who knew of unpermitted work and failed to disclose may face: (1) MISREPRESENTATION/FRAUD CLAIMS — particularly if questions on disclosure forms were answered falsely; (2) BREACH OF STATUTORY DISCLOSURE OBLIGATIONS under state laws; (3) RESCISSION rights for the buyer; (4) DAMAGES — including the cost to obtain after-the-fact permits, repair noncompliant work, or remove unpermitted structures. The materiality depends on the nature of the work — unpermitted electrical or major structural work is more serious than a small unpermitted shed. Code enforcement after the buyer takes possession can require expensive remediation."},

  {"id":"re-nat-496","domain":"Property Disclosures","type":"single-choice",
   "question":"In some states (notably FLORIDA), residential property disclosure requirements specifically address SINKHOLE risk because:",
   "choices":["Sinkholes are decorative","Florida has no sinkhole law","FLORIDA'S LIMESTONE GEOLOGY makes sinkhole formation common; state law requires sellers to disclose any prior sinkhole damage and any insurance claims for sinkhole damage on the property; buyers can request sinkhole inspections, and insurance availability is heavily affected by sinkhole history","Federal preemption"],
   "correctAnswer":2,
   "explanation":"Florida (and to a lesser extent other states with sinkhole-prone geology like the Carolinas, Missouri, Kentucky, and Tennessee) has SINKHOLE-SPECIFIC disclosure requirements. Florida law requires sellers to: (1) DISCLOSE any prior sinkhole damage; (2) DISCLOSE any insurance claims for sinkhole damage; (3) DISCLOSE any sinkhole investigation reports. Buyers can request sinkhole inspections during the inspection period. INSURANCE AVAILABILITY is heavily affected by sinkhole history — properties with prior sinkhole damage may be uninsurable or require expensive sinkhole-specific coverage. The limestone geology underlying Florida creates natural sinkhole risk; sinkholes can cause sudden, catastrophic property damage."},

  {"id":"re-nat-497","domain":"Property Disclosures","type":"single-choice",
   "question":"With respect to ASBESTOS in older buildings, FRIABLE asbestos (easily crumbled by hand pressure) is:",
   "choices":["Less hazardous than non-friable","Required to be removed by sellers before sale","Federally preempted","MORE HAZARDOUS — friable asbestos can readily release fibers into the air, posing significant inhalation risk; non-friable asbestos (e.g., bound in vinyl floor tiles or roofing materials) is less immediately hazardous unless disturbed; both types are regulated, and disturbance during renovation/demolition triggers federal NESHAP and OSHA requirements"],
   "correctAnswer":3,
   "explanation":"Asbestos in older buildings is categorized: (1) FRIABLE — material easily crumbled by hand pressure when dry (often pipe insulation, sprayed-on coatings, deteriorated materials); friable asbestos readily releases fibers into the air, posing significant inhalation risk; (2) NON-FRIABLE — material that does NOT crumble easily (vinyl floor tiles, roofing materials, bound asbestos cement); less immediately hazardous BUT can become friable if disturbed (sawing, sanding, removal). DISTURBANCE OF EITHER TYPE during renovation or demolition triggers federal NESHAP (National Emission Standards for Hazardous Air Pollutants) and OSHA (worker protection) requirements — including licensed abatement contractors, notification, and proper disposal. Disclosure of known asbestos is required in many states."},

  # ── Land Use Controls and Regulations (2) ───────────────────────────────
  {"id":"re-nat-498","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"A property is landlocked due to a recent partition of a larger tract. The owner has no road access. The court may grant:",
   "choices":["An EASEMENT BY NECESSITY — when a property is landlocked by a partition or conveyance from a common ownership, courts will imply an easement of access across retained land to make the conveyance meaningful; the easement persists as long as necessity exists","No easement","A fee simple interest","An eminent domain proceeding"],
   "correctAnswer":0,
   "explanation":"Easement by necessity is implied when a parcel is left landlocked by a partition or conveyance from common ownership. Elements: (1) UNITY OF OWNERSHIP at some past point (both parcels were owned by the same person); (2) SEVERANCE — the parcels were divided; (3) NECESSITY — the landlocked parcel has no other access at the time of severance. The easement is implied because the law presumes the parties wouldn't have intended to leave a parcel inaccessible. The easement persists as long as necessity exists — if alternate access becomes available, the necessity may end. The easement runs with the land."},

  {"id":"re-nat-499","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"WETLANDS regulation is enforced primarily under:",
   "choices":["State law only","No federal regulation","The Clean Water Act's Section 404 — administered by the Army Corps of Engineers (and EPA) — which requires permits for the discharge of dredged or fill material into 'waters of the United States,' including most wetlands; permits are required for activities like building, draining, or significantly altering wetlands; significant state-law wetlands protections also exist","Federal Tax Code"],
   "correctAnswer":1,
   "explanation":"WETLANDS regulation is primarily under: (1) FEDERAL CLEAN WATER ACT Section 404 — administered jointly by the Army Corps of Engineers (permits) and EPA (rule-making and enforcement); requires permits for the discharge of dredged or fill material into 'waters of the United States,' including most wetlands; (2) Section 401 — state water quality certification; (3) Many STATE WETLANDS LAWS — often providing additional protections, particularly for inland wetlands not covered by federal jurisdiction. Activities requiring permits: building, draining, dredging, filling, significant alteration of wetlands. The exact scope of jurisdiction has been subject to extensive Supreme Court litigation (Rapanos, Sackett) — current scope is more limited than past decades."},

  # ── Leasing and Property Management (1) ─────────────────────────────────
  {"id":"re-nat-500","domain":"Leasing and Property Management","type":"single-choice",
   "question":"Most state landlord-tenant laws now recognize an IMPLIED WARRANTY OF HABITABILITY in residential leases — meaning:",
   "choices":["Tenants must repair everything","Landlords have no obligations","Tenants are entitled to a property in a HABITABLE condition (free of major defects affecting health and safety: working heat, water, electricity, structurally sound, free of major pests, etc.); the warranty cannot be waived by lease; tenants may have remedies (rent withholding, repair-and-deduct, lease termination) for material breaches by the landlord","Federal preemption"],
   "correctAnswer":2,
   "explanation":"The IMPLIED WARRANTY OF HABITABILITY — recognized in most states by statute or common law — guarantees tenants the right to a property in HABITABLE condition. Habitability typically requires: (1) Working heat, water, and electricity; (2) Structural soundness (no major roof leaks, foundation issues, etc.); (3) Sanitary conditions (functional plumbing, no major pests); (4) Code compliance (smoke alarms, locks, fire exits); (5) Reasonable security. The warranty CANNOT BE WAIVED by lease — even sophisticated tenant lease language attempting to do so is typically void. Tenant remedies for material breach: (a) rent withholding (with proper procedure), (b) repair-and-deduct, (c) lease termination, (d) damages, (e) injunctive relief. Specific procedures vary by state."},
]

data.extend(new_qs)
Q.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"Written: {len(data)} questions")
