"""Real Estate National batch 12 — questions 551-600."""
import json, pathlib

Q = pathlib.Path("src/data/real-estate-national-questions.json")
data = json.loads(Q.read_text(encoding="utf-8"))

new_qs = [
  # ── Contracts (9) ───────────────────────────────────────────────────────
  {"id":"re-nat-551","domain":"Contracts","type":"single-choice",
   "question":"A licensee solicits a homeowner at their front door and convinces them to sign a listing agreement on the spot. In many states (and under federal door-to-door sales rules for certain transactions), the homeowner has a 'cooling-off' period that:",
   "choices":["Allows the consumer to cancel the agreement within a stated period (often 3 business days for in-home solicited contracts under federal law and many state laws) by delivering written notice — providing protection against high-pressure sales tactics","Eliminates all contract obligations forever","Requires court approval to cancel","Is preempted by federal law"],
   "correctAnswer":0,
   "explanation":"Cooling-off periods provide consumer protection against high-pressure sales tactics — particularly for in-home solicitations. The federal Cooling-Off Rule (16 CFR Part 429) gives consumers 3 BUSINESS DAYS to cancel certain in-home or off-site solicited sales of $25 or more. Many state real estate laws extend similar protections to listing or buyer-representation agreements signed in the consumer's home. The seller (licensee) must: (1) DELIVER WRITTEN NOTICE of the cancellation right at signing, (2) PROVIDE proper cancellation forms, (3) NOT begin performance until the cooling-off period expires. Failure to comply may extend the cancellation right indefinitely."},

  {"id":"re-nat-552","domain":"Contracts","type":"single-choice",
   "question":"A RIGHT OF FIRST REFUSAL (ROFR) differs from an OPTION TO PURCHASE in that:",
   "choices":["They are identical","An OPTION gives the optionee the right to purchase at any time during the option period at the agreed price; a ROFR is conditional — it triggers ONLY IF the owner decides to sell, requiring the owner to FIRST OFFER the property to the ROFR holder before selling to anyone else (typically at a price matching a third-party offer or per a contractual formula)","ROFR is illegal","Options eliminate seller rights"],
   "correctAnswer":1,
   "explanation":"OPTION TO PURCHASE: The optionee can EXERCISE the option at any time during the option period — unilaterally compelling the owner to sell at the agreed price. The owner is bound to sell if the optionee exercises. RIGHT OF FIRST REFUSAL (ROFR): The right is CONDITIONAL — it triggers ONLY IF the owner decides to sell. When the owner decides to sell, they must FIRST OFFER the property to the ROFR holder (typically at a price matching a bona-fide third-party offer or per a contractual formula). The ROFR holder can either accept (and purchase) or decline (allowing the owner to sell to others on those same terms). ROFRs are common in: tenant leases, commercial partnerships, family arrangements."},

  {"id":"re-nat-553","domain":"Contracts","type":"single-choice",
   "question":"An ESCALATION CLAUSE in a buyer's offer:",
   "choices":["Eliminates the offer","Forces the seller to accept","AUTOMATICALLY INCREASES the buyer's offer by a stated amount above any bona-fide competing offer the seller receives — up to a stated cap; designed to win in competitive bidding situations; common in hot markets; requires careful documentation of competing offers","Eliminates contingencies"],
   "correctAnswer":2,
   "explanation":"An ESCALATION CLAUSE automatically increases the buyer's offer by a stated amount (e.g., $5,000) above any bona-fide competing offer the seller receives — up to a stated CAP (e.g., $50,000 above original offer). Example: Buyer A offers $400,000 with $5,000 escalation up to $450,000. If Buyer B offers $420,000, Buyer A's offer escalates to $425,000. Buyer A wins unless Buyer B's offer exceeds $450,000. ADVANTAGES: lets the buyer compete without massively overpaying; demonstrates seriousness. RISKS: (1) seller may not have a true competing offer (require documentation); (2) buyer may pay more than necessary if seller doesn't disclose; (3) lender may not approve final price. Documentation of competing offers is essential."},

  {"id":"re-nat-554","domain":"Contracts","type":"single-choice",
   "question":"A BACKUP CONTRACT in a real estate transaction:",
   "choices":["Replaces the original contract","Adds requirements","Is illegal","Is a SECONDARY purchase contract — typically activated only if the FIRST contract terminates. The seller signs a backup contract with a second buyer, and the backup becomes the primary contract automatically if the first contract dies (e.g., from inspection issues, financing failure, or other termination). The backup buyer maintains their position without further negotiation"],
   "correctAnswer":3,
   "explanation":"A BACKUP CONTRACT is a secondary purchase contract that activates only if the FIRST contract terminates. PROCESS: (1) Seller signs primary contract with Buyer A; (2) Seller and Buyer B sign a backup contract — typically with terms similar to or matching Buyer A's contract; (3) If Buyer A's contract TERMINATES (inspection issues, financing failure, breach, etc.), Buyer B's backup AUTOMATICALLY becomes primary; (4) If Buyer A closes, Buyer B's backup terminates. ADVANTAGES: (a) Seller has a known backup buyer; (b) Buyer B maintains their position without further negotiation; (c) Reduces re-marketing time. RISKS: (1) Buyer B might lose interest before activation; (2) Market conditions may change. Backup contracts are common in hot markets and competitive scenarios."},

  {"id":"re-nat-555","domain":"Contracts","type":"single-choice",
   "question":"A CO-SIGNOR on a purchase contract:",
   "choices":["Agrees to be JOINTLY LIABLE with the primary borrower for the obligations under the contract — including the obligation to close the purchase, pay earnest money, and complete the transaction; co-signors are sometimes required when the primary borrower has insufficient credit, income, or other resources","Has no obligations","Eliminates the primary borrower's duties","Pays only after the primary borrower defaults"],
   "correctAnswer":0,
   "explanation":"A CO-SIGNOR on a purchase contract is JOINTLY AND SEVERALLY LIABLE with the primary borrower for all contract obligations: (1) DEPOSITING earnest money; (2) CLOSING the purchase; (3) COMPLETING any required performance. The seller can pursue EITHER OR BOTH for breach. Co-signors are sometimes required when: (a) the primary borrower has insufficient credit or income; (b) the primary borrower is a young or first-time buyer; (c) parental co-signing to help children purchase. The co-signor's credit and income are typically used in the qualification calculation. DISTINCT FROM A SURETY: surety is typically liable only AFTER the primary borrower defaults; co-signor is liable from the start. State laws and contract language affect specific obligations."},

  {"id":"re-nat-556","domain":"Contracts","type":"single-choice",
   "question":"A PERFORMANCE BOND in commercial real estate:",
   "choices":["Eliminates the contractor's obligations","Provides funds to the project owner if the CONTRACTOR FAILS to perform per the construction contract — typically issued by a surety company for a percentage of the contract value; common in commercial construction and required for many public works projects","Replaces title insurance","Acts as a personal loan"],
   "correctAnswer":1,
   "explanation":"A PERFORMANCE BOND is a SURETY INSTRUMENT issued by a surety company (typically a bond company or insurance company) that provides funds to the PROJECT OWNER if the CONTRACTOR FAILS to perform per the construction contract. KEY ELEMENTS: (1) PRINCIPAL — the contractor whose performance is bonded; (2) OBLIGEE — the project owner; (3) SURETY — the bonding company. The surety pays the obligee if the principal defaults, then pursues the principal for reimbursement. PERFORMANCE BONDS are: (a) typically issued for a percentage of the contract value (often 100% of construction cost); (b) common in commercial construction and required for many public works projects; (c) one of several bonds (payment bond, bid bond, maintenance bond) covering different risks. They reduce the owner's risk of construction failure."},

  {"id":"re-nat-557","domain":"Contracts","type":"single-choice",
   "question":"In a hold-harmless/indemnification clause, common CARVE-OUTS (exclusions from coverage) include:",
   "choices":["Routine maintenance","Inspections","Acts of the indemnitee","CLAIMS arising from the INDEMNITEE'S OWN gross negligence, willful misconduct, criminal conduct, or violations of strong public policy — courts may refuse to enforce attempts to shift liability for such conduct; clauses are also often carved out for acts predating the contract relationship and for claims by third parties unrelated to the agreement"],
   "correctAnswer":2,
   "explanation":"Hold-harmless/indemnification clauses often INCLUDE CARVE-OUTS — exclusions where the indemnitor is NOT obligated to cover the indemnitee. Common carve-outs: (1) CLAIMS arising from the INDEMNITEE'S OWN GROSS NEGLIGENCE, WILLFUL MISCONDUCT, CRIMINAL CONDUCT, or VIOLATIONS OF STRONG PUBLIC POLICY — courts in most states refuse to enforce attempts to shift liability for such conduct, and explicit carve-outs prevent unenforceability; (2) ACTS PREDATING THE CONTRACT relationship; (3) CLAIMS BY THIRD PARTIES UNRELATED TO THE AGREEMENT; (4) CLAIMS BARRED BY APPLICABLE STATUTES OF LIMITATIONS; (5) PUNITIVE DAMAGES (often excluded as a matter of public policy). Well-drafted clauses explicitly list carve-outs to avoid disputes about coverage scope."},

  {"id":"re-nat-558","domain":"Contracts","type":"single-choice",
   "question":"A licensee makes a clear and definite promise to a buyer that they will receive a specific commission rebate at closing. The buyer relies on this promise and makes other financial commitments. The licensee then refuses to honor the promise. The buyer's potential claim:",
   "choices":["No claim available","Federal claim","Criminal complaint","PROMISSORY ESTOPPEL — a quasi-contractual remedy that enforces a clear, definite promise where the promisor should have reasonably expected reliance, the promisee actually relied to their detriment, and injustice can only be avoided by enforcement; sometimes called 'detrimental reliance'"],
   "correctAnswer":3,
   "explanation":"Promissory estoppel (also called 'detrimental reliance') enforces a promise WITHOUT consideration when: (1) The promisor makes a CLEAR AND DEFINITE PROMISE; (2) The promisor should reasonably expect the promisee to rely on it; (3) The promisee ACTUALLY RELIES on it to their detriment; (4) INJUSTICE can only be avoided by enforcing the promise. Recovery is typically based on RELIANCE DAMAGES (putting the promisee in the position they would have been in had they NOT relied on the promise) — not expectation damages. The doctrine is most commonly applied in CHARITABLE PLEDGES, BUSINESS NEGOTIATIONS that fall through, and EMPLOYMENT contexts. It's used as both a SWORD (enforcing a non-contract promise) and a SHIELD (defense against assertions that a promise wasn't binding)."},

  {"id":"re-nat-559","domain":"Contracts","type":"single-choice",
   "question":"A buyer pays a seller $50,000 in earnest money on an oral agreement to purchase real estate. Despite the Statute of Frauds requirement for real estate contracts to be in writing, the buyer can sometimes ENFORCE the oral contract under exceptions like:",
   "choices":["PARTIAL PERFORMANCE — the buyer has paid substantial consideration, taken possession, and made improvements; PROMISSORY ESTOPPEL — the buyer has substantially relied on the oral promise; or ADMISSION — the seller admits the contract in court proceedings; courts vary in their willingness to enforce oral real estate contracts even with these exceptions","Federal court intervention","Sheriff's sale","Court order eliminating SoF"],
   "correctAnswer":0,
   "explanation":"Statute of Frauds exceptions for ORAL real estate contracts: (1) PART PERFORMANCE — when the buyer has: (a) PAID substantial consideration, (b) TAKEN POSSESSION of the property, AND (c) MADE IMPROVEMENTS to the property. Courts typically require all three (or strong evidence of two), demonstrating a real contract exists despite the oral nature; (2) PROMISSORY ESTOPPEL / EQUITABLE ESTOPPEL — when the buyer has substantially relied on the oral promise to their detriment, the seller may be estopped from raising the SoF defense; (3) ADMISSION — if the seller ADMITS the contract in pleadings, testimony, or interrogatories, courts may enforce. Courts VARY in their willingness to enforce oral real estate contracts — the trend is toward stricter enforcement of the writing requirement. Best practice: always have real estate contracts in writing."},

  # ── General Principles of Agency (7) ────────────────────────────────────
  {"id":"re-nat-560","domain":"General Principles of Agency","type":"single-choice",
   "question":"A seller's listing is set to expire in 10 days, but the seller has just received a serious offer. The seller wishes to extend the listing:",
   "choices":["No extension allowed","The seller and listing broker can sign a LISTING EXTENSION AMENDMENT — typically a brief written document referencing the original listing, specifying the new termination date, and signed by both parties; the original listing terms continue in force as modified; the amendment should be done BEFORE the original expiration to ensure continuous representation","Federal court approval","Automatic extension"],
   "correctAnswer":1,
   "explanation":"LISTING EXTENSIONS are accomplished by a written amendment: (1) References the original listing; (2) States the NEW TERMINATION DATE; (3) Confirms all other listing terms continue in force (or notes any modifications); (4) Signed by BOTH parties; (5) Best practice: completed BEFORE the original expires to ensure continuous representation (if a new buyer is procured during a gap, the original broker may not be entitled to commission). Many states' real estate commission rules require listing extensions to be documented in writing. Failure to properly document extensions can result in commission disputes and license violations. Extensions can be for any agreed period — common patterns are 30, 60, or 90 days."},

  {"id":"re-nat-561","domain":"General Principles of Agency","type":"single-choice",
   "question":"In real estate brokerage, the BROKERAGE itself (the firm) is typically:",
   "choices":["The principal","An employee","THE LICENSED ENTITY that contractually engages with clients (sellers, buyers); individual licensees (broker associates and salespersons) typically work AS AGENTS OF THE BROKERAGE — and the brokerage is the agent of the client; commissions flow through the brokerage; the qualifying broker is personally responsible for compliance","A federal agency"],
   "correctAnswer":2,
   "explanation":"The BROKERAGE is typically the LICENSED ENTITY that contractually engages with clients. STRUCTURE: (1) The brokerage's QUALIFYING BROKER (designated/principal broker) is personally licensed and responsible for the brokerage's compliance with real estate law; (2) Individual BROKER ASSOCIATES and SALESPERSONS work AS AGENTS OF THE BROKERAGE — affiliated through their licenses; (3) Clients contract with the BROKERAGE (typically the listing/buyer-representation agreement is between the seller/buyer and the brokerage); (4) The brokerage is the agent of the client; individual licensees are SUB-AGENTS of the brokerage; (5) Commissions flow through the brokerage; individual licensees receive compensation per their affiliation agreement. This structure has implications for vicarious liability, supervision, and licensing — and is fundamental to how the real estate industry operates."},

  {"id":"re-nat-562","domain":"General Principles of Agency","type":"single-choice",
   "question":"Multiple agency-representation models include all of the following EXCEPT:",
   "choices":["Single agency — representing one party","Dual agency — representing both parties with informed consent","Designated agency — different licensees of the same firm representing each party","ABSENTEE AGENCY — agency without any party knowing — this is NOT an actual model; agency must be disclosed and informed; undisclosed dual or any form of secret representation is generally illegal"],
   "correctAnswer":3,
   "explanation":"REAL agency-representation models in modern practice: (1) SINGLE AGENCY — representing only the seller OR only the buyer (full fiduciary duties to that one client); (2) DUAL AGENCY — representing BOTH parties with INFORMED WRITTEN CONSENT — limited fiduciary duties to both; (3) DESIGNATED AGENCY — within a single brokerage, different licensees are designated to represent each party (each licensee maintains full fiduciary duties to their designated client); (4) TRANSACTIONAL BROKERAGE (in states recognizing it) — no fiduciary relationship; broker is a neutral facilitator. UNDISCLOSED DUAL AGENCY or any form of secret representation is generally ILLEGAL — it violates fiduciary duties, exposes the licensee to license discipline, and can result in contract rescission and damages."},

  {"id":"re-nat-563","domain":"General Principles of Agency","type":"single-choice",
   "question":"At first substantive contact with a prospective client, the licensee should:",
   "choices":["DELIVER and EXPLAIN the state-required agency disclosure form — explaining the various representation options available, their respective duties, and asking the prospective client to acknowledge receipt; this is typically REQUIRED before discussing the client's confidential financial or personal information and before discussing specific properties","Ignore the requirement","Ask only for personal information","Wait until offer signing"],
   "correctAnswer":0,
   "explanation":"AGENCY DISCLOSURE AT FIRST SUBSTANTIVE CONTACT: most state real estate laws require licensees to DELIVER and EXPLAIN the agency disclosure form at the FIRST SUBSTANTIVE CONTACT with a prospective client. Required content typically includes: (1) THE VARIOUS REPRESENTATION OPTIONS available (seller agency, buyer agency, dual agency, transactional brokerage); (2) THE RESPECTIVE DUTIES owed to clients vs. customers; (3) ACKNOWLEDGMENT by the prospective client. This is typically required BEFORE: (a) discussing the prospective client's confidential financial or personal information; (b) discussing specific properties or transactions in depth; (c) entering any representation agreement. Failure to properly deliver and explain disclosure can result in: license discipline, contract challenges, and consumer-protection violations."},

  {"id":"re-nat-564","domain":"General Principles of Agency","type":"single-choice",
   "question":"A licensee handling a closing on behalf of a client typically:",
   "choices":["The licensee operates as a NEUTRAL CLOSING AGENT — coordinating, but not as the seller's or buyer's exclusive representative; in most transactions a SEPARATE CLOSING AGENT (title company, attorney, escrow company) handles the actual closing process; the licensee continues to advise their client throughout the closing but does not perform the closing function","Bills extra","Eliminates the closing agent role","Replaces the title company"],
   "correctAnswer":0,
   "explanation":"The CLOSING AGENT is typically NEUTRAL — coordinating the transaction without exclusive representation of either party. In most transactions: (1) A SEPARATE CLOSING AGENT (title company, attorney, or escrow company) handles the actual closing process — preparing documents, collecting and disbursing funds, recording deeds; (2) The LICENSEE'S role is to continue advising their client (seller or buyer) throughout the closing — coordinating with the closing agent, reviewing closing documents on the client's behalf, ensuring the closing reflects the client's interests; (3) In some states/transactions, licensees may NOT serve as the closing agent due to neutrality requirements. The closing agent owes specific duties (correct funds disbursement, accurate documentation, proper recording) — but typically not the fiduciary representation that the licensee owes their client."},

  {"id":"re-nat-565","domain":"General Principles of Agency","type":"single-choice",
   "question":"A SUB-AGENT in a real estate transaction:",
   "choices":["Always works for free","Is an unlicensed assistant","Operates without supervision","IS AN AGENT OF THE LISTING AGENT (and thus, by extension, an agent of the LISTING CLIENT) — sub-agents owe fiduciary duties to the listing client through the agency chain; the model has largely been replaced by EXPLICIT BUYER AGENCY since 1990s+ NAR reforms and 2024 NAR settlement; modern transactions typically use buyer agency rather than sub-agency"],
   "correctAnswer":3,
   "explanation":"Sub-agency: Historically, the cooperating buyer's broker was an agent of the LISTING BROKER (and thus, by extension, of the listing client) — creating a SUB-AGENT relationship. The buyer's broker owed fiduciary duties to the SELLER, not the buyer (since the seller paid all commissions). This created CONFLICTS OF INTEREST — buyers were guided by people whose loyalty was to the seller. REFORMS: (1) 1980s-1990s — state laws began allowing EXPLICIT BUYER AGENCY; (2) NAR rules eliminated automatic sub-agency in MLS systems; (3) The 2024 NAR settlement formalized that buyer brokers must have written buyer-representation agreements with their buyers. Sub-agency is now RARE in modern residential real estate practice."},

  {"id":"re-nat-566","domain":"General Principles of Agency","type":"single-choice",
   "question":"Real estate license categories in most states include:",
   "choices":["Federal only","Single license type","Random tiers","SALESPERSON (entry-level, typically requires sponsorship by a supervising broker, limited authority to negotiate without broker approval) and BROKER (advanced, more experience and education required, can operate independently or supervise others); some states also have BROKER ASSOCIATE (broker license but working under another broker's supervision)"],
   "correctAnswer":3,
   "explanation":"State real estate license categories typically include: (1) SALESPERSON (or 'sales agent') — entry-level license; requires sponsorship by a supervising BROKER; limited authority to negotiate independently without broker approval (varies by state); typical initial requirements: 60-180 hours of pre-licensing education plus exam; (2) BROKER — advanced license requiring additional experience (typically 1-3 years as a salesperson) and additional education (often 60-180+ additional hours); can operate independently, supervise salespersons, or both; (3) BROKER ASSOCIATE (in some states) — has a broker license but works under another broker's supervision (rather than operating their own brokerage). The exact terminology and requirements vary significantly by state. Some states use 'real estate agent' as a colloquial term for both salespersons and brokers."},

  # ── Practice of Real Estate (7) ─────────────────────────────────────────
  {"id":"re-nat-567","domain":"Practice of Real Estate","type":"single-choice",
   "question":"The HUD SECTION 8 housing choice voucher program:",
   "choices":["Provides RENTAL ASSISTANCE PAYMENTS to eligible low-income tenants, who pay a portion of their income toward rent (typically 30%) and the voucher covers the rest (up to a fair market rent set by HUD); voucher holders find their own private market apartments; landlords must agree to participate; many states now prohibit discrimination based on voucher status (Source of Income protections)","Eliminates rent","Pays the entire rent","Federal lottery"],
   "correctAnswer":0,
   "explanation":"The HUD Section 8 Housing Choice Voucher Program is the largest federal rental assistance program. How it works: (1) ELIGIBLE LOW-INCOME tenants receive a VOUCHER that they can use to find private market housing; (2) THE TENANT PAYS approximately 30% of their adjusted income toward rent; (3) THE VOUCHER PAYS the difference up to the local FAIR MARKET RENT (FMR) set by HUD; (4) LANDLORDS MUST AGREE to participate — accepting Section 8 voucher holders; (5) MANY STATES (and many cities) NOW PROHIBIT 'source of income' discrimination — meaning landlords cannot refuse to accept voucher holders. The program has been criticized for: lengthy waitlists, landlord reluctance to participate, and challenges in finding voucher-accepting housing in some markets."},

  {"id":"re-nat-568","domain":"Practice of Real Estate","type":"single-choice",
   "question":"Violations of the federal Lead-Based Paint Hazard Reduction Act (Title X) for pre-1978 housing can result in:",
   "choices":["No penalty","CIVIL PENALTIES up to approximately $20,000 per violation (adjusted annually for inflation), TREBLE DAMAGES in private suits by buyers, federal criminal penalties for knowing violations, and license discipline for real estate professionals; enforcement is shared between EPA and HUD","Mere warning letters","Federal court only"],
   "correctAnswer":1,
   "explanation":"Title X penalties for lead-based paint disclosure violations are substantial: (1) CIVIL PENALTIES — up to approximately $20,000 per violation (adjusted annually for inflation); (2) TREBLE DAMAGES — buyers who win a private suit recover 3X actual damages plus attorneys' fees; (3) FEDERAL CRIMINAL PENALTIES — for KNOWING OR WILLFUL violations; (4) LICENSE DISCIPLINE — state real estate commissions may discipline licensees for Title X violations; (5) RESCISSION — buyers may have rescission rights for material violations; (6) ENFORCEMENT — shared between EPA (environmental aspects) and HUD (housing aspects). REQUIRED ELEMENTS for compliant disclosure: (a) lead-based paint disclosure form, (b) EPA pamphlet 'Protect Your Family from Lead in Your Home,' (c) 10-day inspection opportunity (unless waived in writing). Real estate professionals are JOINTLY responsible with sellers for compliance."},

  {"id":"re-nat-569","domain":"Practice of Real Estate","type":"single-choice",
   "question":"A licensee receives a $10,000 referral fee but does not report it on their tax return. This is:",
   "choices":["Tax-free","No consequence","TAX FRAUD — failure to report taxable income — subject to: civil tax penalties (failure-to-file, failure-to-pay, accuracy-related, fraud penalties of up to 75% of tax owed), interest on unpaid taxes, potential CRIMINAL PROSECUTION for tax fraud (felony, with penalties up to 5 years prison + substantial fines), and license discipline if discovered","Optional reporting"],
   "correctAnswer":2,
   "explanation":"Real estate licensees must report all licensed activity income for tax purposes. Failure to report income is TAX FRAUD: (1) CIVIL PENALTIES — accuracy-related penalties of 20-40%; fraud penalties of up to 75% of underpaid tax; failure-to-file penalty of 5% per month (up to 25%); failure-to-pay penalty; INTEREST on unpaid taxes (federal short-term rate + 3%); (2) CRIMINAL PROSECUTION — tax fraud (26 USC 7201) is a felony with penalties up to 5 years imprisonment plus substantial fines; tax evasion specifically targets the deliberate concealment of income; (3) STATE TAX — separately enforceable with similar penalties; (4) LICENSE DISCIPLINE — tax fraud is grounds for state real estate license discipline (state commissions may impose suspension or revocation). 1099-MISC forms are issued for referral fees, making non-reporting easily discovered."},

  {"id":"re-nat-570","domain":"Practice of Real Estate","type":"single-choice",
   "question":"The federal CAN-SPAM ACT regulates commercial email. Real estate licensees sending email marketing must:",
   "choices":["Ignore the rules","Provide CLEAR IDENTIFICATION as commercial advertising; HONOR opt-out requests within 10 business days; INCLUDE A VALID PHYSICAL POSTAL ADDRESS in every commercial email; AVOID FALSE OR MISLEADING SUBJECT LINES; NOT USE harvested email addresses; PENALTIES up to $43,792 per email","Avoid all email","Federal court approval"],
   "correctAnswer":1,
   "explanation":"The CAN-SPAM Act (Controlling the Assault of Non-Solicited Pornography and Marketing Act of 2003) regulates COMMERCIAL EMAIL. Key requirements for real estate marketing emails: (1) IDENTIFICATION — clearly identify the email as a commercial advertisement; (2) HONEST SUBJECT LINES — no misleading or deceptive subject lines; (3) PHYSICAL ADDRESS — include a valid physical postal address; (4) OPT-OUT — include a clear opt-out mechanism (link, address); honor opt-out requests within 10 BUSINESS DAYS; do NOT charge a fee for opt-out; (5) NO HARVESTED ADDRESSES — cannot use email addresses harvested from the internet; (6) ACCURATE 'FROM' INFORMATION — must reflect the actual sender. PENALTIES: up to $43,792 per email (adjusted for inflation); enforcement by FTC, state AGs, and private suits (for ISPs)."},

  {"id":"re-nat-571","domain":"Practice of Real Estate","type":"single-choice",
   "question":"Real estate commissions and other compensation received by licensees are subject to:",
   "choices":["FEDERAL income tax (and typically state income tax) as ordinary income at the licensee's marginal tax rate; SELF-EMPLOYMENT TAX (FICA + Medicare = 15.3% on the first ~$168,600 of net earnings, plus 2.9% Medicare on the rest, plus additional Medicare tax on high earners) since most licensees are independent contractors; quarterly estimated tax payments are typically required to avoid underpayment penalties","No tax","Property tax only","Lottery tax"],
   "correctAnswer":0,
   "explanation":"Real estate licensees' compensation is heavily taxed: (1) FEDERAL INCOME TAX — at ordinary income rates (10-37% marginal); (2) STATE INCOME TAX — varies by state (no state income tax in TX, FL, NV, WA, etc.; high in CA, HI, NY); (3) SELF-EMPLOYMENT TAX — most licensees are INDEPENDENT CONTRACTORS, so they pay BOTH the employer and employee shares of FICA (Social Security 12.4% on first ~$168,600 of net earnings in 2025) and MEDICARE (2.9% on all net earnings, plus 0.9% additional Medicare tax for high earners); (4) QUARTERLY ESTIMATED TAXES — required to avoid underpayment penalties; payments made April 15, June 15, September 15, January 15. DEDUCTIBLE EXPENSES help reduce taxable income: business mileage, home office, advertising, CE, license fees, professional dues, technology, etc."},

  {"id":"re-nat-572","domain":"Practice of Real Estate","type":"single-choice",
   "question":"The Federal Trade Commission (FTC) regulates unfair and deceptive practices in commerce, including real estate. FTC enforcement tools include:",
   "choices":["Federal court only","ADMINISTRATIVE actions, federal court litigation, ASSURANCES OF DISCONTINUANCE (settlements), CONSENT DECREES (negotiated settlements with specific terms), CIVIL MONEY PENALTIES, INJUNCTIVE RELIEF, DISGORGEMENT of ill-gotten gains, and CONSUMER RESTITUTION; the FTC also coordinates with state attorneys general and other agencies","No FTC authority","Optional enforcement"],
   "correctAnswer":1,
   "explanation":"FTC enforcement tools and mechanisms include: (1) INVESTIGATIONS — civil investigative demands (CIDs) compelling document production; (2) ADMINISTRATIVE ACTIONS — Part 3 proceedings with administrative law judges; (3) FEDERAL COURT LITIGATION — Section 13(b) of the FTC Act allows preliminary injunctions and seeks damages, restitution, disgorgement; (4) ASSURANCES OF DISCONTINUANCE — informal settlements; (5) CONSENT DECREES — formal negotiated settlements with specific terms (compliance programs, monitoring, etc.); (6) CIVIL MONEY PENALTIES — for rule violations and consent decree violations; (7) INJUNCTIVE RELIEF — court orders prohibiting further violations; (8) DISGORGEMENT — turning over ill-gotten gains; (9) CONSUMER RESTITUTION — payments to victims. The FTC also COORDINATES with state attorneys general, the Consumer Financial Protection Bureau, the Department of Justice, and other federal/state agencies."},

  {"id":"re-nat-573","domain":"Practice of Real Estate","type":"single-choice",
   "question":"HUD's authority to INVESTIGATE Fair Housing Act violations includes:",
   "choices":["No investigation authority","Only voluntary cooperation","Random investigation","COMPELLING document production, INTERVIEWING parties and witnesses, REQUESTING tests by mystery shoppers, CONDUCTING administrative hearings with HUD ALJs, COORDINATING with DOJ for federal court litigation, INVESTIGATING pattern or practice complaints, and IMPOSING administrative penalties and remedies. HUD investigations can be triggered by complaints OR HUD-initiated inquiries"],
   "correctAnswer":3,
   "explanation":"HUD's Fair Housing Act investigation authority is broad. Tools: (1) DOCUMENT PRODUCTION — compelling subjects to provide documents, including business records; (2) INTERVIEWS — of complainants, respondents, witnesses; (3) TESTING — using mystery shoppers to detect discrimination; (4) ADMINISTRATIVE HEARINGS — before HUD Administrative Law Judges (ALJs); (5) DOJ REFERRAL — for federal court litigation when complainant elects; (6) PATTERN-OR-PRACTICE INVESTIGATIONS — broader systemic investigations beyond individual complaints; (7) ADMINISTRATIVE PENALTIES — civil penalties (escalating for repeat violations), damages, attorneys' fees, injunctive relief, ongoing monitoring. INVESTIGATIONS CAN BE TRIGGERED BY: (a) complaints filed within 1 year of violation; (b) HUD-initiated inquiries (especially for pattern-or-practice concerns); (c) referrals from state/local fair housing agencies."},

  # ── Financing (5) ───────────────────────────────────────────────────────
  {"id":"re-nat-574","domain":"Financing","type":"single-choice",
   "question":"The 2026 CONFORMING LOAN LIMIT for one-unit residences is set by the Federal Housing Finance Agency (FHFA) and is typically:",
   "choices":["Lower than 2024","Unchanged from 2024","Eliminated in 2026","HIGHER than 2025 — the FHFA's baseline conforming loan limit for one-unit residences in 2025 was approximately $806,500 (with adjustments in high-cost areas to ~$1.2 million); FHFA annually adjusts the limit based on the FHFA House Price Index — the 2026 limit will reflect 2025 housing price changes and was announced in late 2025"],
   "correctAnswer":3,
   "explanation":"The FHFA's CONFORMING LOAN LIMIT is the maximum loan amount eligible for purchase by Fannie Mae and Freddie Mac. 2025 limits: baseline approximately $806,500 for one-unit residences in most areas; high-cost areas up to approximately $1.2 million. The FHFA adjusts the limit annually based on changes in the FHFA House Price Index. 2026 limits will reflect 2025 housing price changes — historically, the limit increases each year as housing prices have generally risen. CONFORMING vs. JUMBO: loans above the limit are 'jumbo' and don't qualify for purchase by Fannie/Freddie — typically requiring stricter underwriting and slightly higher rates. The limits are: (1) HIGHER in HIGH-COST AREAS — counties where median home prices exceed 115% of the baseline limit; (2) PROPORTIONALLY HIGHER for 2-, 3-, and 4-unit residences."},

  {"id":"re-nat-575","domain":"Financing","type":"single-choice",
   "question":"GSE (Fannie Mae, Freddie Mac) loan-level price adjustments (LLPAs) are:",
   "choices":["RISK-BASED PRICING ADJUSTMENTS applied to conventional conforming loans by Fannie Mae and Freddie Mac — adjusting the cost of the loan based on borrower credit score, LTV, property type, occupancy, and other risk factors. LLPAs can substantially affect the borrower's effective rate or upfront points. They were significantly REVISED in 2023, with notable changes for lower-credit-score borrowers and higher LTVs","Federal grants","Random fees","Eliminated"],
   "correctAnswer":0,
   "explanation":"Loan-Level Price Adjustments (LLPAs) are RISK-BASED PRICING applied by Fannie Mae and Freddie Mac to conforming conventional loans. KEY FACTORS: (1) CREDIT SCORE — lower scores = higher LLPAs; (2) LOAN-TO-VALUE — higher LTV = higher LLPAs; (3) PROPERTY TYPE — investment property and second homes have higher LLPAs than primary residences; (4) OCCUPANCY — non-owner-occupied has higher LLPAs; (5) PROPERTY USE — manufactured homes, 2-4 unit properties have higher LLPAs; (6) CASH-OUT REFINANCE — higher LLPAs than purchases/rate-and-term. EFFECT: LLPAs are typically expressed as a percentage of loan amount that the lender pays to Fannie/Freddie — the lender typically passes this cost to the borrower through either higher interest rates or upfront points. The 2023 LLPA revisions significantly changed the structure — somewhat reducing burden on lower-credit borrowers while increasing it on higher-credit borrowers."},

  {"id":"re-nat-576","domain":"Financing","type":"single-choice",
   "question":"An ARM (Adjustable Rate Mortgage) typically has THREE caps. The 'LIFETIME CAP' or 'CEILING':",
   "choices":["Limits monthly payments","SETS THE MAXIMUM RATE the loan can ever reach over its life — typically 5-6 percentage points above the initial rate (e.g., a 5/1 ARM with an initial 4% rate and a lifetime cap of +5% can never exceed 9%); designed to prevent rate increases from creating unaffordable payments","Eliminates rate changes","Federally set"],
   "correctAnswer":1,
   "explanation":"ARMs typically have THREE caps: (1) INITIAL ADJUSTMENT CAP (sometimes the same as periodic) — limits the rate change at the FIRST adjustment after the initial fixed period; (2) PERIODIC ADJUSTMENT CAP — limits the rate change at EACH subsequent adjustment; (3) LIFETIME CAP (or 'CEILING') — sets the MAXIMUM RATE the loan can EVER reach over its life. EXAMPLE: 5/1 ARM with 2/2/5 caps and initial 4% rate: (a) After 5 years: max rate = 4% + 2% = 6% (initial cap); (b) Each subsequent annual adjustment: max change of ±2% per year (periodic cap); (c) Lifetime: max rate = 4% + 5% = 9% (lifetime cap). LIFETIME CAPS protect borrowers from catastrophic rate increases — but ARMs can still result in substantially higher payments than initial fixed-rate loans, particularly in rising rate environments."},

  {"id":"re-nat-577","domain":"Financing","type":"single-choice",
   "question":"When a borrower terminates an FHA-insured loan early (through prepayment or refinance), they may be entitled to a refund of the UNUSED PORTION of the Upfront Mortgage Insurance Premium (UFMIP). The refund:",
   "choices":["No refund","Refund of full UFMIP","Refunds the entire MIP paid","DECREASES OVER TIME — the refund is highest if the loan is paid off in the first 1-3 years; the refund is paid by FHA and is calculated based on the remaining unused portion of the original premium; if the loan was assumed (rather than paid off) by another buyer, the refund typically passes to the new owner; the policy is governed by FHA regulations and has limits"],
   "correctAnswer":3,
   "explanation":"The FHA Upfront Mortgage Insurance Premium (UFMIP) refund policy: (1) ELIGIBILITY — when an FHA loan is terminated early by prepayment or refinance; the borrower may be entitled to a refund of the UNUSED PORTION of the UFMIP; (2) AMOUNT — DECREASES OVER TIME — highest if the loan is paid off in the first 1-3 years; (3) CALCULATION — based on the remaining unused portion of the original premium; specific formula governed by FHA regulations; (4) FRESH MIP — if the loan is replaced by another FHA loan, the refund may be applied to the new loan's UFMIP; (5) ASSUMPTION — if the loan was ASSUMED (rather than paid off) by another buyer, the refund typically passes to the new owner; (6) LIMITS — the policy is governed by FHA regulations and may exclude certain situations. Borrowers considering refinance should check whether they're eligible for a UFMIP refund."},

  {"id":"re-nat-578","domain":"Financing","type":"single-choice",
   "question":"In modern residential mortgage lending under Dodd-Frank and CFPB rules, prepayment penalties are:",
   "choices":["Universal","Forbidden entirely","Always allowed","HIGHLY RESTRICTED — for QUALIFIED MORTGAGES, prepayment penalties are limited to specific circumstances and amounts (typically maximum 2% during years 1-2, 1% in year 3, and prohibited thereafter); MOST RESIDENTIAL MORTGAGES (especially QMs and government-backed loans) carry NO prepayment penalties; commercial mortgages have more flexibility"],
   "correctAnswer":3,
   "explanation":"Modern residential prepayment penalty rules: (1) FOR QUALIFIED MORTGAGES (QMs) — prepayment penalties are HEAVILY RESTRICTED: maximum 2% during years 1-2, 1% in year 3, prohibited thereafter; only certain types of QMs can have prepayment penalties; (2) FOR GOVERNMENT-BACKED LOANS — FHA, VA, USDA loans are PROHIBITED from charging prepayment penalties; (3) FOR NON-QM RESIDENTIAL LOANS — prepayment penalties are more permitted but still regulated and capped; (4) FOR COMMERCIAL MORTGAGES — much more flexibility; prepayment penalties are common, particularly with fixed-rate or interest-only loans. RATIONALE: prepayment penalties protect lenders from interest income loss but can trap borrowers in unfavorable loans. Pre-Dodd-Frank prepayment penalties were a major source of consumer harm — significant tightening followed the 2008 crisis."},

  # ── Real Estate Calculations (5) ────────────────────────────────────────
  {"id":"re-nat-579","domain":"Real Estate Calculations","type":"single-choice",
   "question":"An investor uses a 10% DISCOUNT RATE to evaluate a property. The discount rate represents:",
   "choices":["The MINIMUM ACCEPTABLE RATE OF RETURN the investor requires from the investment given its risk — used to bring future cash flows to present value; reflects the investor's opportunity cost of capital, risk tolerance, and market alternatives; HIGHER discount rates produce LOWER present values","Mortgage interest","Sales price","Random number"],
   "correctAnswer":0,
   "explanation":"The DISCOUNT RATE is the investor's MINIMUM ACCEPTABLE RATE OF RETURN given the investment's risk. It represents: (1) OPPORTUNITY COST — the return the investor could earn elsewhere with similar risk; (2) RISK PREMIUM — additional return required for taking the specific risks of the investment; (3) MARKET CONDITIONS — current rates available on alternative investments. APPLICATION: (a) Used in DISCOUNTED CASH FLOW (DCF) analysis to bring future cash flows to present value; (b) HIGHER discount rates produce LOWER present values (more conservative valuations); (c) LOWER discount rates produce HIGHER present values. SOURCES: derived from BAND-OF-INVESTMENT method (weighted average of debt and equity returns), MARKET-EXTRACTED rates from comparable transactions, or BUILD-UP method (risk-free rate + risk premia for various property-specific risks)."},

  {"id":"re-nat-580","domain":"Real Estate Calculations","type":"single-choice",
   "question":"An investment's INTERNAL RATE OF RETURN (IRR) is:",
   "choices":["The interest rate on the mortgage","The IRR is the DISCOUNT RATE at which the NET PRESENT VALUE of all cash flows from the investment equals ZERO — effectively, the EFFECTIVE COMPOUND ANNUAL RETURN over the investment period; investors compare IRR to their required return to decide if the investment meets their target","Just the cap rate","Random calculation"],
   "correctAnswer":1,
   "explanation":"INTERNAL RATE OF RETURN (IRR) is a key real estate investment metric. DEFINITION: the discount rate at which the NET PRESENT VALUE of all cash flows from the investment (initial investment plus future cash flows) equals ZERO. It represents the EFFECTIVE COMPOUND ANNUAL RETURN over the investment period. APPLICATION: (1) Investors COMPARE IRR to their REQUIRED RETURN (hurdle rate, cost of capital); (2) IRR > required return = invest; IRR < required return = pass; (3) IRR accounts for time value of money, multiple cash flow periods, and final sale proceeds. CALCULATION: typically computed using Excel's IRR function or financial calculators (manual calculation requires iterative solving). LIMITATIONS: assumes reinvestment at the IRR rate (which may not be possible); can produce misleading results with non-conventional cash flows (negative cash flows after positive ones)."},

  {"id":"re-nat-581","domain":"Real Estate Calculations","type":"single-choice",
   "question":"In year 1 of a 30-year amortizing $250,000 mortgage at 6%, total mortgage payments are $17,990. Approximately how much of this goes to PRINCIPAL?",
   "choices":["$17,990","$15,000","About $3,100 — early in a mortgage's life, the bulk of each payment is interest. Total year-1 interest is approximately $14,890 (declining outstanding balance × 6%/12 monthly); total year-1 principal is $17,990 − $14,890 ≈ $3,100, or about 17% of total payments","$0"],
   "correctAnswer":2,
   "explanation":"Step 1 — Monthly P&I on $250,000 at 6% over 30 years ≈ $1,499.\nStep 2 — Year 1 total payments: $1,499 × 12 = $17,990.\nStep 3 — Year 1 interest: declining balance × 6%/12 each month. Average balance during year 1 ≈ $248,000; total interest ≈ $248,000 × 6% × (5/6 of year) ≈ $14,890 (approximately).\nStep 4 — Year 1 principal: $17,990 − $14,890 ≈ $3,100 (about 17% of total payments).\nKey takeaway: in early mortgage years, principal paydown is SMALL relative to interest. This is the amortization curve at work. The principal portion grows each year as the outstanding balance declines — by year 30, virtually all of each payment goes to principal."},

  {"id":"re-nat-582","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A property has an ASSESSED VALUE of $300,000 and a MILL RATE of 30 mills. The property qualifies for a $20,000 homestead exemption. The annual property tax is:",
   "choices":["$8,400","$9,000","$7,600","$8,400 — Tax = (Assessed Value − Exemption) × Mill Rate / 1,000 = ($300,000 − $20,000) × 30 / 1,000 = $280,000 × 0.030 = $8,400"],
   "correctAnswer":3,
   "explanation":"Step 1 — Apply homestead exemption: $300,000 − $20,000 = $280,000 (taxable value after exemption).\nStep 2 — Convert mills to decimal: 30 mills = 30/1,000 = 0.030 (or 3%).\nStep 3 — Tax = Taxable Value × Tax Rate: $280,000 × 0.030 = $8,400.\nThis is the basic property tax calculation with a homestead exemption applied. Without the exemption: $300,000 × 0.030 = $9,000. The homestead exemption saves the homeowner $600 ($9,000 − $8,400). Homestead exemptions are typically available for owner-occupied primary residences and require homestead declaration filing in some states."},

  {"id":"re-nat-583","domain":"Real Estate Calculations","type":"single-choice",
   "question":"A comparable property sold for $500,000 with NOI of $35,000. Its derived cap rate is:",
   "choices":["8%","7% — Cap Rate = NOI ÷ Sale Price = $35,000 ÷ $500,000 = 0.07 = 7%","12%","14%"],
   "correctAnswer":1,
   "explanation":"Step 1 — Cap rate formula: Cap Rate = NOI ÷ Sale Price.\nStep 2 — Apply: $35,000 ÷ $500,000 = 0.07 = 7%.\nThis is a derived cap rate from a comparable sale — useful for valuing a subject property with similar characteristics: Subject Value = Subject NOI ÷ Derived Cap Rate. The lower the cap rate, the higher the implied value (Class A properties in prime locations typically have lower cap rates than Class C in marginal locations). Appraisers and investors look at multiple comparable cap rates to derive an appropriate rate for the subject — adjusting for differences in property quality, lease structure, tenant credit, etc."},

  # ── Property Ownership (4) ──────────────────────────────────────────────
  {"id":"re-nat-584","domain":"Property Ownership","type":"single-choice",
   "question":"Two or more parties pool resources to acquire and develop a real estate project. The legal structure may be:",
   "choices":["An individual owner only","Only a non-profit","Only a sole proprietorship","Various FORMS — joint venture (typically partnership-based), limited liability company (LLC), limited partnership (LP), corporation, real estate investment trust (REIT), or other entity; structure depends on tax goals, liability protection, governance, and project complexity; each has different tax treatment, fiduciary duty rules, and management structures"],
   "correctAnswer":3,
   "explanation":"REAL ESTATE INVESTMENT STRUCTURES include: (1) JOINT VENTURE — typically partnership-based; multiple parties contribute capital and expertise for a specific project; (2) LIMITED LIABILITY COMPANY (LLC) — popular for real estate; provides liability protection and pass-through taxation; (3) LIMITED PARTNERSHIP (LP) — general partners manage; limited partners are passive with liability limited to their investment; (4) S-CORPORATION — pass-through taxation with corporate liability protection; (5) C-CORPORATION — taxable entity (double taxation); often used for property development companies; (6) REAL ESTATE INVESTMENT TRUST (REIT) — special tax treatment; must distribute 90% of taxable income; (7) DELAWARE STATUTORY TRUST (DST) — used for 1031 exchanges in passive ownership. Structure depends on: tax goals, liability protection, governance, project complexity, exit strategy, and investor sophistication."},

  {"id":"re-nat-585","domain":"Property Ownership","type":"single-choice",
   "question":"An EXECUTORY INTEREST in property:",
   "choices":["Is permanent","Cannot be created","Equals fee simple","Is a FUTURE INTEREST in property held by a THIRD PARTY (not the grantor) that cuts short a preceding estate upon a stated event — example: 'to A so long as A operates a school on the property, then to B'; B has an executory interest; less common than remainders but recognized in property law"],
   "correctAnswer":3,
   "explanation":"EXECUTORY INTEREST is a FUTURE INTEREST in property held by a THIRD PARTY (not the grantor) that cuts short a preceding estate upon a stated event. Example: 'To A so long as A operates a school on the property, then to B and B's heirs.' Here, A has a fee simple subject to executory limitation; B has the executory interest — if A stops operating a school, B's interest vests. KEY POINTS: (1) Created in a THIRD PARTY (not the grantor); (2) Distinguished from REMAINDERS — remainders follow the natural termination of a prior estate (e.g., 'to A for life, then to B'); executory interests CUT SHORT a prior estate upon a triggering event; (3) RULE AGAINST PERPETUITIES — executory interests must vest within 21 years after a life in being at creation, or they're void; some states have abolished this rule for some interests."},

  {"id":"re-nat-586","domain":"Property Ownership","type":"single-choice",
   "question":"A grantor conveys property 'to A and her heirs, so long as the property is used for residential purposes; if it is used for anything other than residential purposes, then to grantor.' The grantor has retained a:",
   "choices":["POSSIBILITY OF REVERTER — a future interest in the grantor that takes effect AUTOMATICALLY upon the occurrence of a stated event (the property being used for non-residential purposes). The grantee A has a fee simple determinable","Fee simple absolute","Tenancy at will","Life estate"],
   "correctAnswer":0,
   "explanation":"This conveyance creates: (1) GRANTEE A: FEE SIMPLE DETERMINABLE — fee simple that AUTOMATICALLY TERMINATES upon a stated event (use becomes non-residential); (2) GRANTOR: POSSIBILITY OF REVERTER — a future interest that takes effect AUTOMATICALLY upon termination of the determinable fee. KEY POINTS: (1) Both interests are created at the same moment; (2) POSSIBILITY OF REVERTER is AUTOMATIC — the moment the triggering event occurs (non-residential use), the property reverts to the grantor without any action required; (3) DISTINGUISHED from a RIGHT OF ENTRY (also called 'power of termination'), which arises with a FEE SIMPLE SUBJECT TO CONDITION SUBSEQUENT — there, the property does NOT automatically revert; the grantor must AFFIRMATIVELY EXERCISE the right of entry to retake possession. The two structures look similar but have different operational consequences."},

  {"id":"re-nat-587","domain":"Property Ownership","type":"single-choice",
   "question":"In contrast to a possibility of reverter, a RIGHT OF ENTRY (or 'power of termination'):",
   "choices":["Cannot be created","Requires the grantor (or their heirs) to AFFIRMATIVELY EXERCISE the right after the triggering event — the property does NOT automatically revert; the grantor's right may be lost if not timely exercised; typically created with FEE SIMPLE SUBJECT TO CONDITION SUBSEQUENT (e.g., 'to A, but if used for non-residential purposes, then grantor may enter and retake')","Is the same as a remainder","Eliminates all property interests"],
   "correctAnswer":1,
   "explanation":"RIGHT OF ENTRY (also called 'power of termination') is the future interest paired with a FEE SIMPLE SUBJECT TO CONDITION SUBSEQUENT. KEY POINTS: (1) The grantor (or their heirs) must AFFIRMATIVELY EXERCISE the right after the triggering event — the property does NOT automatically revert; (2) The right typically must be exercised within a reasonable time; the grantor's right may be LOST if not timely exercised (laches, statute of limitations); (3) DISTINGUISHED from POSSIBILITY OF REVERTER (paired with fee simple determinable): possibility of reverter is automatic; right of entry requires action. EXAMPLE: 'To A and her heirs, but if used for non-residential purposes, then grantor may enter and retake the property.' Here, A has fee simple subject to condition subsequent; grantor has right of entry."},

  # ── Transfer of Title (4) ───────────────────────────────────────────────
  {"id":"re-nat-588","domain":"Transfer of Title","type":"single-choice",
   "question":"A CLOSING PROTECTION LETTER (CPL):",
   "choices":["Is a title insurance policy","Is a real estate license","Is unnecessary","Is a SEPARATE INSURANCE PRODUCT issued by a title insurance company to a lender (or sometimes the buyer) that PROTECTS AGAINST LOSSES caused by the closing agent's FRAUD, NEGLIGENCE, OR THEFT during the closing process. CPLs provide an additional layer of protection beyond the title policy itself — particularly important when the closing agent is independent of the title insurer"],
   "correctAnswer":3,
   "explanation":"CLOSING PROTECTION LETTERS (CPLs) are SEPARATE INSURANCE PRODUCTS issued by title insurance companies: (1) ISSUED TO — typically the lender (sometimes also the buyer); (2) PROTECTS AGAINST — losses from the CLOSING AGENT'S fraud, negligence, theft, or failure to follow closing instructions; (3) SCOPE — issuance of insured deed and mortgage, proper disbursement of funds, accurate recording, etc.; (4) ADDITIONAL PROTECTION — beyond the title insurance policy itself, which covers title defects but NOT necessarily closing-agent misconduct; (5) IMPORTANCE — particularly important when the closing agent is INDEPENDENT of the title insurer; (6) COST — typically nominal ($25-50 per transaction); (7) WHO REQUIRES — most lenders require CPLs for closings handled by independent closing agents; some states require CPLs by statute. Many fraud losses in real estate transactions are covered by CPLs rather than title policies."},

  {"id":"re-nat-589","domain":"Transfer of Title","type":"single-choice",
   "question":"DEEDS typically require an ACKNOWLEDGMENT (formal certification by a notary public that the grantor signed) because:",
   "choices":["No reason","Just tradition","To recover taxes","Most states require ACKNOWLEDGMENT for a deed to be ELIGIBLE FOR RECORDING in the public records; recording is essential for providing constructive notice and establishing priority; the acknowledgment confirms the grantor's identity, voluntary signing, and capacity; FAILURE TO PROPERLY ACKNOWLEDGE can prevent recording, leaving the deed valid between parties but vulnerable to subsequent claims"],
   "correctAnswer":3,
   "explanation":"DEED ACKNOWLEDGMENT requirements: (1) MOST STATES REQUIRE acknowledgment for a deed to be eligible for RECORDING in the public records; (2) RECORDING is ESSENTIAL for providing CONSTRUCTIVE NOTICE and establishing priority against subsequent good-faith purchasers; (3) THE ACKNOWLEDGMENT — typically taken by a NOTARY PUBLIC — confirms: (a) the GRANTOR'S IDENTITY, (b) the grantor's VOLUNTARY SIGNING, (c) the grantor's CAPACITY. (4) WHAT HAPPENS WITHOUT PROPER ACKNOWLEDGMENT — the deed may still be VALID BETWEEN THE GRANTOR AND GRANTEE (passing title), but it cannot be recorded; without recording, the grantee is vulnerable to subsequent claims by good-faith purchasers without notice. (5) RECORDABLE FORM REQUIREMENTS vary by state — typically including specific acknowledgment language. (6) DIGITAL/REMOTE NOTARIZATION is increasingly accepted but rules vary."},

  {"id":"re-nat-590","domain":"Transfer of Title","type":"single-choice",
   "question":"In some states, a deed requires WITNESS SIGNATURES in addition to (or as an alternative to) notary acknowledgment. State requirements:",
   "choices":["VARY SIGNIFICANTLY — some states require BOTH acknowledgment and witnesses (Florida is famous for requiring 2 witnesses + acknowledgment); other states require only acknowledgment (no witnesses); still others have specific requirements for particular types of deeds or transactions; LICENSEES must know their state's specific recording requirements to avoid invalid deeds","All states require witnesses","No state requires witnesses","Federal preemption"],
   "correctAnswer":0,
   "explanation":"WITNESS AND ACKNOWLEDGMENT REQUIREMENTS for deeds vary by state: (1) FLORIDA is famous for requiring TWO WITNESSES + NOTARY ACKNOWLEDGMENT for warranty deeds; (2) GEORGIA and several other states require ONE WITNESS + acknowledgment for some deeds; (3) MOST STATES require only NOTARY ACKNOWLEDGMENT (no witnesses); (4) PARTICULAR TRANSACTIONS — some states have specific witness requirements for specific types of deeds (e.g., quitclaim, certain spousal conveyances). LICENSEES MUST KNOW their specific state's requirements. Common mistakes include: (a) missing witness signatures in witness-required states; (b) improper acknowledgment certificates; (c) outdated forms from another state. Title insurance companies and closing agents are typically experts on local recording requirements — relying on them is essential."},

  {"id":"re-nat-591","domain":"Transfer of Title","type":"single-choice",
   "question":"An AFFIDAVIT OF TITLE (or 'seller's affidavit') signed at closing typically:",
   "choices":["Is unnecessary","Conveys title automatically","Eliminates title insurance","Is a sworn statement by the seller affirming KEY FACTS about title — including: (1) the seller is the owner; (2) there are no unrecorded liens, judgments, or claims known to the seller; (3) the seller has authority to convey; (4) no recent improvements or unpaid contractors that could give rise to mechanics' liens; (5) no recent divorce/bankruptcy/death affecting title. Used by title insurers to extend coverage for matters not in the public record"],
   "correctAnswer":3,
   "explanation":"AFFIDAVITS OF TITLE (also called 'Seller's Affidavits' or 'Owner's Affidavits') are sworn statements by the seller at closing affirming KEY FACTS about title that the title insurer cannot independently verify through public records: (1) THE SELLER IS THE OWNER and has authority to convey; (2) NO UNRECORDED LIENS, judgments, or claims known to the seller; (3) NO RECENT IMPROVEMENTS or unpaid contractors that could give rise to mechanics' liens (typically within 60-120 days of closing); (4) NO RECENT DIVORCE, BANKRUPTCY, or DEATH affecting title; (5) NO PENDING LITIGATION involving the property; (6) OCCUPANCY status (no other parties in possession); (7) IDENTITY of any parties named on the deed. The affidavit allows title insurers to EXTEND COVERAGE for matters not in the public record. FALSE STATEMENTS in the affidavit can constitute fraud and basis for criminal prosecution."},

  # ── Valuation and Market Analysis (3) ───────────────────────────────────
  {"id":"re-nat-592","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"A 'CAP RATE SPREAD' refers to:",
   "choices":["Marketing methods","The DIFFERENCE between the property's CAP RATE and a relevant BENCHMARK RATE (often the 10-year U.S. Treasury yield) — typically expressed in basis points. A wide cap rate spread suggests the investment offers a substantial premium over the risk-free rate for the inherent risks of the specific property; narrow spreads suggest pricing is aggressive (or comparable rates have risen)","Sales tax","Listing prices"],
   "correctAnswer":1,
   "explanation":"CAP RATE SPREAD: The DIFFERENCE between a property's cap rate and a relevant BENCHMARK RATE — typically the 10-year U.S. Treasury yield (representing the 'risk-free' rate). Expressed in BASIS POINTS (BPS, where 100 BPS = 1.00%). EXAMPLE: 10-year Treasury at 4.5%, retail property cap rate at 7.5% = 300 BPS spread. INTERPRETATION: (1) WIDE SPREAD = generous compensation for the property's risk vs. Treasury; investors are demanding more return; (2) NARROW SPREAD = pricing is aggressive (less margin over the risk-free rate) OR Treasury rates have risen relative to property prices. RECENT MARKET DYNAMICS: cap rate spreads compressed during low-rate periods (2010-2021); spreads widened in 2022-2023 as Treasury rates rose much faster than cap rates. Used by sophisticated investors to assess relative value across asset classes."},

  {"id":"re-nat-593","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"MARKET RENT (the rent a property could command in current market conditions) versus CONTRACT RENT (the rent actually being paid under existing leases):",
   "choices":["Are always equal","Differ when current market conditions are HIGHER or LOWER than the rent fixed in existing long-term leases; the DIFFERENCE between them — 'rent gap' — is important for investment analysis; UNDER-MARKET CONTRACT RENT (long-term leases at below-current-market rates) reduces value below stabilized market potential","Are random","Eliminate cap rates"],
   "correctAnswer":1,
   "explanation":"MARKET RENT vs. CONTRACT RENT distinction: (1) MARKET RENT — the rent a property COULD command if leased today at current market rates; reflects current demand, comparables, condition; (2) CONTRACT RENT — the rent ACTUALLY BEING PAID under existing leases; fixed at the lease start dates, often for multi-year terms; (3) DIFFERENCE: existing tenants may be paying RATES FIXED in older lease agreements that don't reflect current market conditions. UNDER-MARKET — contract rent BELOW market rent: typically when current rates have risen above original lease levels; OVER-MARKET — contract rent ABOVE market rent: typically when current rates have fallen, often during downturns. IMPLICATIONS: (a) UNDER-MARKET reduces current cash flow but creates upside as leases roll; (b) OVER-MARKET inflates current cash flow but creates downside as leases roll; (c) appraisers and investors typically use 'STABILIZED' MARKET-RENT projections for valuation, accounting for rollover."},

  {"id":"re-nat-594","domain":"Valuation and Market Analysis","type":"single-choice",
   "question":"'STABILIZED VALUE' in income property valuation refers to:",
   "choices":["The VALUE THAT THE PROPERTY WOULD HAVE AFTER REACHING STABILIZED OPERATIONS — typically meaning the property is at market-level occupancy, market rents are in place across most or all leases, and operations have settled into expected patterns. Used for properties undergoing lease-up, repositioning, or major rehabilitation","Last week's sale price","Random number","Future date"],
   "correctAnswer":0,
   "explanation":"STABILIZED VALUE is the value a property would have AFTER reaching STABILIZED OPERATIONS — typically meaning: (1) MARKET-LEVEL OCCUPANCY — typical vacancy for the property type and market (e.g., 95% occupied for typical multifamily); (2) MARKET-LEVEL RENTS — across most or all leases (reflecting current market conditions, not below-market legacy contracts); (3) STABILIZED EXPENSES — operations have settled into expected patterns; (4) STABILIZED CAP EX — reserves and capital expenditures at typical sustainable levels. USED FOR: (a) properties undergoing LEASE-UP after construction; (b) properties undergoing REPOSITIONING (e.g., conversion, major renovation); (c) properties with significant under-market rents being repositioned. CALCULATION: typically uses PROJECTED STABILIZED NOI ÷ MARKET CAP RATE. INVESTOR USE: comparing CURRENT VALUE (reflecting actual operations) vs. STABILIZED VALUE (potential post-lease-up); the difference is the 'value-add' opportunity."},

  # ── Property Disclosures (3) ────────────────────────────────────────────
  {"id":"re-nat-595","domain":"Property Disclosures","type":"single-choice",
   "question":"Some jurisdictions (and increasingly many) require ENERGY EFFICIENCY DISCLOSURES at sale or rental:",
   "choices":["No disclosure ever","Federal mandate exists","Random availability","DISCLOSURE of energy bills, energy ratings (e.g., Home Energy Score, ENERGY STAR rating), insulation/windows information, and similar data — designed to help buyers/renters understand future energy costs; cities like AUSTIN, BERKELEY, BOULDER, NEW YORK CITY, PORTLAND require such disclosures; PHILADELPHIA, CHICAGO, and others have energy benchmarking requirements for larger buildings; expanding to more jurisdictions"],
   "correctAnswer":3,
   "explanation":"ENERGY EFFICIENCY DISCLOSURES at sale or rental are required by increasingly many jurisdictions: (1) HOME ENERGY DISCLOSURES — required by AUSTIN, BERKELEY, BOULDER, NEW YORK CITY, PORTLAND, and others; typically requires: (a) recent energy bills (12 months), (b) energy ratings (Home Energy Score, BPI score, ENERGY STAR), (c) information about insulation, windows, HVAC systems, water heaters, appliances; (2) ENERGY BENCHMARKING — required for LARGER BUILDINGS in PHILADELPHIA, CHICAGO, BOSTON, and others; (3) RPP — RATING/DISCLOSURE programs are EXPANDING — many state efforts in CA, NY, OR, and others; (4) RATIONALE: helps buyers/renters understand future energy costs and the carbon footprint of their housing; (5) NON-COMPLIANCE: typically results in fines and (in some cases) blocks the sale or rental from proceeding."},

  {"id":"re-nat-596","domain":"Property Disclosures","type":"single-choice",
   "question":"A property has an in-ground SWIMMING POOL. Disclosure obligations typically include:",
   "choices":["Pool age, equipment age (pumps, filters, heaters), recent repairs, pool surface condition, any known leaks or structural issues, compliance with local pool safety codes (fencing, alarms, gates), and any known damage from extreme weather or other events; SAFETY ISSUES — diving boards, water depths, surface — may also require disclosure given liability exposure","Federal pool disclosure law","Nothing specific","Only pool color"],
   "correctAnswer":0,
   "explanation":"POOL DISCLOSURES typically include: (1) AGE — pool age and lifespan considerations; pools last 50-100 years for concrete, less for vinyl-lined; (2) EQUIPMENT AGE — pumps, filters, heaters, automation systems (typically 5-15 year lifespans); (3) RECENT REPAIRS — any work on the pool or equipment; (4) POOL SURFACE — plaster, tile, vinyl, fiberglass — age and condition; (5) LEAKS — known or suspected leaks; (6) STRUCTURAL ISSUES — cracks, settling, etc.; (7) SAFETY CODE COMPLIANCE — pool fencing, alarms, gates required by local codes; (8) WEATHER DAMAGE — from extreme weather events; (9) WATER FEATURES — water levels, depths, diving boards (with significant liability implications). SAFETY ISSUES — pool injuries and drownings are leading causes of accidental child death; disclosure of safety equipment status is critical. Insurance coverage is also significantly affected by pool presence and condition."},

  {"id":"re-nat-597","domain":"Property Disclosures","type":"single-choice",
   "question":"A buyer wants to verify property BOUNDARIES at closing. They should:",
   "choices":["Trust the listing description","Ask the neighbor","No verification needed","ORDER A SURVEY — by a licensed surveyor, typically required by lenders and recommended for buyers; the survey identifies the boundary lines, structures, encroachments, easements visible on the ground, and other physical features; surveys are typically valid for several years and provide critical information for resolving disputes"],
   "correctAnswer":3,
   "explanation":"PROPERTY SURVEYS are essential for boundary verification: (1) PERFORMED BY licensed surveyors using legal descriptions and physical measurements; (2) IDENTIFY: (a) BOUNDARY LINES — actual property corners and lines; (b) STRUCTURES — house, garage, decks, sheds in relation to boundaries; (c) ENCROACHMENTS — fences, structures, vegetation crossing boundaries; (d) EASEMENTS visible on the ground; (e) UTILITIES — overhead and underground services; (f) ANY DISPUTES — historical or apparent issues; (3) TYPES: (a) PLOT SURVEY — basic boundary identification; (b) ALTA/NSPS SURVEY — comprehensive commercial standard; (c) MORTGAGE INSPECTION (informal, sometimes accepted for residential); (4) WHEN ORDERED: typically by lenders (required for most mortgage loans), and recommended for buyers to identify potential issues before closing; (5) BENEFITS: resolve boundary disputes, identify needed easements, document encroachments, support title insurance coverage."},

  # ── Land Use Controls and Regulations (2) ───────────────────────────────
  {"id":"re-nat-598","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"RIPARIAN RIGHTS in eastern US states typically allow:",
   "choices":["REASONABLE USE of the water — including for domestic purposes, livestock watering, irrigation, and certain commercial uses — subject to the rights of other riparian owners along the same watercourse; the right is tied to the underlying land ownership; commercial diversion or large-scale use may require state permitting; rules vary by state","Unlimited use","No use at all","Federal control only"],
   "correctAnswer":0,
   "explanation":"RIPARIAN RIGHTS (in EASTERN US — water-abundant) typically allow: (1) REASONABLE USE of the water from a watercourse adjacent to one's land; (2) USES INCLUDE: domestic purposes (drinking, household), livestock watering, irrigation (with limits), small-scale commercial use; (3) SUBJECT TO RIGHTS OF OTHER RIPARIAN OWNERS — cannot unreasonably interfere with other owners' uses; (4) TIED TO LAND OWNERSHIP — the right passes with the land; cannot be separately sold; (5) COMMERCIAL DIVERSION OR LARGE-SCALE USE — may require state permitting under water-quantity laws; (6) DIFFERENT FROM WESTERN STATES — PRIOR APPROPRIATION states (mostly western) allocate water based on first-in-time priority for beneficial use, regardless of land ownership; (7) STATE-SPECIFIC VARIATIONS — some eastern states have moved toward 'regulated riparianism' with permitting; California has a hybrid system."},

  {"id":"re-nat-599","domain":"Land Use Controls and Regulations","type":"single-choice",
   "question":"ZONING ENFORCEMENT typically involves:",
   "choices":["A specific zoning enforcement official (city/county planning/code enforcement) investigating COMPLAINTS or doing routine inspections; issuing NOTICES OF VIOLATION; offering OPPORTUNITY TO CURE; escalating through ADMINISTRATIVE HEARINGS, CIVIL PENALTIES (fines, typically daily fines until cure), and ultimately COURT ACTION (injunctive relief, criminal prosecution for serious or willful violations). Property owners have due process rights to challenge violations","No enforcement","Federal action","Random enforcement"],
   "correctAnswer":0,
   "explanation":"ZONING ENFORCEMENT process: (1) DETECTION — by COMPLAINTS from neighbors or other property owners, or by ROUTINE INSPECTIONS by zoning enforcement officials; (2) NOTICE OF VIOLATION — written notice describing the violation and required correction; (3) OPPORTUNITY TO CURE — typically a stated time (often 30-60 days) to bring the property into compliance; (4) ESCALATION if not cured: (a) ADMINISTRATIVE HEARINGS before zoning boards or hearings examiners; (b) CIVIL PENALTIES — fines, typically DAILY FINES that accumulate until compliance; (c) COURT ACTION — injunctive relief, criminal prosecution for serious or willful violations; (d) RECEIVERSHIP in extreme cases. DUE PROCESS RIGHTS: property owners can challenge violations through administrative hearings and court appeals. APPLY TO: residential, commercial, and industrial property — though residential single-family zones have stricter enforcement in many jurisdictions."},

  # ── Leasing and Property Management (1) ─────────────────────────────────
  {"id":"re-nat-600","domain":"Leasing and Property Management","type":"single-choice",
   "question":"TENANT DEFENSES to a landlord's eviction (unlawful detainer) action commonly include:",
   "choices":["No defenses available","Random arguments","Federal court only","BREACH OF IMPLIED WARRANTY OF HABITABILITY by the landlord; RETALIATORY EVICTION (landlord retaliating against the tenant for exercising legal rights); LANDLORD'S WAIVER of the lease provision through accepting late rent or other course of dealing; PROCEDURAL DEFECTS in the notice or court filing; AGREEMENT to allow late payment; RACIAL OR OTHER DISCRIMINATORY motive (fair housing defense); DISCRIMINATORY motive against protected class"],
   "correctAnswer":3,
   "explanation":"TENANT DEFENSES to eviction (unlawful detainer) actions: (1) BREACH OF IMPLIED WARRANTY OF HABITABILITY by the landlord — making the premises uninhabitable; (2) RETALIATORY EVICTION — landlord retaliating against tenant for exercising legal rights (complaints to code enforcement, lawful organizing, filing housing complaints); typically illegal in most states; (3) LANDLORD'S WAIVER — landlord's acceptance of late rent, course of dealing accepting partial payments, etc., may waive lease enforcement; (4) PROCEDURAL DEFECTS — improper notice (wrong content, wrong timing, wrong delivery); improper court filing; (5) AGREEMENT to allow late payment or other accommodation; (6) DISCRIMINATORY MOTIVE — eviction targeting a protected class (race, religion, familial status, etc.) is illegal; (7) FRAUD or MISREPRESENTATION by the landlord; (8) INVALID LEASE — defect making the lease void or voidable. SUCCESSFUL defenses can result in dismissal, requiring the landlord to restart the process."},
]

data.extend(new_qs)
Q.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"Written: {len(data)} questions")
