import json

with open('src/data/comptia-net-plus-questions.json') as f:
    data = json.load(f)

batch3 = [
  {
    "id": "netplus-101",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "What is anycast addressing and how is it used in modern networking?",
    "choices": [
      "Sending a single packet to all hosts in a multicast group simultaneously",
      "Broadcasting a packet to all hosts within a subnet",
      "Assigning temporary addresses from a shared pool to new connections",
      "Assigning the same IP address to multiple nodes so that traffic is routed to the nearest one"
    ],
    "correctAnswer": 3,
    "explanation": "Anycast assigns the same IP address to multiple servers. Routers direct each client's traffic to the topologically nearest instance, enabling geographic load distribution and low-latency delivery. DNS root servers and CDN nodes use anycast extensively."
  },
  {
    "id": "netplus-102",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "Which ICMP message type (Type 3) is generated by a router or host when a destination cannot be reached?",
    "choices": [
      "Echo Request (Type 8) — used by ping to test reachability",
      "Redirect (Type 5) — tells the sender to use a better route",
      "Time Exceeded (Type 11) — sent when TTL reaches zero",
      "Destination Unreachable (Type 3) — sent when the destination host, port, or network is unavailable"
    ],
    "correctAnswer": 3,
    "explanation": "ICMP Type 3 (Destination Unreachable) informs the source that a packet could not be delivered. Sub-codes specify the reason: network unreachable, host unreachable, port unreachable, fragmentation needed but DF bit set, etc."
  },
  {
    "id": "netplus-103",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "In TCP's sliding window flow control mechanism, what does increasing the window size allow the sender to do?",
    "choices": [
      "The receiver to request retransmission of out-of-order segments",
      "The sender to transmit more data segments before waiting for an acknowledgment",
      "The network to automatically prioritize TCP over UDP traffic",
      "The router to fragment oversized segments to match the path MTU"
    ],
    "correctAnswer": 1,
    "explanation": "The TCP receive window advertises how much unacknowledged data the receiver can buffer. A larger window allows the sender to keep more data 'in flight' before stopping to wait for ACKs, increasing throughput on high-bandwidth, high-latency links."
  },
  {
    "id": "netplus-104",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "Which protocol allows routers and hosts to dynamically join and leave IPv4 multicast groups, enabling efficient multicast traffic delivery?",
    "choices": [
      "IGMP (Internet Group Management Protocol)",
      "OSPF (Open Shortest Path First)",
      "BGP (Border Gateway Protocol)",
      "VRRP (Virtual Router Redundancy Protocol)"
    ],
    "correctAnswer": 0,
    "explanation": "IGMP (RFC 3376) operates between hosts and their local routers. Hosts send IGMP Join messages to subscribe to a multicast group address (224.0.0.0/4); routers use IGMP to determine which groups have active listeners on each interface before forwarding multicast streams."
  },
  {
    "id": "netplus-105",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "A network administrator configures DSCP markings to prioritize VoIP traffic. At which OSI layer does DSCP classification operate?",
    "choices": [
      "Layer 1 (Physical) — applied to the electrical signal",
      "Layer 2 (Data Link) — stored in the 802.1p PCP field of the Ethernet header",
      "Layer 4 (Transport) — applied to the TCP/UDP header",
      "Layer 3 (Network) — stored in the Differentiated Services field of the IP header"
    ],
    "correctAnswer": 3,
    "explanation": "DSCP (Differentiated Services Code Point) occupies the upper 6 bits of the 8-bit DS field in the IPv4/IPv6 header (Layer 3). DSCP values like EF (Expedited Forwarding, 46) for VoIP or AF41 for video guide routers on how to queue and forward packets."
  },
  {
    "id": "netplus-106",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "What is the key operational difference between traffic shaping and traffic policing in QoS?",
    "choices": [
      "Traffic shaping encrypts excess traffic; policing discards it without encryption",
      "Traffic shaping buffers excess traffic to smooth it to the committed rate; policing drops or remarks excess traffic immediately",
      "Traffic shaping applies only at Layer 2 on switches; policing applies only at Layer 3 on routers",
      "Traffic shaping manages inbound traffic only; policing manages outbound traffic only"
    ],
    "correctAnswer": 1,
    "explanation": "Traffic shaping queues excess traffic in a buffer and transmits it later, smoothing bursts at the cost of added delay. Traffic policing enforces rate limits by dropping or remarking packets that exceed the defined rate, introducing no buffering delay but potentially discarding traffic."
  },
  {
    "id": "netplus-107",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "What does PAT (Port Address Translation) enable for private network hosts?",
    "choices": [
      "Translating between IPv4 and IPv6 addresses automatically at the network boundary",
      "Encrypting outbound traffic as it crosses the NAT boundary",
      "Multiple private hosts to share a single public IP address by mapping each connection to a unique source port",
      "Assigning a unique dedicated public IP address to each private host on a one-to-one basis"
    ],
    "correctAnswer": 2,
    "explanation": "PAT (also called NAT overload) maps thousands of private-address connections to a single public IP by using unique source port numbers as the differentiator. The NAT table tracks {private IP:port} ↔ {public IP:port} so return traffic is correctly translated."
  },
  {
    "id": "netplus-108",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "Which DNS record type is used for reverse DNS lookups, mapping an IP address back to a hostname?",
    "choices": [
      "A record — maps hostname to IPv4 address",
      "PTR record — maps IP address to hostname (reverse DNS)",
      "CNAME record — creates an alias pointing to another hostname",
      "AAAA record — maps hostname to IPv6 address"
    ],
    "correctAnswer": 1,
    "explanation": "PTR (Pointer) records live in the in-addr.arpa domain and map an IP address to a fully qualified hostname. For example, a PTR record for 192.0.2.10 would be at 10.2.0.192.in-addr.arpa. PTR records are used for email spam filtering and security logging."
  },
  {
    "id": "netplus-109",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "Port numbers 49152–65535 are classified as which category by IANA?",
    "choices": [
      "Well-known ports — permanently assigned to standard services by IANA",
      "Registered ports — used by vendor applications and registered with IANA",
      "Reserved ports — blocked by all stateful firewalls by default",
      "Dynamic/ephemeral ports — temporarily assigned by the OS to client-side connections"
    ],
    "correctAnswer": 3,
    "explanation": "IANA divides the 0–65535 port range into: well-known (0–1023), registered (1024–49151), and dynamic/ephemeral (49152–65535). The OS randomly selects ephemeral ports for outbound client connections and reclaims them after the session ends."
  },
  {
    "id": "netplus-110",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "Which IPv6 transition mechanism encapsulates IPv6 packets inside IPv4 packet headers to traverse IPv4-only network segments?",
    "choices": [
      "Dual-stack — running both IPv4 and IPv6 simultaneously on all interfaces",
      "NAT64 — statefully translating IPv6 addresses into IPv4 addresses",
      "IPv6-in-IPv4 tunneling (e.g., 6to4, ISATAP, or GRE tunnels)",
      "DHCPv6 — stateless address autoconfiguration using router advertisements"
    ],
    "correctAnswer": 2,
    "explanation": "Tunneling mechanisms like 6to4 (2002::/16), ISATAP, and GRE wrap IPv6 packets in an IPv4 header (protocol 41) so they can traverse IPv4 infrastructure. Dual-stack runs both protocols natively; NAT64 translates between protocol families rather than encapsulating."
  },
  {
    "id": "netplus-111",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "What is the primary function of a forward proxy server on a corporate network?",
    "choices": [
      "Assigns IP addresses to hosts on behalf of a DHCP server when the server is on a remote subnet",
      "Routes packets between autonomous systems using the BGP path-vector protocol",
      "Provides redundant default gateway functionality for LAN hosts using VRRP",
      "Forwards client requests to internet servers on behalf of clients, filtering content and caching responses to reduce bandwidth"
    ],
    "correctAnswer": 3,
    "explanation": "A forward proxy sits between internal clients and the internet, intercepting outbound requests. It can enforce content filtering policies, log user activity, and cache frequently accessed content to reduce external bandwidth consumption and improve response times."
  },
  {
    "id": "netplus-112",
    "domain": "Network Implementation",
    "type": "single-choice",
    "question": "What is the key functional difference between a switch access port and a trunk port?",
    "choices": [
      "An access port carries traffic for a single VLAN with no 802.1Q tag added; a trunk port carries multiple VLANs using 802.1Q tagging",
      "An access port routes between VLANs at Layer 3; a trunk port switches within a single VLAN at Layer 2",
      "An access port supports 10 Gbps throughput; a trunk port is limited to 1 Gbps",
      "An access port encrypts frames before transmission; a trunk port forwards them in cleartext"
    ],
    "correctAnswer": 0,
    "explanation": "Access ports connect end devices (PCs, phones, APs) and belong to a single VLAN; frames are forwarded without tags. Trunk ports (typically switch-to-switch or switch-to-router) carry tagged frames for multiple VLANs using 802.1Q encapsulation."
  },
  {
    "id": "netplus-113",
    "domain": "Network Implementation",
    "type": "single-choice",
    "question": "In the 2.4 GHz Wi-Fi band, which three channels are non-overlapping and recommended to minimize adjacent-channel interference between nearby access points?",
    "choices": [
      "Channels 1, 5, and 10",
      "Channels 2, 7, and 12",
      "Channels 1, 6, and 11",
      "Channels 3, 8, and 13"
    ],
    "correctAnswer": 2,
    "explanation": "The 2.4 GHz band has 11 usable channels in North America, each 22 MHz wide with 5 MHz spacing, meaning most channels overlap. Only channels 1, 6, and 11 are spaced far enough apart (25 MHz) to be fully non-overlapping, making them the standard choice for adjacent APs."
  },
  {
    "id": "netplus-114",
    "domain": "Network Implementation",
    "type": "single-choice",
    "question": "What is the primary difference between WPA2-Personal and WPA2-Enterprise wireless security modes?",
    "choices": [
      "WPA2-Enterprise uses a shared pre-shared key; WPA2-Personal uses 802.1X authentication",
      "WPA2-Personal uses AES-CCMP encryption; WPA2-Enterprise uses TKIP",
      "WPA2-Enterprise operates exclusively on the 5 GHz band; WPA2-Personal on 2.4 GHz",
      "WPA2-Personal authenticates with a pre-shared key (PSK); WPA2-Enterprise authenticates each user individually via 802.1X and a RADIUS server"
    ],
    "correctAnswer": 3,
    "explanation": "WPA2-Personal uses a single PSK shared among all users — if compromised, all sessions are at risk. WPA2-Enterprise uses 802.1X with EAP, allowing each user to authenticate with individual credentials or certificates verified by a RADIUS server, supporting user-level auditing and revocation."
  },
  {
    "id": "netplus-115",
    "domain": "Network Implementation",
    "type": "single-choice",
    "question": "What is the purpose of an SFP (Small Form-factor Pluggable) transceiver in a network switch?",
    "choices": [
      "Converts analog telephone signals to digital for VoIP over the LAN",
      "Provides a hot-swappable modular interface supporting different media types such as copper (1000BASE-T) or fiber (1000BASE-LX)",
      "Amplifies optical signal strength on long-distance fiber runs",
      "Delivers PoE power over the fiber connection to attached devices"
    ],
    "correctAnswer": 1,
    "explanation": "SFP (and SFP+, QSFP) transceivers plug into standardized cages on switches and routers. Each module implements a specific physical interface standard, allowing administrators to mix copper and various fiber types on the same device without hardware replacement."
  },
  {
    "id": "netplus-116",
    "domain": "Network Implementation",
    "type": "single-choice",
    "question": "In a three-tier network architecture, what is the primary role of the distribution layer?",
    "choices": [
      "Directly connects end-user devices such as workstations, IP phones, and printers to the network",
      "Provides ultra-high-speed backbone connectivity between distribution switches in the campus",
      "Aggregates access layer switches, enforces routing and security policies, and routes traffic between VLANs",
      "Connects the campus network to the internet via the WAN edge router"
    ],
    "correctAnswer": 2,
    "explanation": "The distribution layer aggregates multiple access layer switches, performs inter-VLAN routing (on a Layer 3 switch or router-on-a-stick), enforces policy (ACLs, QoS), and provides redundancy. The core layer provides high-speed backbone transit; the access layer connects end devices."
  },
  {
    "id": "netplus-117",
    "domain": "Network Implementation",
    "type": "single-choice",
    "question": "What is the key operational difference between a fat (autonomous) access point and a thin (lightweight) access point?",
    "choices": [
      "A fat AP operates independently with its own local configuration; a thin AP relies on a centralized wireless LAN controller (WLC) for management, policy, and configuration",
      "A fat AP supports only 2.4 GHz; a thin AP supports both 2.4 GHz and 5 GHz bands",
      "A thin AP processes all traffic locally; a fat AP tunnels all traffic to the WLC for switching",
      "A fat AP uses WPA3 security; a thin AP is limited to WPA2 only"
    ],
    "correctAnswer": 0,
    "explanation": "Autonomous (fat) APs are fully self-contained, each configured independently — this scales poorly in large deployments. Lightweight (thin) APs forward control and management traffic to a WLC via CAPWAP tunnels; the WLC provides centralized configuration, roaming support, and RF management."
  },
  {
    "id": "netplus-118",
    "domain": "Network Implementation",
    "type": "single-choice",
    "question": "Which overlay network technology encapsulates Layer 2 Ethernet frames in UDP packets to extend Layer 2 segments across a Layer 3 underlay, commonly used in data center virtualization?",
    "choices": [
      "VLAN trunking with 802.1Q (limited to 4094 VLANs)",
      "MPLS with traffic engineering (Layer 2.5 label switching)",
      "VXLAN (Virtual Extensible LAN) using 24-bit VNI supporting 16 million segments",
      "STP with multiple instances (MSTP) for load balancing"
    ],
    "correctAnswer": 2,
    "explanation": "VXLAN (RFC 7348) encapsulates Ethernet frames in UDP packets (port 4789), creating overlay tunnels across an IP underlay. A 24-bit VXLAN Network Identifier (VNI) enables up to 16 million virtual segments — far beyond the 4094 VLAN limit of 802.1Q — making it the standard for multi-tenant cloud data centers."
  },
  {
    "id": "netplus-119",
    "domain": "Network Implementation",
    "type": "single-choice",
    "question": "How does Cat7 cabling differ from Cat6a in its physical characteristics?",
    "choices": [
      "Cat7 supports lower maximum speeds (1 Gbps) compared to Cat6a (10 Gbps)",
      "Cat7 uses non-standard connectors (GG45 or TERA) and requires per-pair shielding (S/FTP), which limits interoperability",
      "Cat7 supports longer maximum cable runs (200 m) compared to the 100 m limit of Cat6a",
      "Cat7 operates on the same electrical specifications as Cat5e"
    ],
    "correctAnswer": 1,
    "explanation": "Cat7 is rated for 10 Gbps at 100 m and uses GG45 or TERA connectors instead of standard RJ-45, reducing plug-and-play compatibility. It requires S/FTP (shielded cable with foil around each pair) construction. Cat6a also supports 10 Gbps at 100 m but uses standard RJ-45 and is more widely deployed."
  },
  {
    "id": "netplus-120",
    "domain": "Network Operations",
    "type": "single-choice",
    "question": "What is the primary purpose of a network management system (NMS) such as SolarWinds Orion or PRTG?",
    "choices": [
      "Provides centralized real-time monitoring, alerting on thresholds, and performance reporting across the entire network infrastructure",
      "Automatically configures routing protocols on all managed devices during initial deployment",
      "Replaces all individual device CLIs with a single graphical management interface",
      "Enforces security ACLs and firewall policies across the network from a central console"
    ],
    "correctAnswer": 0,
    "explanation": "An NMS collects performance data (via SNMP, streaming telemetry, or agents), monitors device health and interface utilization, generates alerts when thresholds are exceeded, and produces trend reports for capacity planning. It provides visibility across the infrastructure without requiring per-device manual polling."
  },
  {
    "id": "netplus-121",
    "domain": "Network Operations",
    "type": "single-choice",
    "question": "A Wireshark capture uses the display filter ip.addr == 10.1.1.50. What traffic will this filter show?",
    "choices": [
      "Only packets where 10.1.1.50 is the source IP address",
      "Only packets where 10.1.1.50 is the destination IP address",
      "All packets where 10.1.1.50 appears as either the source or destination IP address",
      "Only ICMP packets to or from 10.1.1.50"
    ],
    "correctAnswer": 2,
    "explanation": "ip.addr is a Wireshark shorthand that matches on both the source and destination IP fields using an OR condition: ip.src == 10.1.1.50 OR ip.dst == 10.1.1.50. To restrict to source only, use ip.src == 10.1.1.50; for destination only, ip.dst == 10.1.1.50."
  },
  {
    "id": "netplus-122",
    "domain": "Network Operations",
    "type": "single-choice",
    "question": "What does MTBF (Mean Time Between Failures) measure in network operations?",
    "choices": [
      "The average time a device or component operates without failing — a reliability indicator",
      "The average time required to repair a failed component and restore normal service",
      "The maximum acceptable downtime defined in a service-level agreement",
      "The interval between when a fault is detected and when it is escalated to management"
    ],
    "correctAnswer": 0,
    "explanation": "MTBF measures device reliability: a higher MTBF means longer periods between failures and greater reliability. MTTR (Mean Time To Repair) measures recovery speed. Together, MTBF and MTTR determine availability: Availability = MTBF / (MTBF + MTTR)."
  },
  {
    "id": "netplus-123",
    "domain": "Network Operations",
    "type": "single-choice",
    "question": "What is the purpose of a network operations runbook?",
    "choices": [
      "A regulatory compliance document defining audit requirements for the network",
      "A real-time dashboard displaying current link utilization and device health",
      "An automated log of all configuration changes applied to network devices",
      "A step-by-step procedural guide for performing common operational tasks and responding to incidents consistently"
    ],
    "correctAnswer": 3,
    "explanation": "A runbook documents specific operational procedures — how to restart a service, respond to a specific alert, or execute a failover — so that any team member can follow the steps without relying on tacit knowledge. Runbooks reduce errors and ensure consistent responses to recurring situations."
  },
  {
    "id": "netplus-124",
    "domain": "Network Operations",
    "type": "single-choice",
    "question": "A DHCP lease time is configured at 72 hours on a public Wi-Fi network serving hundreds of transient visitors per day with a pool of 200 addresses. What is the most likely consequence?",
    "choices": [
      "The DHCP pool may be exhausted because visitors who have left still hold leases for up to 72 hours",
      "Visiting devices will receive duplicate IP addresses due to rapid churn in the address pool",
      "Devices that remain connected will be unable to renew their lease automatically",
      "The DHCP server will crash from processing an excessive number of renewal requests"
    ],
    "correctAnswer": 0,
    "explanation": "With long lease times and a small pool, departed devices hold their leases for up to 72 hours. New arrivals may exhaust the available addresses before those leases expire. For high-turnover environments, short lease times (1–8 hours) ensure addresses return to the pool quickly."
  },
  {
    "id": "netplus-125",
    "domain": "Network Operations",
    "type": "single-choice",
    "question": "What is the purpose of the TTL value on a DNS resource record?",
    "choices": [
      "Controls how long resolvers and clients may cache the record before re-querying the authoritative nameserver",
      "Specifies the maximum number of recursive hops a DNS query may traverse",
      "Sets the session timeout for the connection between a DNS resolver and client",
      "Defines the maximum duration allowed for a full DNS zone transfer to complete"
    ],
    "correctAnswer": 0,
    "explanation": "DNS TTL (Time to Live) tells caching resolvers and clients how long to store the answer before fetching a fresh copy. Short TTLs (e.g., 60 s) allow rapid propagation of changes; long TTLs (e.g., 86400 s) reduce query load on authoritative servers but slow change propagation."
  },
  {
    "id": "netplus-126",
    "domain": "Network Security",
    "type": "single-choice",
    "question": "Which wireless security protocol is considered cryptographically broken and should never be used on modern networks?",
    "choices": [
      "WPA2 with AES-CCMP",
      "WEP (Wired Equivalent Privacy) — RC4-based, broken by practical attacks",
      "WPA3 with SAE (Simultaneous Authentication of Equals)",
      "WPA with TKIP (Temporal Key Integrity Protocol)"
    ],
    "correctAnswer": 1,
    "explanation": "WEP uses RC4 with a static key and a 24-bit IV that repeats quickly, making it vulnerable to passive attacks that recover the key in minutes. Tools like Aircrack-ng can crack WEP with as few as 40,000 captured packets. WEP was deprecated by IEEE in 2004."
  },
  {
    "id": "netplus-127",
    "domain": "Network Security",
    "type": "single-choice",
    "question": "What attack does Dynamic ARP Inspection (DAI) protect against?",
    "choices": [
      "MAC flooding attacks that overflow the switch CAM table",
      "Rogue DHCP servers injecting malicious gateway configurations",
      "ARP spoofing attacks where a malicious host sends false ARP replies to poison caches and redirect traffic",
      "STP root bridge attacks triggered by unauthorized BPDUs"
    ],
    "correctAnswer": 2,
    "explanation": "DAI validates ARP packets against the DHCP snooping binding table. If an ARP reply's sender IP/MAC pairing does not match the binding table entry for that port, the packet is dropped, preventing an attacker from poisoning ARP caches and intercepting traffic destined for legitimate hosts."
  },
  {
    "id": "netplus-128",
    "domain": "Network Security",
    "type": "single-choice",
    "question": "Which VLAN hopping attack exploits a switch port configured with DTP in auto or desirable mode?",
    "choices": [
      "Switch spoofing — the attacker sends DTP negotiation frames to form a trunk and access all VLANs",
      "Double-tagging — the attacker nests two 802.1Q tags to send frames into a different VLAN",
      "ARP poisoning within the native VLAN to capture cross-VLAN traffic",
      "DHCP starvation targeting a specific VLAN's address pool"
    ],
    "correctAnswer": 0,
    "explanation": "In switch spoofing, an attacker's device sends DTP frames pretending to be a switch, causing the access port to negotiate into trunk mode. Once trunked, the attacker can send and receive traffic on any VLAN. Mitigation: disable DTP on all access ports (switchport nonegotiate) and use switchport mode access."
  },
  {
    "id": "netplus-129",
    "domain": "Network Security",
    "type": "single-choice",
    "question": "What is the purpose of a site-to-site VPN?",
    "choices": [
      "Allows individual remote users to securely tunnel into the corporate network from home over the internet",
      "Provides a persistent encrypted tunnel connecting two or more geographically separated office networks over the internet",
      "Encrypts wireless traffic between an 802.11 access point and a mobile device",
      "Creates logical VLAN segmentation between internal department networks"
    ],
    "correctAnswer": 1,
    "explanation": "A site-to-site VPN (typically IPsec) permanently connects two or more networks via an encrypted tunnel across the internet, making remote offices appear as extensions of the main network. Remote-access VPN, by contrast, connects individual user devices to the corporate network on demand."
  },
  {
    "id": "netplus-130",
    "domain": "Network Security",
    "type": "single-choice",
    "question": "Which switch security feature prevents IP address spoofing by validating that traffic arriving on an access port matches the DHCP snooping binding for that port's IP address?",
    "choices": [
      "DHCP Snooping — blocks rogue DHCP servers",
      "Dynamic ARP Inspection (DAI) — validates ARP packets against bindings",
      "Port Security — limits MAC addresses per port",
      "IP Source Guard — filters packets whose source IP does not match the DHCP binding for that port"
    ],
    "correctAnswer": 3,
    "explanation": "IP Source Guard uses the DHCP snooping binding table (which records the {IP, MAC, VLAN, port} tuple) to filter packets. Any traffic with a source IP that was not assigned by DHCP to that port is dropped, blocking IP address spoofing attacks at Layer 3."
  },
  {
    "id": "netplus-131",
    "domain": "Network Troubleshooting",
    "type": "single-choice",
    "question": "A switch interface counter shows an increasing count of runt frames. What does a runt frame indicate?",
    "choices": [
      "A frame exceeding the maximum Ethernet frame size of 1518 bytes (or 1522 with 802.1Q)",
      "A frame containing a mismatched 802.1Q VLAN tag sent on an access port",
      "A frame containing an IP-layer checksum error detected by the upstream router",
      "A frame smaller than the minimum 64-byte Ethernet size, typically caused by a collision or faulty NIC/cable"
    ],
    "correctAnswer": 3,
    "explanation": "Runts are Ethernet frames shorter than 64 bytes (the minimum including header, data, and FCS). They are usually caused by collisions (which corrupt frames mid-transmission), hardware faults, or duplex mismatches. Giants exceed the maximum frame size. Both are Layer 1/2 indicators of physical problems."
  },
  {
    "id": "netplus-132",
    "domain": "Network Troubleshooting",
    "type": "single-choice",
    "question": "An administrator reports high packet loss and jitter on VoIP calls, but data transfers on the same link are unaffected. What is the most likely cause?",
    "choices": [
      "The VoIP phones have faulty Ethernet cables causing intermittent link failures",
      "QoS is not configured, causing VoIP UDP packets to compete equally with bulk data TCP for bandwidth",
      "The switch has a VLAN misconfiguration that is incorrectly isolating VoIP traffic",
      "The VoIP call manager server is located on the wrong subnet and traffic must traverse an extra router"
    ],
    "correctAnswer": 1,
    "explanation": "VoIP is highly sensitive to delay, jitter, and packet loss. Without QoS, VoIP packets compete with TCP bulk transfers (file downloads, backups) in the same queue. When a large TCP burst fills the interface buffer, VoIP packets are delayed or dropped, causing audio degradation. Configuring LLQ (Low Latency Queuing) or DSCP EF prioritization resolves this."
  },
  {
    "id": "netplus-133",
    "domain": "Network Troubleshooting",
    "type": "single-choice",
    "question": "A router interface counter shows rapidly incrementing input errors. Which two physical layer conditions most commonly cause input errors on a router interface?",
    "choices": [
      "MTU mismatches causing oversized frame drops, or duplex mismatches generating CRC/FCS errors at ingress",
      "An incorrect default gateway configured on hosts connected to that interface",
      "OSPF neighbor adjacency failures causing routing protocol packets to be dropped",
      "Spanning tree topology changes on directly connected switches"
    ],
    "correctAnswer": 0,
    "explanation": "Input errors include CRC errors (bad FCS from duplex mismatches, corrupted cables), giants (MTU exceeded), and runts (collisions from duplex issues). They are Layer 1/2 indicators — physical cable quality, duplex settings, and MTU configuration are the first troubleshooting targets."
  },
  {
    "id": "netplus-134",
    "domain": "Network Troubleshooting",
    "type": "single-choice",
    "question": "A technician suspects an MTU mismatch on a network path. Which symptom is most characteristic of an MTU mismatch?",
    "choices": [
      "Complete loss of connectivity for all traffic in both directions",
      "Large packets (over ~1400 bytes) are dropped while small packets such as ICMP pings succeed",
      "DNS name resolution fails while HTTP traffic to known IP addresses succeeds",
      "Only UDP traffic is affected; TCP connections negotiate around the issue using MSS clamping"
    ],
    "correctAnswer": 1,
    "explanation": "MTU mismatches cause large packets to be dropped when a segment in the path has a lower MTU and the DF (Don't Fragment) bit is set. Small packets (like ping with default 32-byte data) fit within any MTU and pass fine. Black hole routers that drop oversized packets without sending ICMP Fragmentation Needed messages are a common cause."
  },
  {
    "id": "netplus-135",
    "domain": "Network Troubleshooting",
    "type": "single-choice",
    "question": "An EtherChannel (LACP) bundle has one member port in a 'suspended' state. What is the most likely cause?",
    "choices": [
      "The port is in STP blocking state due to a spanning tree topology change on the segment",
      "A configuration mismatch between EtherChannel member ports — speed, duplex, or allowed VLANs differ",
      "The upstream router does not support IEEE 802.3ad link aggregation",
      "The connected device does not have sufficient PoE budget to power both member ports simultaneously"
    ],
    "correctAnswer": 1,
    "explanation": "LACP suspends a member port when it detects a mismatch between the local and remote port parameters (speed, duplex, native VLAN, allowed VLANs, or port-channel mode). All member ports in an EtherChannel must share identical configuration. Check show etherchannel summary for mismatched flags."
  },
  {
    "id": "netplus-136",
    "domain": "Network Troubleshooting",
    "type": "single-choice",
    "question": "A wireless client shows a strong RSSI signal (-55 dBm) but experiences very slow throughput. Which condition is the most likely cause?",
    "choices": [
      "The client is too far from the access point for reliable signal reception",
      "The AP is correctly using a non-overlapping channel with no adjacent interference",
      "Co-channel interference from neighboring APs broadcasting on the same channel",
      "The client's wireless adapter does not support the MIMO antenna configuration of the AP"
    ],
    "correctAnswer": 2,
    "explanation": "Strong signal with poor throughput is a classic co-channel interference (CCI) symptom. When multiple APs in range use the same channel, they must defer to each other's transmissions (CSMA/CA), increasing contention and reducing effective throughput even though signal strength is high. The fix is AP channel planning with proper separation."
  },
  {
    "id": "netplus-137",
    "domain": "Network Troubleshooting",
    "type": "single-choice",
    "question": "What does a Time Domain Reflectometer (TDR) do when testing a copper cable?",
    "choices": [
      "Measures optical signal loss in decibels along a fiber run",
      "Identifies the distance to a cable fault (open or short) by measuring the time for a transmitted pulse to reflect back",
      "Verifies the wire mapping and pin continuity of a patch cable end-to-end",
      "Measures the output wattage of a PoE switch port to verify compliance with 802.3at"
    ],
    "correctAnswer": 1,
    "explanation": "A TDR sends a high-frequency pulse down the cable and measures the time until the reflection returns. Since the propagation speed of copper is known, the round-trip time is converted to a distance, pinpointing the location of opens, shorts, or impedance changes without requiring physical access to the fault."
  },
  {
    "id": "netplus-138",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "What is the purpose of a DNS SRV (Service) record?",
    "choices": [
      "Maps a hostname to its IPv6 address (AAAA equivalent for services)",
      "Specifies the mail server responsible for receiving email for a domain",
      "Provides the hostname, port, and priority of servers offering a specific service such as SIP or LDAP",
      "Creates an alias from one hostname to another hostname"
    ],
    "correctAnswer": 2,
    "explanation": "SRV records enable service discovery: clients query _service._proto.domain (e.g., _sip._tcp.example.com) and receive the target hostname, port number, priority, and weight. Applications like VoIP (SIP), XMPP, and Active Directory use SRV records to locate service endpoints automatically."
  },
  {
    "id": "netplus-139",
    "domain": "Networking Concepts",
    "type": "single-choice",
    "question": "Which OSI layer is responsible for establishing, managing, and terminating communication sessions between applications, including dialog control and synchronization?",
    "choices": [
      "Layer 4 — Transport (handles end-to-end delivery via TCP/UDP)",
      "Layer 6 — Presentation (handles encryption, compression, and data format translation)",
      "Layer 5 — Session (manages sessions via protocols like NetBIOS, RPC, and PPTP)",
      "Layer 7 — Application (provides user-facing network services)"
    ],
    "correctAnswer": 2,
    "explanation": "OSI Layer 5 (Session) establishes, coordinates, and terminates sessions. It handles dialog control (simplex, half-duplex, full-duplex), synchronization checkpoints (for recovery), and session multiplexing. NetBIOS and RPC are common Layer 5 protocol examples."
  },
  {
    "id": "netplus-140",
    "domain": "Network Operations",
    "type": "single-choice",
    "question": "An IT organization implements a change freeze during the holiday shopping season, prohibiting all non-emergency changes to production systems. Which change management concept does this represent?",
    "choices": [
      "A service-level agreement (SLA) clause requiring zero change-related downtime",
      "A maintenance window schedule that defers planned upgrades to off-peak hours",
      "A change moratorium restricting all non-critical modifications during a high-risk business period",
      "A rollback plan procedure activated when a prior change causes a service degradation"
    ],
    "correctAnswer": 2,
    "explanation": "A change moratorium (or change freeze) is a formal decision to prohibit non-emergency changes during periods of high business sensitivity — peak seasons, financial year-end, major events. It reduces the risk of change-induced outages when the business can least tolerate disruption."
  },
  {
    "id": "netplus-141",
    "domain": "Networking Concepts",
    "type": "multiple-response",
    "question": "Which TWO of the following are accurate characteristics of OSPF as a routing protocol? (Select two)",
    "choices": [
      "Uses Dijkstra's Shortest Path First (SPF) algorithm to calculate loop-free routes",
      "Uses hop count as its primary routing metric, like RIP",
      "Supports VLSM and CIDR, allowing it to carry subnet mask information in its LSAs",
      "Exchanges routing updates using UDP broadcasts to all directly connected routers"
    ],
    "correctAnswers": [0, 2],
    "explanation": "OSPF uses SPF (Dijkstra's algorithm) applied to its Link-State Database to calculate shortest paths (true). OSPF carries subnet masks in its LSAs, natively supporting VLSM and CIDR (true). OSPF uses cost (based on bandwidth) as its metric — not hop count — and exchanges LSAs via multicast (224.0.0.5/6) using IP protocol 89, not UDP."
  },
  {
    "id": "netplus-142",
    "domain": "Network Security",
    "type": "multiple-response",
    "question": "Which TWO configuration actions help prevent VLAN hopping attacks on an access switch? (Select two)",
    "choices": [
      "Explicitly configure all access ports as access ports and disable DTP (switchport nonegotiate)",
      "Enable STP PortFast on all trunk uplink ports to speed convergence",
      "Change the native VLAN from the default VLAN 1 to a dedicated, unused VLAN ID",
      "Enable DHCP snooping on all user-facing access VLANs"
    ],
    "correctAnswers": [0, 2],
    "explanation": "Disabling DTP on access ports prevents switch spoofing (the attacker cannot negotiate a trunk). Changing the native VLAN from VLAN 1 to an unused VLAN defeats double-tagging attacks, which rely on the attacker's outer tag matching the native VLAN. DHCP snooping protects against rogue DHCP but does not prevent VLAN hopping."
  },
  {
    "id": "netplus-143",
    "domain": "Network Troubleshooting",
    "type": "multiple-response",
    "question": "Which TWO tools are most appropriate for troubleshooting wireless connectivity issues in an enterprise environment? (Select two)",
    "choices": [
      "Wireless spectrum analyzer to detect RF interference and channel congestion",
      "TDR (Time Domain Reflectometer) for locating breaks in the copper cable runs",
      "OTDR (Optical Time Domain Reflectometer) for testing fiber patch cables",
      "Wireless site survey software showing AP coverage maps, RSSI levels, and SNR"
    ],
    "correctAnswers": [0, 3],
    "explanation": "A spectrum analyzer identifies RF interference sources (microwave ovens, neighboring Wi-Fi, Bluetooth) and channel saturation. Wireless site survey software (like Ekahau or NetSpot) maps signal coverage, identifies dead zones, and visualizes roaming boundaries. TDR and OTDR apply to wired copper and fiber, respectively."
  },
  {
    "id": "netplus-144",
    "domain": "Network Implementation",
    "type": "matching",
    "question": "Match each copper cable category to its maximum rated data rate at a 100-meter run.",
    "itemsLeft": ["Cat5e", "Cat6", "Cat6a", "Cat7"],
    "itemsRight": [
      "10 Gbps at 100 m with individual pair shielding (S/FTP)",
      "1 Gbps at 100 m",
      "10 Gbps at 55 m or 1 Gbps at 100 m",
      "10 Gbps at 100 m (augmented, standard RJ-45)"
    ],
    "correctMatches": [1, 2, 3, 0],
    "explanation": "Cat5e supports 1 Gbps at 100 m. Cat6 supports 10 Gbps only up to 55 m (or 1 Gbps at the full 100 m). Cat6a (augmented) supports 10 Gbps at the full 100 m with standard RJ-45. Cat7 also supports 10 Gbps at 100 m but requires per-pair foil shielding (S/FTP) and uses non-standard GG45 or TERA connectors."
  },
  {
    "id": "netplus-145",
    "domain": "Network Security",
    "type": "matching",
    "question": "Match each Layer 2 security feature to the specific attack it is designed to prevent.",
    "itemsLeft": ["DHCP Snooping", "Dynamic ARP Inspection (DAI)", "Port Security", "IP Source Guard"],
    "itemsRight": [
      "ARP spoofing and ARP cache poisoning",
      "IP address spoofing at Layer 3",
      "Rogue DHCP servers assigning malicious gateway or DNS configurations",
      "MAC address flooding or unauthorized device connection"
    ],
    "correctMatches": [2, 0, 3, 1],
    "explanation": "DHCP Snooping blocks rogue DHCP servers (correctMatches[0]=2). DAI validates ARP packets against the DHCP binding table to stop ARP spoofing (correctMatches[1]=0). Port Security limits the MACs allowed per port, mitigating flooding and unauthorized devices (correctMatches[2]=3). IP Source Guard drops packets whose source IP does not match the DHCP binding, stopping IP spoofing (correctMatches[3]=1)."
  },
  {
    "id": "netplus-146",
    "domain": "Network Operations",
    "type": "ordering",
    "question": "Order the IT change management process steps from first to last.",
    "items": [
      "Document the change outcome and lessons learned in the change log",
      "Submit a change request (RFC) describing scope, risk, and rollback plan",
      "Obtain formal approval from the Change Advisory Board (CAB)",
      "Implement the change during the approved maintenance window",
      "Verify success and validate that all functionality is restored after the change"
    ],
    "correctOrder": [1, 2, 3, 4, 0],
    "explanation": "Change management flow: (1) Submit RFC with scope and risk; (2) CAB reviews and approves; (3) Implement during the maintenance window; (4) Verify and validate functionality; (5) Document the outcome and update the change log. Skipping approval or documentation steps increases risk and reduces accountability."
  },
  {
    "id": "netplus-147",
    "domain": "Networking Concepts",
    "type": "ordering",
    "question": "Order the DNS resolution steps that occur when a client first queries for www.example.com, from first to last.",
    "items": [
      "The authoritative nameserver for example.com returns the A record for www.example.com",
      "The client sends a DNS query to its configured recursive resolver",
      "The TLD nameserver for .com refers the resolver to example.com's authoritative nameserver",
      "The recursive resolver queries a root nameserver for information about the .com TLD",
      "The resolver caches the answer and returns the IP address to the client"
    ],
    "correctOrder": [1, 3, 2, 0, 4],
    "explanation": "DNS resolution: (1) Client queries its recursive resolver; (2) Resolver queries a root nameserver for the .com TLD; (3) Root refers to a .com TLD nameserver; TLD refers to example.com's authoritative server; (4) Authoritative server returns the A record; (5) Resolver caches the result and returns the IP to the client."
  },
  {
    "id": "netplus-148",
    "domain": "Network Implementation",
    "type": "statement-block",
    "question": "For each statement about fiber optic cabling, indicate whether it is True or False.",
    "statements": [
      "Single-mode fiber (SMF) has a smaller core diameter (8–10 µm) than multimode fiber (MMF)",
      "Multimode fiber supports longer distances than single-mode fiber",
      "LC connectors are commonly used with SFP modules in enterprise switching environments",
      "An OTDR (Optical Time Domain Reflectometer) is used to verify copper cable wire mapping and continuity"
    ],
    "correctAnswers": [True, False, True, False],
    "explanation": "SMF core is 8–10 µm vs MMF 50–62.5 µm (true). Single-mode supports far greater distances (10 km to 80 km+) vs multimode (up to ~550 m for OM4 at 10 Gbps) — so MMF has shorter reach (false). LC connectors are the standard for SFP modules (true). An OTDR tests fiber, not copper — cable testers / TDRs test copper wire maps (false)."
  },
  {
    "id": "netplus-149",
    "domain": "Networking Concepts",
    "type": "statement-block",
    "question": "For each statement about NAT and PAT, indicate whether it is True or False.",
    "statements": [
      "PAT (Port Address Translation) allows multiple private hosts to share a single public IP address using unique source port numbers",
      "Static NAT creates a permanent one-to-one mapping between a specific private IP and a specific public IP",
      "Dynamic NAT assigns private IP addresses to hosts from a configured address pool",
      "NAT eliminates the need for routing between internal subnets on the private network"
    ],
    "correctAnswers": [True, True, False, False],
    "explanation": "PAT uses port numbers to multiplex many private addresses onto one public IP (true). Static NAT maps one private address permanently to one public address for servers that must be reachable externally (true). Dynamic NAT assigns PUBLIC addresses from a pool to translate outbound traffic — not private addresses, which are managed by DHCP (false). NAT operates at the perimeter; internal inter-subnet routing still requires a Layer 3 device (false)."
  },
  {
    "id": "netplus-150",
    "domain": "Network Troubleshooting",
    "type": "statement-block",
    "question": "For each statement about Ethernet interface error counters, indicate whether it is True or False.",
    "statements": [
      "Runt frames are Ethernet frames smaller than the minimum 64-byte size",
      "Giant frames are Ethernet frames that exceed the maximum 1518-byte size (or 1522 bytes with 802.1Q)",
      "CRC errors indicate a physical layer problem such as a damaged cable, bad SFP, or duplex mismatch",
      "Input errors on an interface always indicate a bug in the device's operating system software"
    ],
    "correctAnswers": [True, True, True, False],
    "explanation": "Runts (<64 bytes) result from collisions or hardware faults (true). Giants (>1518/1522 bytes) result from MTU mismatches, jumbo frame misconfigurations, or software bugs (true). CRC errors are a Layer 1/2 indicator of physical corruption — bad cable, dirty fiber connector, or duplex mismatch (true). Input errors indicate physical or configuration problems, not OS bugs (false)."
  }
]

data.extend(batch3)
with open('src/data/comptia-net-plus-questions.json', 'w') as f:
    json.dump(data, f, indent=2)
print(f'Written: {len(data)} questions')
